<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DesarrolladoresSeeder extends Seeder
{
    /**
     * Comienza el volcado de datos en la tabla desarrolladores
     */
    public function run()
    {
        DB::table('desarrolladores')->insert([ 'id' => '1', 'nombre' => "989 Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '2', 'nombre' => "5th Cell", ]);
        DB::table('desarrolladores')->insert([ 'id' => '3', 'nombre' => "5pb. Inc.", ]);
        DB::table('desarrolladores')->insert([ 'id' => '4', 'nombre' => "4A Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '5', 'nombre' => "42 Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '6', 'nombre' => "3G Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '7', 'nombre' => "3D Realms", ]);
        DB::table('desarrolladores')->insert([ 'id' => '8', 'nombre' => "38 Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '9', 'nombre' => "343 Industries", ]);
        DB::table('desarrolladores')->insert([ 'id' => '10', 'nombre' => "2XL Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '11', 'nombre' => "2K Czech", ]);
        DB::table('desarrolladores')->insert([ 'id' => '12', 'nombre' => "1st Playable Productions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '13', 'nombre' => "0verflow", ]);
        DB::table('desarrolladores')->insert([ 'id' => '14', 'nombre' => "Acclaim Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '15', 'nombre' => "Accolade", ]);
        DB::table('desarrolladores')->insert([ 'id' => '16', 'nombre' => "Access Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '17', 'nombre' => "Access Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '18', 'nombre' => "Aces Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '19', 'nombre' => "ACE Team", ]);
        DB::table('desarrolladores')->insert([ 'id' => '20', 'nombre' => "Acheron Design", ]);
        DB::table('desarrolladores')->insert([ 'id' => '21', 'nombre' => "Action Forms", ]);
        DB::table('desarrolladores')->insert([ 'id' => '22', 'nombre' => "Active Gaming Media", ]);
        DB::table('desarrolladores')->insert([ 'id' => '23', 'nombre' => "Activision", ]);
        DB::table('desarrolladores')->insert([ 'id' => '24', 'nombre' => "Activision Blizzard", ]);
        DB::table('desarrolladores')->insert([ 'id' => '25', 'nombre' => "Adventure Soft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '26', 'nombre' => "Akella", ]);
        DB::table('desarrolladores')->insert([ 'id' => '27', 'nombre' => "Aki Corporation", ]);
        DB::table('desarrolladores')->insert([ 'id' => '28', 'nombre' => "Alfa System", ]);
        DB::table('desarrolladores')->insert([ 'id' => '29', 'nombre' => "Amazon Game Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '30', 'nombre' => "Ancient", ]);
        DB::table('desarrolladores')->insert([ 'id' => '31', 'nombre' => "Anino Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '32', 'nombre' => "Ankama Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '33', 'nombre' => "AQ Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '34', 'nombre' => "Arc System Works", ]);
        DB::table('desarrolladores')->insert([ 'id' => '35', 'nombre' => "Arkane Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '36', 'nombre' => "Arkedo Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '37', 'nombre' => "ArenaNet", ]);
        DB::table('desarrolladores')->insert([ 'id' => '38', 'nombre' => "Arika", ]);
        DB::table('desarrolladores')->insert([ 'id' => '39', 'nombre' => "Armor Project", ]);
        DB::table('desarrolladores')->insert([ 'id' => '40', 'nombre' => "Art Co., Ltd", ]);
        DB::table('desarrolladores')->insert([ 'id' => '41', 'nombre' => "Artdink", ]);
        DB::table('desarrolladores')->insert([ 'id' => '42', 'nombre' => "ArtePiazza", ]);
        DB::table('desarrolladores')->insert([ 'id' => '43', 'nombre' => "Artificial Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '44', 'nombre' => "Artoon", ]);
        DB::table('desarrolladores')->insert([ 'id' => '45', 'nombre' => "Asobo Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '46', 'nombre' => "Ascaron", ]);
        DB::table('desarrolladores')->insert([ 'id' => '47', 'nombre' => "Atlus", ]);
        DB::table('desarrolladores')->insert([ 'id' => '48', 'nombre' => "Atomic Planet Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '49', 'nombre' => "Attic Entertainment Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '50', 'nombre' => "Avalanche Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '51', 'nombre' => "Avalanche Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '52', 'nombre' => "Aventurine SA", ]);
        DB::table('desarrolladores')->insert([ 'id' => '53', 'nombre' => "Babaroga", ]);
        DB::table('desarrolladores')->insert([ 'id' => '54', 'nombre' => "Backbone Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '55', 'nombre' => "Bandai Namco Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '56', 'nombre' => "Banpresto", ]);
        DB::table('desarrolladores')->insert([ 'id' => '57', 'nombre' => "Bauhaus Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '58', 'nombre' => "Beenox", ]);
        DB::table('desarrolladores')->insert([ 'id' => '59', 'nombre' => "Behaviour Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '60', 'nombre' => "Bethesda Softworks", ]);
        DB::table('desarrolladores')->insert([ 'id' => '61', 'nombre' => "Big Huge Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '62', 'nombre' => "Binary Hammer", ]);
        DB::table('desarrolladores')->insert([ 'id' => '63', 'nombre' => "BioWare", ]);
        DB::table('desarrolladores')->insert([ 'id' => '64', 'nombre' => "Bird Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '65', 'nombre' => "The Bitmap Brothers", ]);
        DB::table('desarrolladores')->insert([ 'id' => '66', 'nombre' => "Bits Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '67', 'nombre' => "Bizarre Creations", ]);
        DB::table('desarrolladores')->insert([ 'id' => '68', 'nombre' => "Black Forest Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '69', 'nombre' => "Black Isle Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '70', 'nombre' => "Black Rock Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '71', 'nombre' => "Black Shell Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '72', 'nombre' => "Black Wing Foundation", ]);
        DB::table('desarrolladores')->insert([ 'id' => '73', 'nombre' => "Blitz Games Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '74', 'nombre' => "Blizzard Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '75', 'nombre' => "Blue Byte Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '76', 'nombre' => "Blue Fang Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '77', 'nombre' => "Blue Tongue Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '78', 'nombre' => "Bohemia Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '79', 'nombre' => "Boss Fight Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '80', 'nombre' => "Boss Key Productions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '81', 'nombre' => "BreakAway Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '82', 'nombre' => "Brøderbund", ]);
        DB::table('desarrolladores')->insert([ 'id' => '83', 'nombre' => "Brownie Brown", ]);
        DB::table('desarrolladores')->insert([ 'id' => '84', 'nombre' => "Bullfrog Productions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '85', 'nombre' => "Buka Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '86', 'nombre' => "Bugbear Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '87', 'nombre' => "Bungie", ]);
        DB::table('desarrolladores')->insert([ 'id' => '88', 'nombre' => "Capcom", ]);
        DB::table('desarrolladores')->insert([ 'id' => '89', 'nombre' => "Capcom Vancouver", ]);
        DB::table('desarrolladores')->insert([ 'id' => '90', 'nombre' => "Carbine Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '91', 'nombre' => "Cauldron", ]);
        DB::table('desarrolladores')->insert([ 'id' => '92', 'nombre' => "Cave", ]);
        DB::table('desarrolladores')->insert([ 'id' => '93', 'nombre' => "Cavia", ]);
        DB::table('desarrolladores')->insert([ 'id' => '94', 'nombre' => "CCP Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '95', 'nombre' => "CD Projekt RED", ]);
        DB::table('desarrolladores')->insert([ 'id' => '96', 'nombre' => "Centuri", ]);
        DB::table('desarrolladores')->insert([ 'id' => '97', 'nombre' => "Certain Affinity", ]);
        DB::table('desarrolladores')->insert([ 'id' => '98', 'nombre' => "Chair Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '99', 'nombre' => "Chunsoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '100', 'nombre' => "Cing", ]);
        DB::table('desarrolladores')->insert([ 'id' => '101', 'nombre' => "Clap Hanz", ]);
        DB::table('desarrolladores')->insert([ 'id' => '102', 'nombre' => "Climax Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '103', 'nombre' => "Climax Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '104', 'nombre' => "Cloud Imperium Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '105', 'nombre' => "Coded Illusions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '106', 'nombre' => "Codemasters", ]);
        DB::table('desarrolladores')->insert([ 'id' => '107', 'nombre' => "Coktel Vision", ]);
        DB::table('desarrolladores')->insert([ 'id' => '108', 'nombre' => "Colossal Order", ]);
        DB::table('desarrolladores')->insert([ 'id' => '109', 'nombre' => "Compile Heart", ]);
        DB::table('desarrolladores')->insert([ 'id' => '110', 'nombre' => "Core Design", ]);
        DB::table('desarrolladores')->insert([ 'id' => '111', 'nombre' => "Crafts & Meister", ]);
        DB::table('desarrolladores')->insert([ 'id' => '112', 'nombre' => "Creat Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '113', 'nombre' => "Creative Assembly", ]);
        DB::table('desarrolladores')->insert([ 'id' => '114', 'nombre' => "Criterion Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '115', 'nombre' => "Croteam", ]);
        DB::table('desarrolladores')->insert([ 'id' => '116', 'nombre' => "Clover Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '117', 'nombre' => "Cryo Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '118', 'nombre' => "Cryptic Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '119', 'nombre' => "Crystal Dynamics", ]);
        DB::table('desarrolladores')->insert([ 'id' => '120', 'nombre' => "Crytek", ]);
        DB::table('desarrolladores')->insert([ 'id' => '121', 'nombre' => "Crytek UK", ]);
        DB::table('desarrolladores')->insert([ 'id' => '122', 'nombre' => "Cyberdreams", ]);
        DB::table('desarrolladores')->insert([ 'id' => '123', 'nombre' => "Cyberlore Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '124', 'nombre' => "Cyan Worlds", ]);
        DB::table('desarrolladores')->insert([ 'id' => '125', 'nombre' => "Cyanide", ]);
        DB::table('desarrolladores')->insert([ 'id' => '126', 'nombre' => "CyberConnect2", ]);
        DB::table('desarrolladores')->insert([ 'id' => '127', 'nombre' => "CyberStep", ]);
        DB::table('desarrolladores')->insert([ 'id' => '128', 'nombre' => "Dambuster Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '129', 'nombre' => "Day 1 Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '130', 'nombre' => "Deadline Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '131', 'nombre' => "Deck13", ]);
        DB::table('desarrolladores')->insert([ 'id' => '132', 'nombre' => "Demiurge Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '133', 'nombre' => "devCAT Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '134', 'nombre' => "Dhruva Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '135', 'nombre' => "Die Gute Fabrik", ]);
        DB::table('desarrolladores')->insert([ 'id' => '136', 'nombre' => "Digital Illusions CE", ]);
        DB::table('desarrolladores')->insert([ 'id' => '137', 'nombre' => "Digital Reality", ]);
        DB::table('desarrolladores')->insert([ 'id' => '138', 'nombre' => "Dimps", ]);
        DB::table('desarrolladores')->insert([ 'id' => '139', 'nombre' => "Disney Interactive Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '140', 'nombre' => "Doobic Game Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '141', 'nombre' => "Double Fine Productions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '142', 'nombre' => "Double Helix Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '143', 'nombre' => "D-Pad Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '144', 'nombre' => "Dynamix", ]);
        DB::table('desarrolladores')->insert([ 'id' => '145', 'nombre' => "Egosoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '146', 'nombre' => "Eidos Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '147', 'nombre' => "Electronic Arts", ]);
        DB::table('desarrolladores')->insert([ 'id' => '148', 'nombre' => "Elev8 Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '149', 'nombre' => "Engine Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '150', 'nombre' => "Ensemble Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '151', 'nombre' => "Epic Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '152', 'nombre' => "Epic Games Poland", ]);
        DB::table('desarrolladores')->insert([ 'id' => '153', 'nombre' => "Epicenter Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '154', 'nombre' => "Epyx", ]);
        DB::table('desarrolladores')->insert([ 'id' => '155', 'nombre' => "Etranges Libellules", ]);
        DB::table('desarrolladores')->insert([ 'id' => '156', 'nombre' => "Eugen Systems", ]);
        DB::table('desarrolladores')->insert([ 'id' => '157', 'nombre' => "Eurocom", ]);
        DB::table('desarrolladores')->insert([ 'id' => '158', 'nombre' => "Evolution Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '159', 'nombre' => "Eyedentity Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '160', 'nombre' => "F4", ]);
        DB::table('desarrolladores')->insert([ 'id' => '161', 'nombre' => "Facepunch Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '162', 'nombre' => "FarSight Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '163', 'nombre' => "Fatshark", ]);
        DB::table('desarrolladores')->insert([ 'id' => '164', 'nombre' => "feelplus", ]);
        DB::table('desarrolladores')->insert([ 'id' => '165', 'nombre' => "Firaxis Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '166', 'nombre' => "Firefly Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '167', 'nombre' => "First Star Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '168', 'nombre' => "Flagship Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '169', 'nombre' => "Flying Wild Hog", ]);
        DB::table('desarrolladores')->insert([ 'id' => '170', 'nombre' => "Foundation 9 Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '171', 'nombre' => "Fox Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '172', 'nombre' => "Frictional Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '173', 'nombre' => "Frogwares", ]);
        DB::table('desarrolladores')->insert([ 'id' => '174', 'nombre' => "FromSoftware", ]);
        DB::table('desarrolladores')->insert([ 'id' => '175', 'nombre' => "Frozenbyte", ]);
        DB::table('desarrolladores')->insert([ 'id' => '176', 'nombre' => "Frontier Developments", ]);
        DB::table('desarrolladores')->insert([ 'id' => '177', 'nombre' => "FUN Labs", ]);
        DB::table('desarrolladores')->insert([ 'id' => '178', 'nombre' => "Funcom", ]);
        DB::table('desarrolladores')->insert([ 'id' => '179', 'nombre' => "Futuremark", ]);
        DB::table('desarrolladores')->insert([ 'id' => '180', 'nombre' => "Gaijin Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '181', 'nombre' => "Game Arts", ]);
        DB::table('desarrolladores')->insert([ 'id' => '182', 'nombre' => "GameHouse", ]);
        DB::table('desarrolladores')->insert([ 'id' => '183', 'nombre' => "Gameloft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '184', 'nombre' => "Galassia Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '185', 'nombre' => "Games2win", ]);
        DB::table('desarrolladores')->insert([ 'id' => '186', 'nombre' => "Game Freak", ]);
        DB::table('desarrolladores')->insert([ 'id' => '187', 'nombre' => "Gearbox Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '188', 'nombre' => "Geewa", ]);
        DB::table('desarrolladores')->insert([ 'id' => '189', 'nombre' => "Genki", ]);
        DB::table('desarrolladores')->insert([ 'id' => '190', 'nombre' => "Giant Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '191', 'nombre' => "Glu Mobile", ]);
        DB::table('desarrolladores')->insert([ 'id' => '192', 'nombre' => "Gogii Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '193', 'nombre' => "Good-Feel", ]);
        DB::table('desarrolladores')->insert([ 'id' => '194', 'nombre' => "Grasshopper Manufacture", ]);
        DB::table('desarrolladores')->insert([ 'id' => '195', 'nombre' => "Gravity", ]);
        DB::table('desarrolladores')->insert([ 'id' => '196', 'nombre' => "Gremlin Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '197', 'nombre' => "Grezzo", ]);
        DB::table('desarrolladores')->insert([ 'id' => '198', 'nombre' => "Griptonite Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '199', 'nombre' => "GSC Game World", ]);
        DB::table('desarrolladores')->insert([ 'id' => '200', 'nombre' => "Guerrilla Cambridge", ]);
        DB::table('desarrolladores')->insert([ 'id' => '201', 'nombre' => "Guerrilla Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '202', 'nombre' => "GungHo Online Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '203', 'nombre' => "Gust Corporation", ]);
        DB::table('desarrolladores')->insert([ 'id' => '204', 'nombre' => "Haemimont Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '205', 'nombre' => "HappySoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '206', 'nombre' => "HAL Laboratory", ]);
        DB::table('desarrolladores')->insert([ 'id' => '207', 'nombre' => "Halfbrick", ]);
        DB::table('desarrolladores')->insert([ 'id' => '208', 'nombre' => "Hanaho", ]);
        DB::table('desarrolladores')->insert([ 'id' => '209', 'nombre' => "Hangar 13", ]);
        DB::table('desarrolladores')->insert([ 'id' => '210', 'nombre' => "Harebrained Schemes", ]);
        DB::table('desarrolladores')->insert([ 'id' => '211', 'nombre' => "Harmonix Music Systems", ]);
        DB::table('desarrolladores')->insert([ 'id' => '212', 'nombre' => "Hasbro Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '213', 'nombre' => "HB Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '214', 'nombre' => "HeroCraft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '215', 'nombre' => "High Moon Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '216', 'nombre' => "High Voltage Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '217', 'nombre' => "Hoplon Infotainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '218', 'nombre' => "Hothead Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '219', 'nombre' => "Housemarque", ]);
        DB::table('desarrolladores')->insert([ 'id' => '220', 'nombre' => "Hudson Soft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '221', 'nombre' => "Human Head Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '222', 'nombre' => "Humongous Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '223', 'nombre' => "Hyperion Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '224', 'nombre' => "id Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '225', 'nombre' => "Idea Factory", ]);
        DB::table('desarrolladores')->insert([ 'id' => '226', 'nombre' => "Imageepoch", ]);
        DB::table('desarrolladores')->insert([ 'id' => '227', 'nombre' => "Infinity Ward", ]);
        DB::table('desarrolladores')->insert([ 'id' => '228', 'nombre' => "Infocom", ]);
        DB::table('desarrolladores')->insert([ 'id' => '229', 'nombre' => "Infogrames", ]);
        DB::table('desarrolladores')->insert([ 'id' => '230', 'nombre' => "Incredible Technologies", ]);
        DB::table('desarrolladores')->insert([ 'id' => '231', 'nombre' => "indieszero", ]);
        DB::table('desarrolladores')->insert([ 'id' => '232', 'nombre' => "Innerloop Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '233', 'nombre' => "Insomniac Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '234', 'nombre' => "Intelligent Systems", ]);
        DB::table('desarrolladores')->insert([ 'id' => '235', 'nombre' => "Interceptor Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '236', 'nombre' => "Interplay Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '237', 'nombre' => "Inti Creates", ]);
        DB::table('desarrolladores')->insert([ 'id' => '238', 'nombre' => "Introversion Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '239', 'nombre' => "IO Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '240', 'nombre' => "Ion Storm", ]);
        DB::table('desarrolladores')->insert([ 'id' => '241', 'nombre' => "Ion Storm Austin", ]);
        DB::table('desarrolladores')->insert([ 'id' => '242', 'nombre' => "Irem", ]);
        DB::table('desarrolladores')->insert([ 'id' => '243', 'nombre' => "Iron Galaxy Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '244', 'nombre' => "Irrational Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '245', 'nombre' => "Jadestone Group", ]);
        DB::table('desarrolladores')->insert([ 'id' => '246', 'nombre' => "Jagex", ]);
        DB::table('desarrolladores')->insert([ 'id' => '247', 'nombre' => "Jaleco", ]);
        DB::table('desarrolladores')->insert([ 'id' => '248', 'nombre' => "Javaground", ]);
        DB::table('desarrolladores')->insert([ 'id' => '249', 'nombre' => "JoWood Entertainment AG", ]);
        DB::table('desarrolladores')->insert([ 'id' => '250', 'nombre' => "Juice Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '251', 'nombre' => "Jupiter", ]);
        DB::table('desarrolladores')->insert([ 'id' => '252', 'nombre' => "JV Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '253', 'nombre' => "Kairosoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '254', 'nombre' => "Kalypso Media", ]);
        DB::table('desarrolladores')->insert([ 'id' => '255', 'nombre' => "Kaos Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '256', 'nombre' => "Keen Software House", ]);
        DB::table('desarrolladores')->insert([ 'id' => '257', 'nombre' => "Kiloo Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '258', 'nombre' => "Koei", ]);
        DB::table('desarrolladores')->insert([ 'id' => '259', 'nombre' => "KOG Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '260', 'nombre' => "Konami", ]);
        DB::table('desarrolladores')->insert([ 'id' => '261', 'nombre' => "Kongzhong", ]);
        DB::table('desarrolladores')->insert([ 'id' => '262', 'nombre' => "Krome Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '263', 'nombre' => "Krome Studios Melbourne", ]);
        DB::table('desarrolladores')->insert([ 'id' => '264', 'nombre' => "Kuju Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '265', 'nombre' => "Kush Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '266', 'nombre' => "Kuma Reality Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '267', 'nombre' => "Larian Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '268', 'nombre' => "Legacy Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '269', 'nombre' => "Legend Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '270', 'nombre' => "Legendo Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '271', 'nombre' => "LEGO Group", ]);
        DB::table('desarrolladores')->insert([ 'id' => '272', 'nombre' => "Level-5", ]);
        DB::table('desarrolladores')->insert([ 'id' => '273', 'nombre' => "Lionhead Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '274', 'nombre' => "Liquid Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '275', 'nombre' => "Little Green Men Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '276', 'nombre' => "LK Avalon", ]);
        DB::table('desarrolladores')->insert([ 'id' => '277', 'nombre' => "Llamasoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '278', 'nombre' => "Linden Lab", ]);
        DB::table('desarrolladores')->insert([ 'id' => '279', 'nombre' => "Looking Glass Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '280', 'nombre' => "LucasArts", ]);
        DB::table('desarrolladores')->insert([ 'id' => '281', 'nombre' => "Luma Arcade", ]);
        DB::table('desarrolladores')->insert([ 'id' => '282', 'nombre' => "Luxoflux", ]);
        DB::table('desarrolladores')->insert([ 'id' => '283', 'nombre' => "MachineGames", ]);
        DB::table('desarrolladores')->insert([ 'id' => '284', 'nombre' => "Magenta Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '285', 'nombre' => "Majesco Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '286', 'nombre' => "Marvelous Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '287', 'nombre' => "Massive Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '288', 'nombre' => "Masthead Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '289', 'nombre' => "Maxis Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '290', 'nombre' => "Mean Hamster Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '291', 'nombre' => "Media Molecule", ]);
        DB::table('desarrolladores')->insert([ 'id' => '292', 'nombre' => "Mediatonic", ]);
        DB::table('desarrolladores')->insert([ 'id' => '293', 'nombre' => "MegaZebra", ]);
        DB::table('desarrolladores')->insert([ 'id' => '294', 'nombre' => "Mercury Steam", ]);
        DB::table('desarrolladores')->insert([ 'id' => '295', 'nombre' => "Metropolis Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '296', 'nombre' => "MicroProse Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '297', 'nombre' => "Microsoft Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '298', 'nombre' => "Midway Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '299', 'nombre' => "Milestone", ]);
        DB::table('desarrolladores')->insert([ 'id' => '300', 'nombre' => "Milestone S.r.l.", ]);
        DB::table('desarrolladores')->insert([ 'id' => '301', 'nombre' => "Mind Candy", ]);
        DB::table('desarrolladores')->insert([ 'id' => '302', 'nombre' => "Mistwalker", ]);
        DB::table('desarrolladores')->insert([ 'id' => '303', 'nombre' => "Mitchell Corporation", ]);
        DB::table('desarrolladores')->insert([ 'id' => '304', 'nombre' => "Modoka Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '305', 'nombre' => "Mojang AB", ]);
        DB::table('desarrolladores')->insert([ 'id' => '306', 'nombre' => "Monolith Productions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '307', 'nombre' => "Monolith Soft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '308', 'nombre' => "Mythic Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '309', 'nombre' => "Nadeo", ]);
        DB::table('desarrolladores')->insert([ 'id' => '310', 'nombre' => "Nanobit", ]);
        DB::table('desarrolladores')->insert([ 'id' => '311', 'nombre' => "NAPS team", ]);
        DB::table('desarrolladores')->insert([ 'id' => '312', 'nombre' => "Natsume", ]);
        DB::table('desarrolladores')->insert([ 'id' => '313', 'nombre' => "Naughty Dog", ]);
        DB::table('desarrolladores')->insert([ 'id' => '314', 'nombre' => "NCsoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '315', 'nombre' => "NDOORS Corporation", ]);
        DB::table('desarrolladores')->insert([ 'id' => '316', 'nombre' => "Neowiz", ]);
        DB::table('desarrolladores')->insert([ 'id' => '317', 'nombre' => "Nerve Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '318', 'nombre' => "NetDevil", ]);
        DB::table('desarrolladores')->insert([ 'id' => '319', 'nombre' => "Netdragon", ]);
        DB::table('desarrolladores')->insert([ 'id' => '320', 'nombre' => "Netease", ]);
        DB::table('desarrolladores')->insert([ 'id' => '321', 'nombre' => "NetherRealm Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '322', 'nombre' => "Neversoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '323', 'nombre' => "Nexon", ]);
        DB::table('desarrolladores')->insert([ 'id' => '324', 'nombre' => "Next Level Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '325', 'nombre' => "NGD Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '326', 'nombre' => "Nibris", ]);
        DB::table('desarrolladores')->insert([ 'id' => '327', 'nombre' => "Nihon Falcom", ]);
        DB::table('desarrolladores')->insert([ 'id' => '328', 'nombre' => "Ninjabee", ]);
        DB::table('desarrolladores')->insert([ 'id' => '329', 'nombre' => "Ninja Theory", ]);
        DB::table('desarrolladores')->insert([ 'id' => '330', 'nombre' => "Nintendo", ]);
        DB::table('desarrolladores')->insert([ 'id' => '331', 'nombre' => "Nippon Ichi Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '332', 'nombre' => "Nordeus", ]);
        DB::table('desarrolladores')->insert([ 'id' => '333', 'nombre' => "Novalogic", ]);
        DB::table('desarrolladores')->insert([ 'id' => '334', 'nombre' => "Novarama", ]);
        DB::table('desarrolladores')->insert([ 'id' => '335', 'nombre' => "n-Space", ]);
        DB::table('desarrolladores')->insert([ 'id' => '336', 'nombre' => "Obsidian Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '337', 'nombre' => "Oddworld Inhabitants", ]);
        DB::table('desarrolladores')->insert([ 'id' => '338', 'nombre' => "Omega Force", ]);
        DB::table('desarrolladores')->insert([ 'id' => '339', 'nombre' => "Origin Systems", ]);
        DB::table('desarrolladores')->insert([ 'id' => '340', 'nombre' => "Outrage Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '341', 'nombre' => "Overkill Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '342', 'nombre' => "Oxygen Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '343', 'nombre' => "Page 44 Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '344', 'nombre' => "Pangea Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '345', 'nombre' => "Project Sora", ]);
        DB::table('desarrolladores')->insert([ 'id' => '346', 'nombre' => "Paon", ]);
        DB::table('desarrolladores')->insert([ 'id' => '347', 'nombre' => "Papaya Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '348', 'nombre' => "Project Siren/Team Gravity", ]);
        DB::table('desarrolladores')->insert([ 'id' => '349', 'nombre' => "Project Soul", ]);
        DB::table('desarrolladores')->insert([ 'id' => '350', 'nombre' => "Panther Games Pty Ltd", ]);
        DB::table('desarrolladores')->insert([ 'id' => '351', 'nombre' => "Paradox Development Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '352', 'nombre' => "Parallax Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '353', 'nombre' => "Pandemic Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '354', 'nombre' => "Pendulo Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '355', 'nombre' => "Penguin Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '356', 'nombre' => "Perfect World", ]);
        DB::table('desarrolladores')->insert([ 'id' => '357', 'nombre' => "Petroglyph", ]);
        DB::table('desarrolladores')->insert([ 'id' => '358', 'nombre' => "Phantagram", ]);
        DB::table('desarrolladores')->insert([ 'id' => '359', 'nombre' => "Phenomic Game Development", ]);
        DB::table('desarrolladores')->insert([ 'id' => '360', 'nombre' => "Piranha Bytes", ]);
        DB::table('desarrolladores')->insert([ 'id' => '361', 'nombre' => "Pi Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '362', 'nombre' => "Pivotal Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '363', 'nombre' => "Pixel Press", ]);
        DB::table('desarrolladores')->insert([ 'id' => '364', 'nombre' => "Playdom", ]);
        DB::table('desarrolladores')->insert([ 'id' => '365', 'nombre' => "Playfish", ]);
        DB::table('desarrolladores')->insert([ 'id' => '366', 'nombre' => "PlayFirst", ]);
        DB::table('desarrolladores')->insert([ 'id' => '367', 'nombre' => "Playground Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '368', 'nombre' => "PlatinumGames", ]);
        DB::table('desarrolladores')->insert([ 'id' => '369', 'nombre' => "Polyphony Digital", ]);
        DB::table('desarrolladores')->insert([ 'id' => '370', 'nombre' => "PopCap Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '371', 'nombre' => "Press Play", ]);
        DB::table('desarrolladores')->insert([ 'id' => '372', 'nombre' => "Punch Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '373', 'nombre' => "Pyro Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '374', 'nombre' => "Q Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '375', 'nombre' => "Q-Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '376', 'nombre' => "Quantic Dream", ]);
        DB::table('desarrolladores')->insert([ 'id' => '377', 'nombre' => "Radical Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '378', 'nombre' => "Rage Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '379', 'nombre' => "Rainbow Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '380', 'nombre' => "Rare", ]);
        DB::table('desarrolladores')->insert([ 'id' => '381', 'nombre' => "Raven Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '382', 'nombre' => "Raylight S.r.l.", ]);
        DB::table('desarrolladores')->insert([ 'id' => '383', 'nombre' => "Red Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '384', 'nombre' => "Reality Pump Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '385', 'nombre' => "Realtime Associates", ]);
        DB::table('desarrolladores')->insert([ 'id' => '386', 'nombre' => "Realtime Worlds", ]);
        DB::table('desarrolladores')->insert([ 'id' => '387', 'nombre' => "Rebellion Developments", ]);
        DB::table('desarrolladores')->insert([ 'id' => '388', 'nombre' => "RedLynx", ]);
        DB::table('desarrolladores')->insert([ 'id' => '389', 'nombre' => "Red Thread Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '390', 'nombre' => "Red Storm Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '391', 'nombre' => "Redtribe", ]);
        DB::table('desarrolladores')->insert([ 'id' => '392', 'nombre' => "Reflections Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '393', 'nombre' => "Reflexive Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '394', 'nombre' => "Relic Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '395', 'nombre' => "Remedy Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '396', 'nombre' => "Respawn Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '397', 'nombre' => "Reto-Moto", ]);
        DB::table('desarrolladores')->insert([ 'id' => '398', 'nombre' => "Retro Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '399', 'nombre' => "Revolution Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '400', 'nombre' => "Riot Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '401', 'nombre' => "Rising Star Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '402', 'nombre' => "Robot Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '403', 'nombre' => "Rockstar Games Rockstar North Rockstar San Diego Rockstar Toronto", ]);
        DB::table('desarrolladores')->insert([ 'id' => '404', 'nombre' => "Rocksteady Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '405', 'nombre' => "Robinson Technologies", ]);
        DB::table('desarrolladores')->insert([ 'id' => '406', 'nombre' => "Rovio Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '407', 'nombre' => "Ruffian Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '408', 'nombre' => "Runic Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '409', 'nombre' => "Running With Scissors", ]);
        DB::table('desarrolladores')->insert([ 'id' => '410', 'nombre' => "Sand Grain Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '411', 'nombre' => "Sanuk Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '412', 'nombre' => "SCS Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '413', 'nombre' => "Sega", ]);
        DB::table('desarrolladores')->insert([ 'id' => '414', 'nombre' => "Serious Games Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '415', 'nombre' => "Sega AM2", ]);
        DB::table('desarrolladores')->insert([ 'id' => '416', 'nombre' => "SIE Foster City Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '417', 'nombre' => "SIE Japan Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '418', 'nombre' => "SIE London Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '419', 'nombre' => "SIE San Diego Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '420', 'nombre' => "SIE Santa Monica Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '421', 'nombre' => "SCE Studio Liverpool", ]);
        DB::table('desarrolladores')->insert([ 'id' => '422', 'nombre' => "SIE Worldwide Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '423', 'nombre' => "Shanda", ]);
        DB::table('desarrolladores')->insert([ 'id' => '424', 'nombre' => "Sherman3D", ]);
        DB::table('desarrolladores')->insert([ 'id' => '425', 'nombre' => "Sierra Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '426', 'nombre' => "Silicon Knights", ]);
        DB::table('desarrolladores')->insert([ 'id' => '427', 'nombre' => "Silicon Studio", ]);
        DB::table('desarrolladores')->insert([ 'id' => '428', 'nombre' => "Simtex", ]);
        DB::table('desarrolladores')->insert([ 'id' => '429', 'nombre' => "Sledgehammer Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '430', 'nombre' => "Snail Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '431', 'nombre' => "SNK Playmore", ]);
        DB::table('desarrolladores')->insert([ 'id' => '432', 'nombre' => "Sobee Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '433', 'nombre' => "Snowblind Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '434', 'nombre' => "Software 2000", ]);
        DB::table('desarrolladores')->insert([ 'id' => '435', 'nombre' => "Sonic Team", ]);
        DB::table('desarrolladores')->insert([ 'id' => '436', 'nombre' => "Sony Interactive Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '437', 'nombre' => "Sora Ltd.", ]);
        DB::table('desarrolladores')->insert([ 'id' => '438', 'nombre' => "Spectrum HoloByte", ]);
        DB::table('desarrolladores')->insert([ 'id' => '439', 'nombre' => "Spellbound Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '440', 'nombre' => "Spike", ]);
        DB::table('desarrolladores')->insert([ 'id' => '441', 'nombre' => "Spike Chunsoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '442', 'nombre' => "Spil Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '443', 'nombre' => "Splash Damage", ]);
        DB::table('desarrolladores')->insert([ 'id' => '444', 'nombre' => "Sproing Interactive Media", ]);
        DB::table('desarrolladores')->insert([ 'id' => '445', 'nombre' => "Square Enix", ]);
        DB::table('desarrolladores')->insert([ 'id' => '446', 'nombre' => "Stainless Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '447', 'nombre' => "Stainless Steel Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '448', 'nombre' => "Starbreeze Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '449', 'nombre' => "Stardock", ]);
        DB::table('desarrolladores')->insert([ 'id' => '450', 'nombre' => "Star Vault", ]);
        DB::table('desarrolladores')->insert([ 'id' => '451', 'nombre' => "Sting Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '452', 'nombre' => "Strategic Simulations", ]);
        DB::table('desarrolladores')->insert([ 'id' => '453', 'nombre' => "Strawdog Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '454', 'nombre' => "Straylight Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '455', 'nombre' => "Streamline Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '456', 'nombre' => "Sucker Punch Productions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '457', 'nombre' => "Sumo Digital", ]);
        DB::table('desarrolladores')->insert([ 'id' => '458', 'nombre' => "Sunflowers Interactive Entertainment Software", ]);
        DB::table('desarrolladores')->insert([ 'id' => '459', 'nombre' => "Supercell", ]);
        DB::table('desarrolladores')->insert([ 'id' => '460', 'nombre' => "SuperVillain Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '461', 'nombre' => "Swingin' Ape Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '462', 'nombre' => "StormRegion", ]);
        DB::table('desarrolladores')->insert([ 'id' => '463', 'nombre' => "Taito", ]);
        DB::table('desarrolladores')->insert([ 'id' => '464', 'nombre' => "Tango Gameworks", ]);
        DB::table('desarrolladores')->insert([ 'id' => '465', 'nombre' => "Tag Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '466', 'nombre' => "Take-Two Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '467', 'nombre' => "TaleWorlds", ]);
        DB::table('desarrolladores')->insert([ 'id' => '468', 'nombre' => "Tamsoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '469', 'nombre' => "Tantrumedia", ]);
        DB::table('desarrolladores')->insert([ 'id' => '470', 'nombre' => "Tantalus Media", ]);
        DB::table('desarrolladores')->insert([ 'id' => '471', 'nombre' => "Tate Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '472', 'nombre' => "Team17", ]);
        DB::table('desarrolladores')->insert([ 'id' => '473', 'nombre' => "Team Bondi", ]);
        DB::table('desarrolladores')->insert([ 'id' => '474', 'nombre' => "Team Ico", ]);
        DB::table('desarrolladores')->insert([ 'id' => '475', 'nombre' => "Team Ninja", ]);
        DB::table('desarrolladores')->insert([ 'id' => '476', 'nombre' => "Techland", ]);
        DB::table('desarrolladores')->insert([ 'id' => '477', 'nombre' => "Telltale Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '478', 'nombre' => "Tencent", ]);
        DB::table('desarrolladores')->insert([ 'id' => '479', 'nombre' => "Tequila Works", ]);
        DB::table('desarrolladores')->insert([ 'id' => '480', 'nombre' => "Terminal Reality", ]);
        DB::table('desarrolladores')->insert([ 'id' => '481', 'nombre' => "Teyon", ]);
        DB::table('desarrolladores')->insert([ 'id' => '482', 'nombre' => "The9", ]);
        DB::table('desarrolladores')->insert([ 'id' => '483', 'nombre' => "The Chinese Room", ]);
        DB::table('desarrolladores')->insert([ 'id' => '484', 'nombre' => "THQ", ]);
        DB::table('desarrolladores')->insert([ 'id' => '485', 'nombre' => "Three Rings Design", ]);
        DB::table('desarrolladores')->insert([ 'id' => '486', 'nombre' => "TimeGate Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '487', 'nombre' => "Toaplan", ]);
        DB::table('desarrolladores')->insert([ 'id' => '488', 'nombre' => "ToeJam & Earl Productions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '489', 'nombre' => "TopWare Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '490', 'nombre' => "Torpex Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '491', 'nombre' => "Torus Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '493', 'nombre' => "Toys for Bob", ]);
        DB::table('desarrolladores')->insert([ 'id' => '494', 'nombre' => "Trapdoor", ]);
        DB::table('desarrolladores')->insert([ 'id' => '495', 'nombre' => "Transmission Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '496', 'nombre' => "Traveller's Tales", ]);
        DB::table('desarrolladores')->insert([ 'id' => '497', 'nombre' => "Treyarch", ]);
        DB::table('desarrolladores')->insert([ 'id' => '498', 'nombre' => "Treasure", ]);
        DB::table('desarrolladores')->insert([ 'id' => '499', 'nombre' => "tri-Ace", ]);
        DB::table('desarrolladores')->insert([ 'id' => '500', 'nombre' => "Tripwire Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '501', 'nombre' => "Triumph Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '502', 'nombre' => "Turn 10 Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '503', 'nombre' => "Turtle Rock Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '504', 'nombre' => "Two Tribes", ]);
        DB::table('desarrolladores')->insert([ 'id' => '505', 'nombre' => "Tygron", ]);
        DB::table('desarrolladores')->insert([ 'id' => '506', 'nombre' => "Typhoon Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '507', 'nombre' => "Ubisoft", ]);
        DB::table('desarrolladores')->insert([ 'id' => '508', 'nombre' => "Ultimate Play the Game", ]);
        DB::table('desarrolladores')->insert([ 'id' => '509', 'nombre' => "Unique Development Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '510', 'nombre' => "United Front Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '511', 'nombre' => "Universomo", ]);
        DB::table('desarrolladores')->insert([ 'id' => '512', 'nombre' => "Valve Corporation", ]);
        DB::table('desarrolladores')->insert([ 'id' => '513', 'nombre' => "Vanillaware", ]);
        DB::table('desarrolladores')->insert([ 'id' => '514', 'nombre' => "Venan Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '515', 'nombre' => "Vicarious Visions", ]);
        DB::table('desarrolladores')->insert([ 'id' => '516', 'nombre' => "Vigil Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '517', 'nombre' => "Virtual Heroes, Inc.", ]);
        DB::table('desarrolladores')->insert([ 'id' => '518', 'nombre' => "Visceral Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '519', 'nombre' => "Visual Concepts", ]);
        DB::table('desarrolladores')->insert([ 'id' => '520', 'nombre' => "Vivendi Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '521', 'nombre' => "Viwawa", ]);
        DB::table('desarrolladores')->insert([ 'id' => '522', 'nombre' => "Volition, Inc.", ]);
        DB::table('desarrolladores')->insert([ 'id' => '523', 'nombre' => "Vostok Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '524', 'nombre' => "VoxelStorm", ]);
        DB::table('desarrolladores')->insert([ 'id' => '525', 'nombre' => "Wahoo Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '526', 'nombre' => "Wanako Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '527', 'nombre' => "Warhorse Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '528', 'nombre' => "Wargaming", ]);
        DB::table('desarrolladores')->insert([ 'id' => '529', 'nombre' => "Wargaming Saint Petersburg", ]);
        DB::table('desarrolladores')->insert([ 'id' => '530', 'nombre' => "WB Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '531', 'nombre' => "Webfoot Technologies", ]);
        DB::table('desarrolladores')->insert([ 'id' => '532', 'nombre' => "Westwood Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '533', 'nombre' => "Westone Bit Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '534', 'nombre' => "Wideload Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '535', 'nombre' => "Wildfire Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '536', 'nombre' => "Wizet", ]);
        DB::table('desarrolladores')->insert([ 'id' => '537', 'nombre' => "Wolfire Games", ]);
        DB::table('desarrolladores')->insert([ 'id' => '538', 'nombre' => "World Forge", ]);
        DB::table('desarrolladores')->insert([ 'id' => '539', 'nombre' => "XPEC Entertainment", ]);
        DB::table('desarrolladores')->insert([ 'id' => '540', 'nombre' => "Yager Development", ]);
        DB::table('desarrolladores')->insert([ 'id' => '541', 'nombre' => "Yuke's", ]);
        DB::table('desarrolladores')->insert([ 'id' => '542', 'nombre' => "ZeniMax Online Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '543', 'nombre' => "Zipper Interactive", ]);
        DB::table('desarrolladores')->insert([ 'id' => '544', 'nombre' => "Zombie Studios", ]);
        DB::table('desarrolladores')->insert([ 'id' => '545', 'nombre' => "ZootFly", ]);
        DB::table('desarrolladores')->insert([ 'id' => '546', 'nombre' => "Zylom", ]);
        DB::table('desarrolladores')->insert([ 'id' => '547', 'nombre' => "Zynga", ]);
        DB::table('desarrolladores')->insert([ 'id' => '548', 'nombre' => "test", ]);
        DB::table('desarrolladores')->insert([ 'id' => '549', 'nombre' => "test", ]);
    }
}
