<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DevelopersSeeder extends Seeder
{
    /**
     * Comienza el volcado de datos en la tabla developers
     */
    public function run()
    {
        DB::table('developers')->insert([ 'id' => '1', 'name' => "989 Studios", ]);
        DB::table('developers')->insert([ 'id' => '2', 'name' => "5th Cell", ]);
        DB::table('developers')->insert([ 'id' => '3', 'name' => "5pb. Inc.", ]);
        DB::table('developers')->insert([ 'id' => '4', 'name' => "4A Games", ]);
        DB::table('developers')->insert([ 'id' => '5', 'name' => "42 Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '6', 'name' => "3G Studios", ]);
        DB::table('developers')->insert([ 'id' => '7', 'name' => "3D Realms", ]);
        DB::table('developers')->insert([ 'id' => '8', 'name' => "38 Studios", ]);
        DB::table('developers')->insert([ 'id' => '9', 'name' => "343 Industries", ]);
        DB::table('developers')->insert([ 'id' => '10', 'name' => "2XL Games", ]);
        DB::table('developers')->insert([ 'id' => '11', 'name' => "2K Czech", ]);
        DB::table('developers')->insert([ 'id' => '12', 'name' => "1st Playable Productions", ]);
        DB::table('developers')->insert([ 'id' => '13', 'name' => "0verflow", ]);
        DB::table('developers')->insert([ 'id' => '14', 'name' => "Acclaim Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '15', 'name' => "Accolade", ]);
        DB::table('developers')->insert([ 'id' => '16', 'name' => "Access Games", ]);
        DB::table('developers')->insert([ 'id' => '17', 'name' => "Access Software", ]);
        DB::table('developers')->insert([ 'id' => '18', 'name' => "Aces Studio", ]);
        DB::table('developers')->insert([ 'id' => '19', 'name' => "ACE Team", ]);
        DB::table('developers')->insert([ 'id' => '20', 'name' => "Acheron Design", ]);
        DB::table('developers')->insert([ 'id' => '21', 'name' => "Action Forms", ]);
        DB::table('developers')->insert([ 'id' => '22', 'name' => "Active Gaming Media", ]);
        DB::table('developers')->insert([ 'id' => '23', 'name' => "Activision", ]);
        DB::table('developers')->insert([ 'id' => '24', 'name' => "Activision Blizzard", ]);
        DB::table('developers')->insert([ 'id' => '25', 'name' => "Adventure Soft", ]);
        DB::table('developers')->insert([ 'id' => '26', 'name' => "Akella", ]);
        DB::table('developers')->insert([ 'id' => '27', 'name' => "Aki Corporation", ]);
        DB::table('developers')->insert([ 'id' => '28', 'name' => "Alfa System", ]);
        DB::table('developers')->insert([ 'id' => '29', 'name' => "Amazon Game Studios", ]);
        DB::table('developers')->insert([ 'id' => '30', 'name' => "Ancient", ]);
        DB::table('developers')->insert([ 'id' => '31', 'name' => "Anino Games", ]);
        DB::table('developers')->insert([ 'id' => '32', 'name' => "Ankama Games", ]);
        DB::table('developers')->insert([ 'id' => '33', 'name' => "AQ Interactive", ]);
        DB::table('developers')->insert([ 'id' => '34', 'name' => "Arc System Works", ]);
        DB::table('developers')->insert([ 'id' => '35', 'name' => "Arkane Studios", ]);
        DB::table('developers')->insert([ 'id' => '36', 'name' => "Arkedo Studio", ]);
        DB::table('developers')->insert([ 'id' => '37', 'name' => "ArenaNet", ]);
        DB::table('developers')->insert([ 'id' => '38', 'name' => "Arika", ]);
        DB::table('developers')->insert([ 'id' => '39', 'name' => "Armor Project", ]);
        DB::table('developers')->insert([ 'id' => '40', 'name' => "Art Co., Ltd", ]);
        DB::table('developers')->insert([ 'id' => '41', 'name' => "Artdink", ]);
        DB::table('developers')->insert([ 'id' => '42', 'name' => "ArtePiazza", ]);
        DB::table('developers')->insert([ 'id' => '43', 'name' => "Artificial Studios", ]);
        DB::table('developers')->insert([ 'id' => '44', 'name' => "Artoon", ]);
        DB::table('developers')->insert([ 'id' => '45', 'name' => "Asobo Studio", ]);
        DB::table('developers')->insert([ 'id' => '46', 'name' => "Ascaron", ]);
        DB::table('developers')->insert([ 'id' => '47', 'name' => "Atlus", ]);
        DB::table('developers')->insert([ 'id' => '48', 'name' => "Atomic Planet Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '49', 'name' => "Attic Entertainment Software", ]);
        DB::table('developers')->insert([ 'id' => '50', 'name' => "Avalanche Studios", ]);
        DB::table('developers')->insert([ 'id' => '51', 'name' => "Avalanche Software", ]);
        DB::table('developers')->insert([ 'id' => '52', 'name' => "Aventurine SA", ]);
        DB::table('developers')->insert([ 'id' => '53', 'name' => "Babaroga", ]);
        DB::table('developers')->insert([ 'id' => '54', 'name' => "Backbone Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '55', 'name' => "Bandai Namco Studios", ]);
        DB::table('developers')->insert([ 'id' => '56', 'name' => "Banpresto", ]);
        DB::table('developers')->insert([ 'id' => '57', 'name' => "Bauhaus Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '58', 'name' => "Beenox", ]);
        DB::table('developers')->insert([ 'id' => '59', 'name' => "Behaviour Interactive", ]);
        DB::table('developers')->insert([ 'id' => '60', 'name' => "Bethesda Softworks", ]);
        DB::table('developers')->insert([ 'id' => '61', 'name' => "Big Huge Games", ]);
        DB::table('developers')->insert([ 'id' => '62', 'name' => "Binary Hammer", ]);
        DB::table('developers')->insert([ 'id' => '63', 'name' => "BioWare", ]);
        DB::table('developers')->insert([ 'id' => '64', 'name' => "Bird Studio", ]);
        DB::table('developers')->insert([ 'id' => '65', 'name' => "The Bitmap Brothers", ]);
        DB::table('developers')->insert([ 'id' => '66', 'name' => "Bits Studios", ]);
        DB::table('developers')->insert([ 'id' => '67', 'name' => "Bizarre Creations", ]);
        DB::table('developers')->insert([ 'id' => '68', 'name' => "Black Forest Games", ]);
        DB::table('developers')->insert([ 'id' => '69', 'name' => "Black Isle Studios", ]);
        DB::table('developers')->insert([ 'id' => '70', 'name' => "Black Rock Studio", ]);
        DB::table('developers')->insert([ 'id' => '71', 'name' => "Black Shell Games", ]);
        DB::table('developers')->insert([ 'id' => '72', 'name' => "Black Wing Foundation", ]);
        DB::table('developers')->insert([ 'id' => '73', 'name' => "Blitz Games Studios", ]);
        DB::table('developers')->insert([ 'id' => '74', 'name' => "Blizzard Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '75', 'name' => "Blue Byte Software", ]);
        DB::table('developers')->insert([ 'id' => '76', 'name' => "Blue Fang Games", ]);
        DB::table('developers')->insert([ 'id' => '77', 'name' => "Blue Tongue Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '78', 'name' => "Bohemia Interactive", ]);
        DB::table('developers')->insert([ 'id' => '79', 'name' => "Boss Fight Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '80', 'name' => "Boss Key Productions", ]);
        DB::table('developers')->insert([ 'id' => '81', 'name' => "BreakAway Games", ]);
        DB::table('developers')->insert([ 'id' => '82', 'name' => "Brøderbund", ]);
        DB::table('developers')->insert([ 'id' => '83', 'name' => "Brownie Brown", ]);
        DB::table('developers')->insert([ 'id' => '84', 'name' => "Bullfrog Productions", ]);
        DB::table('developers')->insert([ 'id' => '85', 'name' => "Buka Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '86', 'name' => "Bugbear Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '87', 'name' => "Bungie", ]);
        DB::table('developers')->insert([ 'id' => '88', 'name' => "Capcom", ]);
        DB::table('developers')->insert([ 'id' => '89', 'name' => "Capcom Vancouver", ]);
        DB::table('developers')->insert([ 'id' => '90', 'name' => "Carbine Studios", ]);
        DB::table('developers')->insert([ 'id' => '91', 'name' => "Cauldron", ]);
        DB::table('developers')->insert([ 'id' => '92', 'name' => "Cave", ]);
        DB::table('developers')->insert([ 'id' => '93', 'name' => "Cavia", ]);
        DB::table('developers')->insert([ 'id' => '94', 'name' => "CCP Games", ]);
        DB::table('developers')->insert([ 'id' => '95', 'name' => "CD Projekt RED", ]);
        DB::table('developers')->insert([ 'id' => '96', 'name' => "Centuri", ]);
        DB::table('developers')->insert([ 'id' => '97', 'name' => "Certain Affinity", ]);
        DB::table('developers')->insert([ 'id' => '98', 'name' => "Chair Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '99', 'name' => "Chunsoft", ]);
        DB::table('developers')->insert([ 'id' => '100', 'name' => "Cing", ]);
        DB::table('developers')->insert([ 'id' => '101', 'name' => "Clap Hanz", ]);
        DB::table('developers')->insert([ 'id' => '102', 'name' => "Climax Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '103', 'name' => "Climax Studios", ]);
        DB::table('developers')->insert([ 'id' => '104', 'name' => "Cloud Imperium Games", ]);
        DB::table('developers')->insert([ 'id' => '105', 'name' => "Coded Illusions", ]);
        DB::table('developers')->insert([ 'id' => '106', 'name' => "Codemasters", ]);
        DB::table('developers')->insert([ 'id' => '107', 'name' => "Coktel Vision", ]);
        DB::table('developers')->insert([ 'id' => '108', 'name' => "Colossal Order", ]);
        DB::table('developers')->insert([ 'id' => '109', 'name' => "Compile Heart", ]);
        DB::table('developers')->insert([ 'id' => '110', 'name' => "Core Design", ]);
        DB::table('developers')->insert([ 'id' => '111', 'name' => "Crafts & Meister", ]);
        DB::table('developers')->insert([ 'id' => '112', 'name' => "Creat Studios", ]);
        DB::table('developers')->insert([ 'id' => '113', 'name' => "Creative Assembly", ]);
        DB::table('developers')->insert([ 'id' => '114', 'name' => "Criterion Games", ]);
        DB::table('developers')->insert([ 'id' => '115', 'name' => "Croteam", ]);
        DB::table('developers')->insert([ 'id' => '116', 'name' => "Clover Studio", ]);
        DB::table('developers')->insert([ 'id' => '117', 'name' => "Cryo Interactive", ]);
        DB::table('developers')->insert([ 'id' => '118', 'name' => "Cryptic Studios", ]);
        DB::table('developers')->insert([ 'id' => '119', 'name' => "Crystal Dynamics", ]);
        DB::table('developers')->insert([ 'id' => '120', 'name' => "Crytek", ]);
        DB::table('developers')->insert([ 'id' => '121', 'name' => "Crytek UK", ]);
        DB::table('developers')->insert([ 'id' => '122', 'name' => "Cyberdreams", ]);
        DB::table('developers')->insert([ 'id' => '123', 'name' => "Cyberlore Studios", ]);
        DB::table('developers')->insert([ 'id' => '124', 'name' => "Cyan Worlds", ]);
        DB::table('developers')->insert([ 'id' => '125', 'name' => "Cyanide", ]);
        DB::table('developers')->insert([ 'id' => '126', 'name' => "CyberConnect2", ]);
        DB::table('developers')->insert([ 'id' => '127', 'name' => "CyberStep", ]);
        DB::table('developers')->insert([ 'id' => '128', 'name' => "Dambuster Studios", ]);
        DB::table('developers')->insert([ 'id' => '129', 'name' => "Day 1 Studios", ]);
        DB::table('developers')->insert([ 'id' => '130', 'name' => "Deadline Games", ]);
        DB::table('developers')->insert([ 'id' => '131', 'name' => "Deck13", ]);
        DB::table('developers')->insert([ 'id' => '132', 'name' => "Demiurge Studios", ]);
        DB::table('developers')->insert([ 'id' => '133', 'name' => "devCAT Studios", ]);
        DB::table('developers')->insert([ 'id' => '134', 'name' => "Dhruva Interactive", ]);
        DB::table('developers')->insert([ 'id' => '135', 'name' => "Die Gute Fabrik", ]);
        DB::table('developers')->insert([ 'id' => '136', 'name' => "Digital Illusions CE", ]);
        DB::table('developers')->insert([ 'id' => '137', 'name' => "Digital Reality", ]);
        DB::table('developers')->insert([ 'id' => '138', 'name' => "Dimps", ]);
        DB::table('developers')->insert([ 'id' => '139', 'name' => "Disney Interactive Studios", ]);
        DB::table('developers')->insert([ 'id' => '140', 'name' => "Doobic Game Studios", ]);
        DB::table('developers')->insert([ 'id' => '141', 'name' => "Double Fine Productions", ]);
        DB::table('developers')->insert([ 'id' => '142', 'name' => "Double Helix Games", ]);
        DB::table('developers')->insert([ 'id' => '143', 'name' => "D-Pad Studio", ]);
        DB::table('developers')->insert([ 'id' => '144', 'name' => "Dynamix", ]);
        DB::table('developers')->insert([ 'id' => '145', 'name' => "Egosoft", ]);
        DB::table('developers')->insert([ 'id' => '146', 'name' => "Eidos Interactive", ]);
        DB::table('developers')->insert([ 'id' => '147', 'name' => "Electronic Arts", ]);
        DB::table('developers')->insert([ 'id' => '148', 'name' => "Elev8 Games", ]);
        DB::table('developers')->insert([ 'id' => '149', 'name' => "Engine Software", ]);
        DB::table('developers')->insert([ 'id' => '150', 'name' => "Ensemble Studios", ]);
        DB::table('developers')->insert([ 'id' => '151', 'name' => "Epic Games", ]);
        DB::table('developers')->insert([ 'id' => '152', 'name' => "Epic Games Poland", ]);
        DB::table('developers')->insert([ 'id' => '153', 'name' => "Epicenter Studios", ]);
        DB::table('developers')->insert([ 'id' => '154', 'name' => "Epyx", ]);
        DB::table('developers')->insert([ 'id' => '155', 'name' => "Etranges Libellules", ]);
        DB::table('developers')->insert([ 'id' => '156', 'name' => "Eugen Systems", ]);
        DB::table('developers')->insert([ 'id' => '157', 'name' => "Eurocom", ]);
        DB::table('developers')->insert([ 'id' => '158', 'name' => "Evolution Studios", ]);
        DB::table('developers')->insert([ 'id' => '159', 'name' => "Eyedentity Games", ]);
        DB::table('developers')->insert([ 'id' => '160', 'name' => "F4", ]);
        DB::table('developers')->insert([ 'id' => '161', 'name' => "Facepunch Studios", ]);
        DB::table('developers')->insert([ 'id' => '162', 'name' => "FarSight Studios", ]);
        DB::table('developers')->insert([ 'id' => '163', 'name' => "Fatshark", ]);
        DB::table('developers')->insert([ 'id' => '164', 'name' => "feelplus", ]);
        DB::table('developers')->insert([ 'id' => '165', 'name' => "Firaxis Games", ]);
        DB::table('developers')->insert([ 'id' => '166', 'name' => "Firefly Studios", ]);
        DB::table('developers')->insert([ 'id' => '167', 'name' => "First Star Software", ]);
        DB::table('developers')->insert([ 'id' => '168', 'name' => "Flagship Studios", ]);
        DB::table('developers')->insert([ 'id' => '169', 'name' => "Flying Wild Hog", ]);
        DB::table('developers')->insert([ 'id' => '170', 'name' => "Foundation 9 Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '171', 'name' => "Fox Interactive", ]);
        DB::table('developers')->insert([ 'id' => '172', 'name' => "Frictional Games", ]);
        DB::table('developers')->insert([ 'id' => '173', 'name' => "Frogwares", ]);
        DB::table('developers')->insert([ 'id' => '174', 'name' => "FromSoftware", ]);
        DB::table('developers')->insert([ 'id' => '175', 'name' => "Frozenbyte", ]);
        DB::table('developers')->insert([ 'id' => '176', 'name' => "Frontier Developments", ]);
        DB::table('developers')->insert([ 'id' => '177', 'name' => "FUN Labs", ]);
        DB::table('developers')->insert([ 'id' => '178', 'name' => "Funcom", ]);
        DB::table('developers')->insert([ 'id' => '179', 'name' => "Futuremark", ]);
        DB::table('developers')->insert([ 'id' => '180', 'name' => "Gaijin Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '181', 'name' => "Game Arts", ]);
        DB::table('developers')->insert([ 'id' => '182', 'name' => "GameHouse", ]);
        DB::table('developers')->insert([ 'id' => '183', 'name' => "Gameloft", ]);
        DB::table('developers')->insert([ 'id' => '184', 'name' => "Galassia Studios", ]);
        DB::table('developers')->insert([ 'id' => '185', 'name' => "Games2win", ]);
        DB::table('developers')->insert([ 'id' => '186', 'name' => "Game Freak", ]);
        DB::table('developers')->insert([ 'id' => '187', 'name' => "Gearbox Software", ]);
        DB::table('developers')->insert([ 'id' => '188', 'name' => "Geewa", ]);
        DB::table('developers')->insert([ 'id' => '189', 'name' => "Genki", ]);
        DB::table('developers')->insert([ 'id' => '190', 'name' => "Giant Interactive", ]);
        DB::table('developers')->insert([ 'id' => '191', 'name' => "Glu Mobile", ]);
        DB::table('developers')->insert([ 'id' => '192', 'name' => "Gogii Games", ]);
        DB::table('developers')->insert([ 'id' => '193', 'name' => "Good-Feel", ]);
        DB::table('developers')->insert([ 'id' => '194', 'name' => "Grasshopper Manufacture", ]);
        DB::table('developers')->insert([ 'id' => '195', 'name' => "Gravity", ]);
        DB::table('developers')->insert([ 'id' => '196', 'name' => "Gremlin Interactive", ]);
        DB::table('developers')->insert([ 'id' => '197', 'name' => "Grezzo", ]);
        DB::table('developers')->insert([ 'id' => '198', 'name' => "Griptonite Games", ]);
        DB::table('developers')->insert([ 'id' => '199', 'name' => "GSC Game World", ]);
        DB::table('developers')->insert([ 'id' => '200', 'name' => "Guerrilla Cambridge", ]);
        DB::table('developers')->insert([ 'id' => '201', 'name' => "Guerrilla Games", ]);
        DB::table('developers')->insert([ 'id' => '202', 'name' => "GungHo Online Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '203', 'name' => "Gust Corporation", ]);
        DB::table('developers')->insert([ 'id' => '204', 'name' => "Haemimont Games", ]);
        DB::table('developers')->insert([ 'id' => '205', 'name' => "HappySoft", ]);
        DB::table('developers')->insert([ 'id' => '206', 'name' => "HAL Laboratory", ]);
        DB::table('developers')->insert([ 'id' => '207', 'name' => "Halfbrick", ]);
        DB::table('developers')->insert([ 'id' => '208', 'name' => "Hanaho", ]);
        DB::table('developers')->insert([ 'id' => '209', 'name' => "Hangar 13", ]);
        DB::table('developers')->insert([ 'id' => '210', 'name' => "Harebrained Schemes", ]);
        DB::table('developers')->insert([ 'id' => '211', 'name' => "Harmonix Music Systems", ]);
        DB::table('developers')->insert([ 'id' => '212', 'name' => "Hasbro Interactive", ]);
        DB::table('developers')->insert([ 'id' => '213', 'name' => "HB Studios", ]);
        DB::table('developers')->insert([ 'id' => '214', 'name' => "HeroCraft", ]);
        DB::table('developers')->insert([ 'id' => '215', 'name' => "High Moon Studios", ]);
        DB::table('developers')->insert([ 'id' => '216', 'name' => "High Voltage Software", ]);
        DB::table('developers')->insert([ 'id' => '217', 'name' => "Hoplon Infotainment", ]);
        DB::table('developers')->insert([ 'id' => '218', 'name' => "Hothead Games", ]);
        DB::table('developers')->insert([ 'id' => '219', 'name' => "Housemarque", ]);
        DB::table('developers')->insert([ 'id' => '220', 'name' => "Hudson Soft", ]);
        DB::table('developers')->insert([ 'id' => '221', 'name' => "Human Head Studios", ]);
        DB::table('developers')->insert([ 'id' => '222', 'name' => "Humongous Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '223', 'name' => "Hyperion Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '224', 'name' => "id Software", ]);
        DB::table('developers')->insert([ 'id' => '225', 'name' => "Idea Factory", ]);
        DB::table('developers')->insert([ 'id' => '226', 'name' => "Imageepoch", ]);
        DB::table('developers')->insert([ 'id' => '227', 'name' => "Infinity Ward", ]);
        DB::table('developers')->insert([ 'id' => '228', 'name' => "Infocom", ]);
        DB::table('developers')->insert([ 'id' => '229', 'name' => "Infogrames", ]);
        DB::table('developers')->insert([ 'id' => '230', 'name' => "Incredible Technologies", ]);
        DB::table('developers')->insert([ 'id' => '231', 'name' => "indieszero", ]);
        DB::table('developers')->insert([ 'id' => '232', 'name' => "Innerloop Studios", ]);
        DB::table('developers')->insert([ 'id' => '233', 'name' => "Insomniac Games", ]);
        DB::table('developers')->insert([ 'id' => '234', 'name' => "Intelligent Systems", ]);
        DB::table('developers')->insert([ 'id' => '235', 'name' => "Interceptor Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '236', 'name' => "Interplay Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '237', 'name' => "Inti Creates", ]);
        DB::table('developers')->insert([ 'id' => '238', 'name' => "Introversion Software", ]);
        DB::table('developers')->insert([ 'id' => '239', 'name' => "IO Interactive", ]);
        DB::table('developers')->insert([ 'id' => '240', 'name' => "Ion Storm", ]);
        DB::table('developers')->insert([ 'id' => '241', 'name' => "Ion Storm Austin", ]);
        DB::table('developers')->insert([ 'id' => '242', 'name' => "Irem", ]);
        DB::table('developers')->insert([ 'id' => '243', 'name' => "Iron Galaxy Studios", ]);
        DB::table('developers')->insert([ 'id' => '244', 'name' => "Irrational Games", ]);
        DB::table('developers')->insert([ 'id' => '245', 'name' => "Jadestone Group", ]);
        DB::table('developers')->insert([ 'id' => '246', 'name' => "Jagex", ]);
        DB::table('developers')->insert([ 'id' => '247', 'name' => "Jaleco", ]);
        DB::table('developers')->insert([ 'id' => '248', 'name' => "Javaground", ]);
        DB::table('developers')->insert([ 'id' => '249', 'name' => "JoWood Entertainment AG", ]);
        DB::table('developers')->insert([ 'id' => '250', 'name' => "Juice Games", ]);
        DB::table('developers')->insert([ 'id' => '251', 'name' => "Jupiter", ]);
        DB::table('developers')->insert([ 'id' => '252', 'name' => "JV Games", ]);
        DB::table('developers')->insert([ 'id' => '253', 'name' => "Kairosoft", ]);
        DB::table('developers')->insert([ 'id' => '254', 'name' => "Kalypso Media", ]);
        DB::table('developers')->insert([ 'id' => '255', 'name' => "Kaos Studios", ]);
        DB::table('developers')->insert([ 'id' => '256', 'name' => "Keen Software House", ]);
        DB::table('developers')->insert([ 'id' => '257', 'name' => "Kiloo Games", ]);
        DB::table('developers')->insert([ 'id' => '258', 'name' => "Koei", ]);
        DB::table('developers')->insert([ 'id' => '259', 'name' => "KOG Studios", ]);
        DB::table('developers')->insert([ 'id' => '260', 'name' => "Konami", ]);
        DB::table('developers')->insert([ 'id' => '261', 'name' => "Kongzhong", ]);
        DB::table('developers')->insert([ 'id' => '262', 'name' => "Krome Studios", ]);
        DB::table('developers')->insert([ 'id' => '263', 'name' => "Krome Studios Melbourne", ]);
        DB::table('developers')->insert([ 'id' => '264', 'name' => "Kuju Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '265', 'name' => "Kush Games", ]);
        DB::table('developers')->insert([ 'id' => '266', 'name' => "Kuma Reality Games", ]);
        DB::table('developers')->insert([ 'id' => '267', 'name' => "Larian Studios", ]);
        DB::table('developers')->insert([ 'id' => '268', 'name' => "Legacy Interactive", ]);
        DB::table('developers')->insert([ 'id' => '269', 'name' => "Legend Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '270', 'name' => "Legendo Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '271', 'name' => "LEGO Group", ]);
        DB::table('developers')->insert([ 'id' => '272', 'name' => "Level-5", ]);
        DB::table('developers')->insert([ 'id' => '273', 'name' => "Lionhead Studios", ]);
        DB::table('developers')->insert([ 'id' => '274', 'name' => "Liquid Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '275', 'name' => "Little Green Men Games", ]);
        DB::table('developers')->insert([ 'id' => '276', 'name' => "LK Avalon", ]);
        DB::table('developers')->insert([ 'id' => '277', 'name' => "Llamasoft", ]);
        DB::table('developers')->insert([ 'id' => '278', 'name' => "Linden Lab", ]);
        DB::table('developers')->insert([ 'id' => '279', 'name' => "Looking Glass Studios", ]);
        DB::table('developers')->insert([ 'id' => '280', 'name' => "LucasArts", ]);
        DB::table('developers')->insert([ 'id' => '281', 'name' => "Luma Arcade", ]);
        DB::table('developers')->insert([ 'id' => '282', 'name' => "Luxoflux", ]);
        DB::table('developers')->insert([ 'id' => '283', 'name' => "MachineGames", ]);
        DB::table('developers')->insert([ 'id' => '284', 'name' => "Magenta Software", ]);
        DB::table('developers')->insert([ 'id' => '285', 'name' => "Majesco Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '286', 'name' => "Marvelous Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '287', 'name' => "Massive Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '288', 'name' => "Masthead Studios", ]);
        DB::table('developers')->insert([ 'id' => '289', 'name' => "Maxis Software", ]);
        DB::table('developers')->insert([ 'id' => '290', 'name' => "Mean Hamster Software", ]);
        DB::table('developers')->insert([ 'id' => '291', 'name' => "Media Molecule", ]);
        DB::table('developers')->insert([ 'id' => '292', 'name' => "Mediatonic", ]);
        DB::table('developers')->insert([ 'id' => '293', 'name' => "MegaZebra", ]);
        DB::table('developers')->insert([ 'id' => '294', 'name' => "Mercury Steam", ]);
        DB::table('developers')->insert([ 'id' => '295', 'name' => "Metropolis Software", ]);
        DB::table('developers')->insert([ 'id' => '296', 'name' => "MicroProse Software", ]);
        DB::table('developers')->insert([ 'id' => '297', 'name' => "Microsoft Studios", ]);
        DB::table('developers')->insert([ 'id' => '298', 'name' => "Midway Games", ]);
        DB::table('developers')->insert([ 'id' => '299', 'name' => "Milestone", ]);
        DB::table('developers')->insert([ 'id' => '300', 'name' => "Milestone S.r.l.", ]);
        DB::table('developers')->insert([ 'id' => '301', 'name' => "Mind Candy", ]);
        DB::table('developers')->insert([ 'id' => '302', 'name' => "Mistwalker", ]);
        DB::table('developers')->insert([ 'id' => '303', 'name' => "Mitchell Corporation", ]);
        DB::table('developers')->insert([ 'id' => '304', 'name' => "Modoka Studios", ]);
        DB::table('developers')->insert([ 'id' => '305', 'name' => "Mojang AB", ]);
        DB::table('developers')->insert([ 'id' => '306', 'name' => "Monolith Productions", ]);
        DB::table('developers')->insert([ 'id' => '307', 'name' => "Monolith Soft", ]);
        DB::table('developers')->insert([ 'id' => '308', 'name' => "Mythic Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '309', 'name' => "Nadeo", ]);
        DB::table('developers')->insert([ 'id' => '310', 'name' => "Nanobit", ]);
        DB::table('developers')->insert([ 'id' => '311', 'name' => "NAPS team", ]);
        DB::table('developers')->insert([ 'id' => '312', 'name' => "Natsume", ]);
        DB::table('developers')->insert([ 'id' => '313', 'name' => "Naughty Dog", ]);
        DB::table('developers')->insert([ 'id' => '314', 'name' => "NCsoft", ]);
        DB::table('developers')->insert([ 'id' => '315', 'name' => "NDOORS Corporation", ]);
        DB::table('developers')->insert([ 'id' => '316', 'name' => "Neowiz", ]);
        DB::table('developers')->insert([ 'id' => '317', 'name' => "Nerve Software", ]);
        DB::table('developers')->insert([ 'id' => '318', 'name' => "NetDevil", ]);
        DB::table('developers')->insert([ 'id' => '319', 'name' => "Netdragon", ]);
        DB::table('developers')->insert([ 'id' => '320', 'name' => "Netease", ]);
        DB::table('developers')->insert([ 'id' => '321', 'name' => "NetherRealm Studios", ]);
        DB::table('developers')->insert([ 'id' => '322', 'name' => "Neversoft", ]);
        DB::table('developers')->insert([ 'id' => '323', 'name' => "Nexon", ]);
        DB::table('developers')->insert([ 'id' => '324', 'name' => "Next Level Games", ]);
        DB::table('developers')->insert([ 'id' => '325', 'name' => "NGD Studios", ]);
        DB::table('developers')->insert([ 'id' => '326', 'name' => "Nibris", ]);
        DB::table('developers')->insert([ 'id' => '327', 'name' => "Nihon Falcom", ]);
        DB::table('developers')->insert([ 'id' => '328', 'name' => "Ninjabee", ]);
        DB::table('developers')->insert([ 'id' => '329', 'name' => "Ninja Theory", ]);
        DB::table('developers')->insert([ 'id' => '330', 'name' => "Nintendo", ]);
        DB::table('developers')->insert([ 'id' => '331', 'name' => "Nippon Ichi Software", ]);
        DB::table('developers')->insert([ 'id' => '332', 'name' => "Nordeus", ]);
        DB::table('developers')->insert([ 'id' => '333', 'name' => "Novalogic", ]);
        DB::table('developers')->insert([ 'id' => '334', 'name' => "Novarama", ]);
        DB::table('developers')->insert([ 'id' => '335', 'name' => "n-Space", ]);
        DB::table('developers')->insert([ 'id' => '336', 'name' => "Obsidian Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '337', 'name' => "Oddworld Inhabitants", ]);
        DB::table('developers')->insert([ 'id' => '338', 'name' => "Omega Force", ]);
        DB::table('developers')->insert([ 'id' => '339', 'name' => "Origin Systems", ]);
        DB::table('developers')->insert([ 'id' => '340', 'name' => "Outrage Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '341', 'name' => "Overkill Software", ]);
        DB::table('developers')->insert([ 'id' => '342', 'name' => "Oxygen Studios", ]);
        DB::table('developers')->insert([ 'id' => '343', 'name' => "Page 44 Studios", ]);
        DB::table('developers')->insert([ 'id' => '344', 'name' => "Pangea Software", ]);
        DB::table('developers')->insert([ 'id' => '345', 'name' => "Project Sora", ]);
        DB::table('developers')->insert([ 'id' => '346', 'name' => "Paon", ]);
        DB::table('developers')->insert([ 'id' => '347', 'name' => "Papaya Studio", ]);
        DB::table('developers')->insert([ 'id' => '348', 'name' => "Project Siren/Team Gravity", ]);
        DB::table('developers')->insert([ 'id' => '349', 'name' => "Project Soul", ]);
        DB::table('developers')->insert([ 'id' => '350', 'name' => "Panther Games Pty Ltd", ]);
        DB::table('developers')->insert([ 'id' => '351', 'name' => "Paradox Development Studio", ]);
        DB::table('developers')->insert([ 'id' => '352', 'name' => "Parallax Software", ]);
        DB::table('developers')->insert([ 'id' => '353', 'name' => "Pandemic Studios", ]);
        DB::table('developers')->insert([ 'id' => '354', 'name' => "Pendulo Studios", ]);
        DB::table('developers')->insert([ 'id' => '355', 'name' => "Penguin Software", ]);
        DB::table('developers')->insert([ 'id' => '356', 'name' => "Perfect World", ]);
        DB::table('developers')->insert([ 'id' => '357', 'name' => "Petroglyph", ]);
        DB::table('developers')->insert([ 'id' => '358', 'name' => "Phantagram", ]);
        DB::table('developers')->insert([ 'id' => '359', 'name' => "Phenomic Game Development", ]);
        DB::table('developers')->insert([ 'id' => '360', 'name' => "Piranha Bytes", ]);
        DB::table('developers')->insert([ 'id' => '361', 'name' => "Pi Studios", ]);
        DB::table('developers')->insert([ 'id' => '362', 'name' => "Pivotal Games", ]);
        DB::table('developers')->insert([ 'id' => '363', 'name' => "Pixel Press", ]);
        DB::table('developers')->insert([ 'id' => '364', 'name' => "Playdom", ]);
        DB::table('developers')->insert([ 'id' => '365', 'name' => "Playfish", ]);
        DB::table('developers')->insert([ 'id' => '366', 'name' => "PlayFirst", ]);
        DB::table('developers')->insert([ 'id' => '367', 'name' => "Playground Games", ]);
        DB::table('developers')->insert([ 'id' => '368', 'name' => "PlatinumGames", ]);
        DB::table('developers')->insert([ 'id' => '369', 'name' => "Polyphony Digital", ]);
        DB::table('developers')->insert([ 'id' => '370', 'name' => "PopCap Games", ]);
        DB::table('developers')->insert([ 'id' => '371', 'name' => "Press Play", ]);
        DB::table('developers')->insert([ 'id' => '372', 'name' => "Punch Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '373', 'name' => "Pyro Studios", ]);
        DB::table('developers')->insert([ 'id' => '374', 'name' => "Q Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '375', 'name' => "Q-Games", ]);
        DB::table('developers')->insert([ 'id' => '376', 'name' => "Quantic Dream", ]);
        DB::table('developers')->insert([ 'id' => '377', 'name' => "Radical Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '378', 'name' => "Rage Software", ]);
        DB::table('developers')->insert([ 'id' => '379', 'name' => "Rainbow Studios", ]);
        DB::table('developers')->insert([ 'id' => '380', 'name' => "Rare", ]);
        DB::table('developers')->insert([ 'id' => '381', 'name' => "Raven Software", ]);
        DB::table('developers')->insert([ 'id' => '382', 'name' => "Raylight S.r.l.", ]);
        DB::table('developers')->insert([ 'id' => '383', 'name' => "Red Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '384', 'name' => "Reality Pump Studios", ]);
        DB::table('developers')->insert([ 'id' => '385', 'name' => "Realtime Associates", ]);
        DB::table('developers')->insert([ 'id' => '386', 'name' => "Realtime Worlds", ]);
        DB::table('developers')->insert([ 'id' => '387', 'name' => "Rebellion Developments", ]);
        DB::table('developers')->insert([ 'id' => '388', 'name' => "RedLynx", ]);
        DB::table('developers')->insert([ 'id' => '389', 'name' => "Red Thread Games", ]);
        DB::table('developers')->insert([ 'id' => '390', 'name' => "Red Storm Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '391', 'name' => "Redtribe", ]);
        DB::table('developers')->insert([ 'id' => '392', 'name' => "Reflections Interactive", ]);
        DB::table('developers')->insert([ 'id' => '393', 'name' => "Reflexive Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '394', 'name' => "Relic Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '395', 'name' => "Remedy Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '396', 'name' => "Respawn Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '397', 'name' => "Reto-Moto", ]);
        DB::table('developers')->insert([ 'id' => '398', 'name' => "Retro Studios", ]);
        DB::table('developers')->insert([ 'id' => '399', 'name' => "Revolution Software", ]);
        DB::table('developers')->insert([ 'id' => '400', 'name' => "Riot Games", ]);
        DB::table('developers')->insert([ 'id' => '401', 'name' => "Rising Star Games", ]);
        DB::table('developers')->insert([ 'id' => '402', 'name' => "Robot Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '403', 'name' => "Rockstar Games Rockstar North Rockstar San Diego Rockstar Toronto", ]);
        DB::table('developers')->insert([ 'id' => '404', 'name' => "Rocksteady Studios", ]);
        DB::table('developers')->insert([ 'id' => '405', 'name' => "Robinson Technologies", ]);
        DB::table('developers')->insert([ 'id' => '406', 'name' => "Rovio Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '407', 'name' => "Ruffian Games", ]);
        DB::table('developers')->insert([ 'id' => '408', 'name' => "Runic Games", ]);
        DB::table('developers')->insert([ 'id' => '409', 'name' => "Running With Scissors", ]);
        DB::table('developers')->insert([ 'id' => '410', 'name' => "Sand Grain Studios", ]);
        DB::table('developers')->insert([ 'id' => '411', 'name' => "Sanuk Games", ]);
        DB::table('developers')->insert([ 'id' => '412', 'name' => "SCS Software", ]);
        DB::table('developers')->insert([ 'id' => '413', 'name' => "Sega", ]);
        DB::table('developers')->insert([ 'id' => '414', 'name' => "Serious Games Interactive", ]);
        DB::table('developers')->insert([ 'id' => '415', 'name' => "Sega AM2", ]);
        DB::table('developers')->insert([ 'id' => '416', 'name' => "SIE Foster City Studio", ]);
        DB::table('developers')->insert([ 'id' => '417', 'name' => "SIE Japan Studio", ]);
        DB::table('developers')->insert([ 'id' => '418', 'name' => "SIE London Studio", ]);
        DB::table('developers')->insert([ 'id' => '419', 'name' => "SIE San Diego Studio", ]);
        DB::table('developers')->insert([ 'id' => '420', 'name' => "SIE Santa Monica Studio", ]);
        DB::table('developers')->insert([ 'id' => '421', 'name' => "SCE Studio Liverpool", ]);
        DB::table('developers')->insert([ 'id' => '422', 'name' => "SIE Worldwide Studios", ]);
        DB::table('developers')->insert([ 'id' => '423', 'name' => "Shanda", ]);
        DB::table('developers')->insert([ 'id' => '424', 'name' => "Sherman3D", ]);
        DB::table('developers')->insert([ 'id' => '425', 'name' => "Sierra Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '426', 'name' => "Silicon Knights", ]);
        DB::table('developers')->insert([ 'id' => '427', 'name' => "Silicon Studio", ]);
        DB::table('developers')->insert([ 'id' => '428', 'name' => "Simtex", ]);
        DB::table('developers')->insert([ 'id' => '429', 'name' => "Sledgehammer Games", ]);
        DB::table('developers')->insert([ 'id' => '430', 'name' => "Snail Games", ]);
        DB::table('developers')->insert([ 'id' => '431', 'name' => "SNK Playmore", ]);
        DB::table('developers')->insert([ 'id' => '432', 'name' => "Sobee Studios", ]);
        DB::table('developers')->insert([ 'id' => '433', 'name' => "Snowblind Studios", ]);
        DB::table('developers')->insert([ 'id' => '434', 'name' => "Software 2000", ]);
        DB::table('developers')->insert([ 'id' => '435', 'name' => "Sonic Team", ]);
        DB::table('developers')->insert([ 'id' => '436', 'name' => "Sony Interactive Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '437', 'name' => "Sora Ltd.", ]);
        DB::table('developers')->insert([ 'id' => '438', 'name' => "Spectrum HoloByte", ]);
        DB::table('developers')->insert([ 'id' => '439', 'name' => "Spellbound Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '440', 'name' => "Spike", ]);
        DB::table('developers')->insert([ 'id' => '441', 'name' => "Spike Chunsoft", ]);
        DB::table('developers')->insert([ 'id' => '442', 'name' => "Spil Games", ]);
        DB::table('developers')->insert([ 'id' => '443', 'name' => "Splash Damage", ]);
        DB::table('developers')->insert([ 'id' => '444', 'name' => "Sproing Interactive Media", ]);
        DB::table('developers')->insert([ 'id' => '445', 'name' => "Square Enix", ]);
        DB::table('developers')->insert([ 'id' => '446', 'name' => "Stainless Games", ]);
        DB::table('developers')->insert([ 'id' => '447', 'name' => "Stainless Steel Studios", ]);
        DB::table('developers')->insert([ 'id' => '448', 'name' => "Starbreeze Studios", ]);
        DB::table('developers')->insert([ 'id' => '449', 'name' => "Stardock", ]);
        DB::table('developers')->insert([ 'id' => '450', 'name' => "Star Vault", ]);
        DB::table('developers')->insert([ 'id' => '451', 'name' => "Sting Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '452', 'name' => "Strategic Simulations", ]);
        DB::table('developers')->insert([ 'id' => '453', 'name' => "Strawdog Studios", ]);
        DB::table('developers')->insert([ 'id' => '454', 'name' => "Straylight Studios", ]);
        DB::table('developers')->insert([ 'id' => '455', 'name' => "Streamline Studios", ]);
        DB::table('developers')->insert([ 'id' => '456', 'name' => "Sucker Punch Productions", ]);
        DB::table('developers')->insert([ 'id' => '457', 'name' => "Sumo Digital", ]);
        DB::table('developers')->insert([ 'id' => '458', 'name' => "Sunflowers Interactive Entertainment Software", ]);
        DB::table('developers')->insert([ 'id' => '459', 'name' => "Supercell", ]);
        DB::table('developers')->insert([ 'id' => '460', 'name' => "SuperVillain Studios", ]);
        DB::table('developers')->insert([ 'id' => '461', 'name' => "Swingin' Ape Studios", ]);
        DB::table('developers')->insert([ 'id' => '462', 'name' => "StormRegion", ]);
        DB::table('developers')->insert([ 'id' => '463', 'name' => "Taito", ]);
        DB::table('developers')->insert([ 'id' => '464', 'name' => "Tango Gameworks", ]);
        DB::table('developers')->insert([ 'id' => '465', 'name' => "Tag Games", ]);
        DB::table('developers')->insert([ 'id' => '466', 'name' => "Take-Two Interactive", ]);
        DB::table('developers')->insert([ 'id' => '467', 'name' => "TaleWorlds", ]);
        DB::table('developers')->insert([ 'id' => '468', 'name' => "Tamsoft", ]);
        DB::table('developers')->insert([ 'id' => '469', 'name' => "Tantrumedia", ]);
        DB::table('developers')->insert([ 'id' => '470', 'name' => "Tantalus Media", ]);
        DB::table('developers')->insert([ 'id' => '471', 'name' => "Tate Interactive", ]);
        DB::table('developers')->insert([ 'id' => '472', 'name' => "Team17", ]);
        DB::table('developers')->insert([ 'id' => '473', 'name' => "Team Bondi", ]);
        DB::table('developers')->insert([ 'id' => '474', 'name' => "Team Ico", ]);
        DB::table('developers')->insert([ 'id' => '475', 'name' => "Team Ninja", ]);
        DB::table('developers')->insert([ 'id' => '476', 'name' => "Techland", ]);
        DB::table('developers')->insert([ 'id' => '477', 'name' => "Telltale Games", ]);
        DB::table('developers')->insert([ 'id' => '478', 'name' => "Tencent", ]);
        DB::table('developers')->insert([ 'id' => '479', 'name' => "Tequila Works", ]);
        DB::table('developers')->insert([ 'id' => '480', 'name' => "Terminal Reality", ]);
        DB::table('developers')->insert([ 'id' => '481', 'name' => "Teyon", ]);
        DB::table('developers')->insert([ 'id' => '482', 'name' => "The9", ]);
        DB::table('developers')->insert([ 'id' => '483', 'name' => "The Chinese Room", ]);
        DB::table('developers')->insert([ 'id' => '484', 'name' => "THQ", ]);
        DB::table('developers')->insert([ 'id' => '485', 'name' => "Three Rings Design", ]);
        DB::table('developers')->insert([ 'id' => '486', 'name' => "TimeGate Studios", ]);
        DB::table('developers')->insert([ 'id' => '487', 'name' => "Toaplan", ]);
        DB::table('developers')->insert([ 'id' => '488', 'name' => "ToeJam & Earl Productions", ]);
        DB::table('developers')->insert([ 'id' => '489', 'name' => "TopWare Interactive", ]);
        DB::table('developers')->insert([ 'id' => '490', 'name' => "Torpex Games", ]);
        DB::table('developers')->insert([ 'id' => '491', 'name' => "Torus Games", ]);
        DB::table('developers')->insert([ 'id' => '493', 'name' => "Toys for Bob", ]);
        DB::table('developers')->insert([ 'id' => '494', 'name' => "Trapdoor", ]);
        DB::table('developers')->insert([ 'id' => '495', 'name' => "Transmission Games", ]);
        DB::table('developers')->insert([ 'id' => '496', 'name' => "Traveller's Tales", ]);
        DB::table('developers')->insert([ 'id' => '497', 'name' => "Treyarch", ]);
        DB::table('developers')->insert([ 'id' => '498', 'name' => "Treasure", ]);
        DB::table('developers')->insert([ 'id' => '499', 'name' => "tri-Ace", ]);
        DB::table('developers')->insert([ 'id' => '500', 'name' => "Tripwire Interactive", ]);
        DB::table('developers')->insert([ 'id' => '501', 'name' => "Triumph Studios", ]);
        DB::table('developers')->insert([ 'id' => '502', 'name' => "Turn 10 Studios", ]);
        DB::table('developers')->insert([ 'id' => '503', 'name' => "Turtle Rock Studios", ]);
        DB::table('developers')->insert([ 'id' => '504', 'name' => "Two Tribes", ]);
        DB::table('developers')->insert([ 'id' => '505', 'name' => "Tygron", ]);
        DB::table('developers')->insert([ 'id' => '506', 'name' => "Typhoon Games", ]);
        DB::table('developers')->insert([ 'id' => '507', 'name' => "Ubisoft", ]);
        DB::table('developers')->insert([ 'id' => '508', 'name' => "Ultimate Play the Game", ]);
        DB::table('developers')->insert([ 'id' => '509', 'name' => "Unique Development Studios", ]);
        DB::table('developers')->insert([ 'id' => '510', 'name' => "United Front Games", ]);
        DB::table('developers')->insert([ 'id' => '511', 'name' => "Universomo", ]);
        DB::table('developers')->insert([ 'id' => '512', 'name' => "Valve Corporation", ]);
        DB::table('developers')->insert([ 'id' => '513', 'name' => "Vanillaware", ]);
        DB::table('developers')->insert([ 'id' => '514', 'name' => "Venan Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '515', 'name' => "Vicarious Visions", ]);
        DB::table('developers')->insert([ 'id' => '516', 'name' => "Vigil Games", ]);
        DB::table('developers')->insert([ 'id' => '517', 'name' => "Virtual Heroes, Inc.", ]);
        DB::table('developers')->insert([ 'id' => '518', 'name' => "Visceral Games", ]);
        DB::table('developers')->insert([ 'id' => '519', 'name' => "Visual Concepts", ]);
        DB::table('developers')->insert([ 'id' => '520', 'name' => "Vivendi Games", ]);
        DB::table('developers')->insert([ 'id' => '521', 'name' => "Viwawa", ]);
        DB::table('developers')->insert([ 'id' => '522', 'name' => "Volition, Inc.", ]);
        DB::table('developers')->insert([ 'id' => '523', 'name' => "Vostok Games", ]);
        DB::table('developers')->insert([ 'id' => '524', 'name' => "VoxelStorm", ]);
        DB::table('developers')->insert([ 'id' => '525', 'name' => "Wahoo Studios", ]);
        DB::table('developers')->insert([ 'id' => '526', 'name' => "Wanako Games", ]);
        DB::table('developers')->insert([ 'id' => '527', 'name' => "Warhorse Studios", ]);
        DB::table('developers')->insert([ 'id' => '528', 'name' => "Wargaming", ]);
        DB::table('developers')->insert([ 'id' => '529', 'name' => "Wargaming Saint Petersburg", ]);
        DB::table('developers')->insert([ 'id' => '530', 'name' => "WB Games", ]);
        DB::table('developers')->insert([ 'id' => '531', 'name' => "Webfoot Technologies", ]);
        DB::table('developers')->insert([ 'id' => '532', 'name' => "Westwood Studios", ]);
        DB::table('developers')->insert([ 'id' => '533', 'name' => "Westone Bit Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '534', 'name' => "Wideload Games", ]);
        DB::table('developers')->insert([ 'id' => '535', 'name' => "Wildfire Studios", ]);
        DB::table('developers')->insert([ 'id' => '536', 'name' => "Wizet", ]);
        DB::table('developers')->insert([ 'id' => '537', 'name' => "Wolfire Games", ]);
        DB::table('developers')->insert([ 'id' => '538', 'name' => "World Forge", ]);
        DB::table('developers')->insert([ 'id' => '539', 'name' => "XPEC Entertainment", ]);
        DB::table('developers')->insert([ 'id' => '540', 'name' => "Yager Development", ]);
        DB::table('developers')->insert([ 'id' => '541', 'name' => "Yuke's", ]);
        DB::table('developers')->insert([ 'id' => '542', 'name' => "ZeniMax Online Studios", ]);
        DB::table('developers')->insert([ 'id' => '543', 'name' => "Zipper Interactive", ]);
        DB::table('developers')->insert([ 'id' => '544', 'name' => "Zombie Studios", ]);
        DB::table('developers')->insert([ 'id' => '545', 'name' => "ZootFly", ]);
        DB::table('developers')->insert([ 'id' => '546', 'name' => "Zylom", ]);
        DB::table('developers')->insert([ 'id' => '547', 'name' => "Zynga", ]);
        DB::table('developers')->insert([ 'id' => '548', 'name' => "test", ]);
        DB::table('developers')->insert([ 'id' => '549', 'name' => "test", ]);
    }
}
