<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistributorsSeeder extends Seeder
{
    /**
     * Comienza el volcado de datos en la tabla distributors
     */
    public function run()
    {
        DB::table('distributors')->insert([ 'id' => '1', 'name' => "1C Company", ]);
        DB::table('distributors')->insert([ 'id' => '2', 'name' => "2K Games", ]);
        DB::table('distributors')->insert([ 'id' => '3', 'name' => "3D Realms", ]);
        DB::table('distributors')->insert([ 'id' => '4', 'name' => "The 3DO Company", ]);
        DB::table('distributors')->insert([ 'id' => '5', 'name' => "505 Games", ]);
        DB::table('distributors')->insert([ 'id' => '6', 'name' => "Accolade", ]);
        DB::table('distributors')->insert([ 'id' => '7', 'name' => "Acclaim Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '8', 'name' => "Active Gaming Media AGM", ]);
        DB::table('distributors')->insert([ 'id' => '9', 'name' => "Activision", ]);
        DB::table('distributors')->insert([ 'id' => '10', 'name' => "Activision Blizzard", ]);
        DB::table('distributors')->insert([ 'id' => '11', 'name' => "Agetec", ]);
        DB::table('distributors')->insert([ 'id' => '12', 'name' => "Akella", ]);
        DB::table('distributors')->insert([ 'id' => '13', 'name' => "Alten8", ]);
        DB::table('distributors')->insert([ 'id' => '14', 'name' => "Anuman", ]);
        DB::table('distributors')->insert([ 'id' => '15', 'name' => "Apogee Software", ]);
        DB::table('distributors')->insert([ 'id' => '16', 'name' => "Arc System Works", ]);
        DB::table('distributors')->insert([ 'id' => '17', 'name' => "Asmik Corporation of America", ]);
        DB::table('distributors')->insert([ 'id' => '18', 'name' => "Aspyr Media", ]);
        DB::table('distributors')->insert([ 'id' => '19', 'name' => "Atari, Inc", ]);
        DB::table('distributors')->insert([ 'id' => '20', 'name' => "Atari, SA", ]);
        DB::table('distributors')->insert([ 'id' => '21', 'name' => "AQ Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '22', 'name' => "Atlus", ]);
        DB::table('distributors')->insert([ 'id' => '23', 'name' => "Autumn Games", ]);
        DB::table('distributors')->insert([ 'id' => '24', 'name' => "Aventurine SA", ]);
        DB::table('distributors')->insert([ 'id' => '25', 'name' => "Bandai Games Bandai Games", ]);
        DB::table('distributors')->insert([ 'id' => '26', 'name' => "Bandai Namco", ]);
        DB::table('distributors')->insert([ 'id' => '27', 'name' => "Banpresto", ]);
        DB::table('distributors')->insert([ 'id' => '28', 'name' => "Bethesda Softworks", ]);
        DB::table('distributors')->insert([ 'id' => '29', 'name' => "Big Fish Games", ]);
        DB::table('distributors')->insert([ 'id' => '30', 'name' => "Bigben Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '31', 'name' => "Blue Byte Software", ]);
        DB::table('distributors')->insert([ 'id' => '32', 'name' => "Bullet-Proof Software", ]);
        DB::table('distributors')->insert([ 'id' => '33', 'name' => "Brøderbund", ]);
        DB::table('distributors')->insert([ 'id' => '34', 'name' => "Black Shell Games", ]);
        DB::table('distributors')->insert([ 'id' => '35', 'name' => "Blizzard Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '36', 'name' => "Bohemia Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '37', 'name' => "Bug-Byte", ]);
        DB::table('distributors')->insert([ 'id' => '38', 'name' => "Buka Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '39', 'name' => "Bungie", ]);
        DB::table('distributors')->insert([ 'id' => '40', 'name' => "Camerica", ]);
        DB::table('distributors')->insert([ 'id' => '41', 'name' => "Capcom", ]);
        DB::table('distributors')->insert([ 'id' => '42', 'name' => "CD Projekt RED", ]);
        DB::table('distributors')->insert([ 'id' => '43', 'name' => "cdv Software Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '44', 'name' => "CI Games", ]);
        DB::table('distributors')->insert([ 'id' => '45', 'name' => "Codemasters", ]);
        DB::table('distributors')->insert([ 'id' => '46', 'name' => "Coleco", ]);
        DB::table('distributors')->insert([ 'id' => '47', 'name' => "Color Dreams", ]);
        DB::table('distributors')->insert([ 'id' => '48', 'name' => "Conspiracy Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '49', 'name' => "Crave Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '50', 'name' => "Culture Brain", ]);
        DB::table('distributors')->insert([ 'id' => '51', 'name' => "Crystal Dynamics", ]);
        DB::table('distributors')->insert([ 'id' => '52', 'name' => "Cyberdreams", ]);
        DB::table('distributors')->insert([ 'id' => '53', 'name' => "D3 Publisher", ]);
        DB::table('distributors')->insert([ 'id' => '54', 'name' => "Daybreak Game Company", ]);
        DB::table('distributors')->insert([ 'id' => '55', 'name' => "Data East", ]);
        DB::table('distributors')->insert([ 'id' => '56', 'name' => "Deep Silver", ]);
        DB::table('distributors')->insert([ 'id' => '57', 'name' => "Destineer", ]);
        DB::table('distributors')->insert([ 'id' => '58', 'name' => "Disney Interactive Studios", ]);
        DB::table('distributors')->insert([ 'id' => '59', 'name' => "DreamCatcher Games", ]);
        DB::table('distributors')->insert([ 'id' => '60', 'name' => "Dtp entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '61', 'name' => "Eidos Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '62', 'name' => "Electronic Arts", ]);
        DB::table('distributors')->insert([ 'id' => '63', 'name' => "Enix", ]);
        DB::table('distributors')->insert([ 'id' => '64', 'name' => "Epyx", ]);
        DB::table('distributors')->insert([ 'id' => '65', 'name' => "FASA", ]);
        DB::table('distributors')->insert([ 'id' => '66', 'name' => "First Star Software", ]);
        DB::table('distributors')->insert([ 'id' => '67', 'name' => "Feral Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '68', 'name' => "Fox Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '69', 'name' => "Fresh Games", ]);
        DB::table('distributors')->insert([ 'id' => '70', 'name' => "Fujisankei Communications International", ]);
        DB::table('distributors')->insert([ 'id' => '71', 'name' => "Funcom", ]);
        DB::table('distributors')->insert([ 'id' => '72', 'name' => "Gamecock", ]);
        DB::table('distributors')->insert([ 'id' => '73', 'name' => "GAMÉRICA", ]);
        DB::table('distributors')->insert([ 'id' => '74', 'name' => "Ghostlight", ]);
        DB::table('distributors')->insert([ 'id' => '75', 'name' => "Global Star Software Global Star Software", ]);
        DB::table('distributors')->insert([ 'id' => '76', 'name' => "GOD Games", ]);
        DB::table('distributors')->insert([ 'id' => '77', 'name' => "GOG Ltd", ]);
        DB::table('distributors')->insert([ 'id' => '78', 'name' => "Gogii Games", ]);
        DB::table('distributors')->insert([ 'id' => '79', 'name' => "Got Game Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '80', 'name' => "Gravity", ]);
        DB::table('distributors')->insert([ 'id' => '81', 'name' => "Gremlin Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '82', 'name' => "GSC World Publishing", ]);
        DB::table('distributors')->insert([ 'id' => '83', 'name' => "GT Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '84', 'name' => "Gust Corporation", ]);
        DB::table('distributors')->insert([ 'id' => '85', 'name' => "Hasbro Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '86', 'name' => "Her Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '87', 'name' => "Hi Tech Expressions", ]);
        DB::table('distributors')->insert([ 'id' => '88', 'name' => "Hudson Soft", ]);
        DB::table('distributors')->insert([ 'id' => '89', 'name' => "Iceberg Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '90', 'name' => "Ignition Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '91', 'name' => "Imagic", ]);
        DB::table('distributors')->insert([ 'id' => '92', 'name' => "indiePub Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '93', 'name' => "Infocom", ]);
        DB::table('distributors')->insert([ 'id' => '94', 'name' => "Infogrames", ]);
        DB::table('distributors')->insert([ 'id' => '95', 'name' => "Inscape", ]);
        DB::table('distributors')->insert([ 'id' => '96', 'name' => "Interceptor Micros", ]);
        DB::table('distributors')->insert([ 'id' => '97', 'name' => "Interplay Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '98', 'name' => "inXile Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '99', 'name' => "Irem", ]);
        DB::table('distributors')->insert([ 'id' => '100', 'name' => "Jaleco", ]);
        DB::table('distributors')->insert([ 'id' => '101', 'name' => "JoWooD Productions", ]);
        DB::table('distributors')->insert([ 'id' => '102', 'name' => "K2 Network (Gamersfirst)", ]);
        DB::table('distributors')->insert([ 'id' => '103', 'name' => "Kaneko", ]);
        DB::table('distributors')->insert([ 'id' => '104', 'name' => "Kemco", ]);
        DB::table('distributors')->insert([ 'id' => '105', 'name' => "Koch Media", ]);
        DB::table('distributors')->insert([ 'id' => '106', 'name' => "Koei", ]);
        DB::table('distributors')->insert([ 'id' => '107', 'name' => "Koei Tecmo", ]);
        DB::table('distributors')->insert([ 'id' => '108', 'name' => "Konami", ]);
        DB::table('distributors')->insert([ 'id' => '109', 'name' => "Legacy Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '110', 'name' => "Linux Game Publishing", ]);
        DB::table('distributors')->insert([ 'id' => '111', 'name' => "LJN", ]);
        DB::table('distributors')->insert([ 'id' => '112', 'name' => "Loki Software", ]);
        DB::table('distributors')->insert([ 'id' => '113', 'name' => "LucasArts", ]);
        DB::table('distributors')->insert([ 'id' => '114', 'name' => "Marvelous AQL", ]);
        DB::table('distributors')->insert([ 'id' => '115', 'name' => "Mastiff", ]);
        DB::table('distributors')->insert([ 'id' => '116', 'name' => "Matrix Games", ]);
        DB::table('distributors')->insert([ 'id' => '117', 'name' => "Mattel Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '118', 'name' => "Maximum Games", ]);
        DB::table('distributors')->insert([ 'id' => '119', 'name' => "Maxis", ]);
        DB::table('distributors')->insert([ 'id' => '120', 'name' => "Meldac", ]);
        DB::table('distributors')->insert([ 'id' => '121', 'name' => "Microïds", ]);
        DB::table('distributors')->insert([ 'id' => '122', 'name' => "MicroProse", ]);
        DB::table('distributors')->insert([ 'id' => '123', 'name' => "Microsoft Game Studios", ]);
        DB::table('distributors')->insert([ 'id' => '124', 'name' => "Midway Games", ]);
        DB::table('distributors')->insert([ 'id' => '125', 'name' => "Mindscape", ]);
        DB::table('distributors')->insert([ 'id' => '126', 'name' => "MTV Games", ]);
        DB::table('distributors')->insert([ 'id' => '127', 'name' => "Muse Software", ]);
        DB::table('distributors')->insert([ 'id' => '128', 'name' => "Namco", ]);
        DB::table('distributors')->insert([ 'id' => '129', 'name' => "NCsoft", ]);
        DB::table('distributors')->insert([ 'id' => '130', 'name' => "Netdragon", ]);
        DB::table('distributors')->insert([ 'id' => '131', 'name' => "Netease", ]);
        DB::table('distributors')->insert([ 'id' => '132', 'name' => "New World Computing", ]);
        DB::table('distributors')->insert([ 'id' => '133', 'name' => "Nexon", ]);
        DB::table('distributors')->insert([ 'id' => '134', 'name' => "Nintendo", ]);
        DB::table('distributors')->insert([ 'id' => '135', 'name' => "Nippon Ichi Software", ]);
        DB::table('distributors')->insert([ 'id' => '136', 'name' => "Nihon Bussan", ]);
        DB::table('distributors')->insert([ 'id' => '137', 'name' => "Nokia", ]);
        DB::table('distributors')->insert([ 'id' => '138', 'name' => "Nordic Games GmbH", ]);
        DB::table('distributors')->insert([ 'id' => '139', 'name' => "Nova Games", ]);
        DB::table('distributors')->insert([ 'id' => '140', 'name' => "O3 Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '141', 'name' => "Ocean Software", ]);
        DB::table('distributors')->insert([ 'id' => '142', 'name' => "Origin Systems", ]);
        DB::table('distributors')->insert([ 'id' => '143', 'name' => "Oxygen Games", ]);
        DB::table('distributors')->insert([ 'id' => '144', 'name' => "Panesian Taiwan", ]);
        DB::table('distributors')->insert([ 'id' => '145', 'name' => "Paradox Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '146', 'name' => "Penguin Software", ]);
        DB::table('distributors')->insert([ 'id' => '147', 'name' => "Perfect World", ]);
        DB::table('distributors')->insert([ 'id' => '148', 'name' => "Petroglyph Games", ]);
        DB::table('distributors')->insert([ 'id' => '149', 'name' => "PlayFirst", ]);
        DB::table('distributors')->insert([ 'id' => '150', 'name' => "Playlogic Entertainment, Inc.", ]);
        DB::table('distributors')->insert([ 'id' => '151', 'name' => "Playmates Toys", ]);
        DB::table('distributors')->insert([ 'id' => '152', 'name' => "PopCap Games", ]);
        DB::table('distributors')->insert([ 'id' => '153', 'name' => "Programma International", ]);
        DB::table('distributors')->insert([ 'id' => '154', 'name' => "Psygnosis", ]);
        DB::table('distributors')->insert([ 'id' => '155', 'name' => "R2Games", ]);
        DB::table('distributors')->insert([ 'id' => '156', 'name' => "Red Barrels", ]);
        DB::table('distributors')->insert([ 'id' => '157', 'name' => "Red Storm Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '158', 'name' => "Renovation Products", ]);
        DB::table('distributors')->insert([ 'id' => '159', 'name' => "Riot Games", ]);
        DB::table('distributors')->insert([ 'id' => '160', 'name' => "Rising Star Games", ]);
        DB::table('distributors')->insert([ 'id' => '161', 'name' => "Rockstar Games", ]);
        DB::table('distributors')->insert([ 'id' => '162', 'name' => "Rovio Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '163', 'name' => "Sammy Studios", ]);
        DB::table('distributors')->insert([ 'id' => '164', 'name' => "SCi Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '165', 'name' => "Sega", ]);
        DB::table('distributors')->insert([ 'id' => '166', 'name' => "SETA Corporation", ]);
        DB::table('distributors')->insert([ 'id' => '167', 'name' => "Shanda", ]);
        DB::table('distributors')->insert([ 'id' => '168', 'name' => "Shrapnel Games", ]);
        DB::table('distributors')->insert([ 'id' => '169', 'name' => "Sierra Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '170', 'name' => "Slitherine", ]);
        DB::table('distributors')->insert([ 'id' => '171', 'name' => "Mattel Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '172', 'name' => "SNK Playmore", ]);
        DB::table('distributors')->insert([ 'id' => '173', 'name' => "Sony Computer Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '174', 'name' => "Sony Pictures Digital", ]);
        DB::table('distributors')->insert([ 'id' => '175', 'name' => "SouthPeak Games", ]);
        DB::table('distributors')->insert([ 'id' => '176', 'name' => "Spectrum HoloByte", ]);
        DB::table('distributors')->insert([ 'id' => '177', 'name' => "Spil Games", ]);
        DB::table('distributors')->insert([ 'id' => '178', 'name' => "Square", ]);
        DB::table('distributors')->insert([ 'id' => '179', 'name' => "Square Electronic Arts", ]);
        DB::table('distributors')->insert([ 'id' => '180', 'name' => "Square Enix", ]);
        DB::table('distributors')->insert([ 'id' => '181', 'name' => "Stardock", ]);
        DB::table('distributors')->insert([ 'id' => '182', 'name' => "Strategic Simulations (SSI)", ]);
        DB::table('distributors')->insert([ 'id' => '183', 'name' => "Strategy First", ]);
        DB::table('distributors')->insert([ 'id' => '184', 'name' => "Success", ]);
        DB::table('distributors')->insert([ 'id' => '185', 'name' => "Sunsoft", ]);
        DB::table('distributors')->insert([ 'id' => '186', 'name' => "Taito", ]);
        DB::table('distributors')->insert([ 'id' => '187', 'name' => "Takara", ]);
        DB::table('distributors')->insert([ 'id' => '188', 'name' => "Takara Tomy", ]);
        DB::table('distributors')->insert([ 'id' => '189', 'name' => "Take-Two Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '190', 'name' => "TalonSoft", ]);
        DB::table('distributors')->insert([ 'id' => '191', 'name' => "Taxan", ]);
        DB::table('distributors')->insert([ 'id' => '192', 'name' => "Technos Japan", ]);
        DB::table('distributors')->insert([ 'id' => '193', 'name' => "TecMagik", ]);
        DB::table('distributors')->insert([ 'id' => '194', 'name' => "Tecmo", ]);
        DB::table('distributors')->insert([ 'id' => '195', 'name' => "Telltale Games", ]);
        DB::table('distributors')->insert([ 'id' => '196', 'name' => "Tencent", ]);
        DB::table('distributors')->insert([ 'id' => '197', 'name' => "The9", ]);
        DB::table('distributors')->insert([ 'id' => '198', 'name' => "The Learning Company", ]);
        DB::table('distributors')->insert([ 'id' => '199', 'name' => "THQ", ]);
        DB::table('distributors')->insert([ 'id' => '200', 'name' => "Titus Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '201', 'name' => "Tomy", ]);
        DB::table('distributors')->insert([ 'id' => '202', 'name' => "TopWare Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '203', 'name' => "Tradewest", ]);
        DB::table('distributors')->insert([ 'id' => '204', 'name' => "Triffix Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '205', 'name' => "TT Games", ]);
        DB::table('distributors')->insert([ 'id' => '206', 'name' => "Ubisoft", ]);
        DB::table('distributors')->insert([ 'id' => '207', 'name' => "Ultra Games", ]);
        DB::table('distributors')->insert([ 'id' => '208', 'name' => "U.S. Gold", ]);
        DB::table('distributors')->insert([ 'id' => '209', 'name' => "Valve Corporation", ]);
        DB::table('distributors')->insert([ 'id' => '210', 'name' => "Vic Tokai", ]);
        DB::table('distributors')->insert([ 'id' => '211', 'name' => "Vivendi Games", ]);
        DB::table('distributors')->insert([ 'id' => '212', 'name' => "VoxelStorm", ]);
        DB::table('distributors')->insert([ 'id' => '213', 'name' => "Wargaming.net", ]);
        DB::table('distributors')->insert([ 'id' => '214', 'name' => "Warner Bros. Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '215', 'name' => "Webzen", ]);
        DB::table('distributors')->insert([ 'id' => '216', 'name' => "Wisdom Tree", ]);
        DB::table('distributors')->insert([ 'id' => '217', 'name' => "Working Designs", ]);
        DB::table('distributors')->insert([ 'id' => '218', 'name' => "Xicat Interactive", ]);
        DB::table('distributors')->insert([ 'id' => '219', 'name' => "XSEED Games", ]);
        DB::table('distributors')->insert([ 'id' => '220', 'name' => "XS Games", ]);
        DB::table('distributors')->insert([ 'id' => '221', 'name' => "Yuisy", ]);
        DB::table('distributors')->insert([ 'id' => '222', 'name' => "ZeniMax Media", ]);
        DB::table('distributors')->insert([ 'id' => '223', 'name' => "Zuxxez Entertainment", ]);
        DB::table('distributors')->insert([ 'id' => '224', 'name' => "Zushi Games", ]);
        DB::table('distributors')->insert([ 'id' => '225', 'name' => "Zynga", ]);
    }
}
