<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistribuidoresSeeder extends Seeder
{
    /**
     * Comienza el volcado de datos en la tabla distribuidores
     */
    public function run()
    {
        DB::table('distribuidores')->insert([ 'id' => '1', 'nombre' => "1C Company", ]);
        DB::table('distribuidores')->insert([ 'id' => '2', 'nombre' => "2K Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '3', 'nombre' => "3D Realms", ]);
        DB::table('distribuidores')->insert([ 'id' => '4', 'nombre' => "The 3DO Company", ]);
        DB::table('distribuidores')->insert([ 'id' => '5', 'nombre' => "505 Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '6', 'nombre' => "Accolade", ]);
        DB::table('distribuidores')->insert([ 'id' => '7', 'nombre' => "Acclaim Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '8', 'nombre' => "Active Gaming Media AGM", ]);
        DB::table('distribuidores')->insert([ 'id' => '9', 'nombre' => "Activision", ]);
        DB::table('distribuidores')->insert([ 'id' => '10', 'nombre' => "Activision Blizzard", ]);
        DB::table('distribuidores')->insert([ 'id' => '11', 'nombre' => "Agetec", ]);
        DB::table('distribuidores')->insert([ 'id' => '12', 'nombre' => "Akella", ]);
        DB::table('distribuidores')->insert([ 'id' => '13', 'nombre' => "Alten8", ]);
        DB::table('distribuidores')->insert([ 'id' => '14', 'nombre' => "Anuman", ]);
        DB::table('distribuidores')->insert([ 'id' => '15', 'nombre' => "Apogee Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '16', 'nombre' => "Arc System Works", ]);
        DB::table('distribuidores')->insert([ 'id' => '17', 'nombre' => "Asmik Corporation of America", ]);
        DB::table('distribuidores')->insert([ 'id' => '18', 'nombre' => "Aspyr Media", ]);
        DB::table('distribuidores')->insert([ 'id' => '19', 'nombre' => "Atari, Inc", ]);
        DB::table('distribuidores')->insert([ 'id' => '20', 'nombre' => "Atari, SA", ]);
        DB::table('distribuidores')->insert([ 'id' => '21', 'nombre' => "AQ Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '22', 'nombre' => "Atlus", ]);
        DB::table('distribuidores')->insert([ 'id' => '23', 'nombre' => "Autumn Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '24', 'nombre' => "Aventurine SA", ]);
        DB::table('distribuidores')->insert([ 'id' => '25', 'nombre' => "Bandai Games Bandai Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '26', 'nombre' => "Bandai Namco", ]);
        DB::table('distribuidores')->insert([ 'id' => '27', 'nombre' => "Banpresto", ]);
        DB::table('distribuidores')->insert([ 'id' => '28', 'nombre' => "Bethesda Softworks", ]);
        DB::table('distribuidores')->insert([ 'id' => '29', 'nombre' => "Big Fish Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '30', 'nombre' => "Bigben Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '31', 'nombre' => "Blue Byte Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '32', 'nombre' => "Bullet-Proof Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '33', 'nombre' => "Brøderbund", ]);
        DB::table('distribuidores')->insert([ 'id' => '34', 'nombre' => "Black Shell Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '35', 'nombre' => "Blizzard Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '36', 'nombre' => "Bohemia Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '37', 'nombre' => "Bug-Byte", ]);
        DB::table('distribuidores')->insert([ 'id' => '38', 'nombre' => "Buka Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '39', 'nombre' => "Bungie", ]);
        DB::table('distribuidores')->insert([ 'id' => '40', 'nombre' => "Camerica", ]);
        DB::table('distribuidores')->insert([ 'id' => '41', 'nombre' => "Capcom", ]);
        DB::table('distribuidores')->insert([ 'id' => '42', 'nombre' => "CD Projekt RED", ]);
        DB::table('distribuidores')->insert([ 'id' => '43', 'nombre' => "cdv Software Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '44', 'nombre' => "CI Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '45', 'nombre' => "Codemasters", ]);
        DB::table('distribuidores')->insert([ 'id' => '46', 'nombre' => "Coleco", ]);
        DB::table('distribuidores')->insert([ 'id' => '47', 'nombre' => "Color Dreams", ]);
        DB::table('distribuidores')->insert([ 'id' => '48', 'nombre' => "Conspiracy Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '49', 'nombre' => "Crave Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '50', 'nombre' => "Culture Brain", ]);
        DB::table('distribuidores')->insert([ 'id' => '51', 'nombre' => "Crystal Dynamics", ]);
        DB::table('distribuidores')->insert([ 'id' => '52', 'nombre' => "Cyberdreams", ]);
        DB::table('distribuidores')->insert([ 'id' => '53', 'nombre' => "D3 Publisher", ]);
        DB::table('distribuidores')->insert([ 'id' => '54', 'nombre' => "Daybreak Game Company", ]);
        DB::table('distribuidores')->insert([ 'id' => '55', 'nombre' => "Data East", ]);
        DB::table('distribuidores')->insert([ 'id' => '56', 'nombre' => "Deep Silver", ]);
        DB::table('distribuidores')->insert([ 'id' => '57', 'nombre' => "Destineer", ]);
        DB::table('distribuidores')->insert([ 'id' => '58', 'nombre' => "Disney Interactive Studios", ]);
        DB::table('distribuidores')->insert([ 'id' => '59', 'nombre' => "DreamCatcher Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '60', 'nombre' => "Dtp entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '61', 'nombre' => "Eidos Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '62', 'nombre' => "Electronic Arts", ]);
        DB::table('distribuidores')->insert([ 'id' => '63', 'nombre' => "Enix", ]);
        DB::table('distribuidores')->insert([ 'id' => '64', 'nombre' => "Epyx", ]);
        DB::table('distribuidores')->insert([ 'id' => '65', 'nombre' => "FASA", ]);
        DB::table('distribuidores')->insert([ 'id' => '66', 'nombre' => "First Star Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '67', 'nombre' => "Feral Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '68', 'nombre' => "Fox Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '69', 'nombre' => "Fresh Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '70', 'nombre' => "Fujisankei Communications International", ]);
        DB::table('distribuidores')->insert([ 'id' => '71', 'nombre' => "Funcom", ]);
        DB::table('distribuidores')->insert([ 'id' => '72', 'nombre' => "Gamecock", ]);
        DB::table('distribuidores')->insert([ 'id' => '73', 'nombre' => "GAMÉRICA", ]);
        DB::table('distribuidores')->insert([ 'id' => '74', 'nombre' => "Ghostlight", ]);
        DB::table('distribuidores')->insert([ 'id' => '75', 'nombre' => "Global Star Software Global Star Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '76', 'nombre' => "GOD Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '77', 'nombre' => "GOG Ltd", ]);
        DB::table('distribuidores')->insert([ 'id' => '78', 'nombre' => "Gogii Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '79', 'nombre' => "Got Game Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '80', 'nombre' => "Gravity", ]);
        DB::table('distribuidores')->insert([ 'id' => '81', 'nombre' => "Gremlin Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '82', 'nombre' => "GSC World Publishing", ]);
        DB::table('distribuidores')->insert([ 'id' => '83', 'nombre' => "GT Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '84', 'nombre' => "Gust Corporation", ]);
        DB::table('distribuidores')->insert([ 'id' => '85', 'nombre' => "Hasbro Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '86', 'nombre' => "Her Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '87', 'nombre' => "Hi Tech Expressions", ]);
        DB::table('distribuidores')->insert([ 'id' => '88', 'nombre' => "Hudson Soft", ]);
        DB::table('distribuidores')->insert([ 'id' => '89', 'nombre' => "Iceberg Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '90', 'nombre' => "Ignition Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '91', 'nombre' => "Imagic", ]);
        DB::table('distribuidores')->insert([ 'id' => '92', 'nombre' => "indiePub Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '93', 'nombre' => "Infocom", ]);
        DB::table('distribuidores')->insert([ 'id' => '94', 'nombre' => "Infogrames", ]);
        DB::table('distribuidores')->insert([ 'id' => '95', 'nombre' => "Inscape", ]);
        DB::table('distribuidores')->insert([ 'id' => '96', 'nombre' => "Interceptor Micros", ]);
        DB::table('distribuidores')->insert([ 'id' => '97', 'nombre' => "Interplay Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '98', 'nombre' => "inXile Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '99', 'nombre' => "Irem", ]);
        DB::table('distribuidores')->insert([ 'id' => '100', 'nombre' => "Jaleco", ]);
        DB::table('distribuidores')->insert([ 'id' => '101', 'nombre' => "JoWooD Productions", ]);
        DB::table('distribuidores')->insert([ 'id' => '102', 'nombre' => "K2 Network (Gamersfirst)", ]);
        DB::table('distribuidores')->insert([ 'id' => '103', 'nombre' => "Kaneko", ]);
        DB::table('distribuidores')->insert([ 'id' => '104', 'nombre' => "Kemco", ]);
        DB::table('distribuidores')->insert([ 'id' => '105', 'nombre' => "Koch Media", ]);
        DB::table('distribuidores')->insert([ 'id' => '106', 'nombre' => "Koei", ]);
        DB::table('distribuidores')->insert([ 'id' => '107', 'nombre' => "Koei Tecmo", ]);
        DB::table('distribuidores')->insert([ 'id' => '108', 'nombre' => "Konami", ]);
        DB::table('distribuidores')->insert([ 'id' => '109', 'nombre' => "Legacy Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '110', 'nombre' => "Linux Game Publishing", ]);
        DB::table('distribuidores')->insert([ 'id' => '111', 'nombre' => "LJN", ]);
        DB::table('distribuidores')->insert([ 'id' => '112', 'nombre' => "Loki Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '113', 'nombre' => "LucasArts", ]);
        DB::table('distribuidores')->insert([ 'id' => '114', 'nombre' => "Marvelous AQL", ]);
        DB::table('distribuidores')->insert([ 'id' => '115', 'nombre' => "Mastiff", ]);
        DB::table('distribuidores')->insert([ 'id' => '116', 'nombre' => "Matrix Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '117', 'nombre' => "Mattel Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '118', 'nombre' => "Maximum Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '119', 'nombre' => "Maxis", ]);
        DB::table('distribuidores')->insert([ 'id' => '120', 'nombre' => "Meldac", ]);
        DB::table('distribuidores')->insert([ 'id' => '121', 'nombre' => "Microïds", ]);
        DB::table('distribuidores')->insert([ 'id' => '122', 'nombre' => "MicroProse", ]);
        DB::table('distribuidores')->insert([ 'id' => '123', 'nombre' => "Microsoft Game Studios", ]);
        DB::table('distribuidores')->insert([ 'id' => '124', 'nombre' => "Midway Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '125', 'nombre' => "Mindscape", ]);
        DB::table('distribuidores')->insert([ 'id' => '126', 'nombre' => "MTV Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '127', 'nombre' => "Muse Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '128', 'nombre' => "Namco", ]);
        DB::table('distribuidores')->insert([ 'id' => '129', 'nombre' => "NCsoft", ]);
        DB::table('distribuidores')->insert([ 'id' => '130', 'nombre' => "Netdragon", ]);
        DB::table('distribuidores')->insert([ 'id' => '131', 'nombre' => "Netease", ]);
        DB::table('distribuidores')->insert([ 'id' => '132', 'nombre' => "New World Computing", ]);
        DB::table('distribuidores')->insert([ 'id' => '133', 'nombre' => "Nexon", ]);
        DB::table('distribuidores')->insert([ 'id' => '134', 'nombre' => "Nintendo", ]);
        DB::table('distribuidores')->insert([ 'id' => '135', 'nombre' => "Nippon Ichi Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '136', 'nombre' => "Nihon Bussan", ]);
        DB::table('distribuidores')->insert([ 'id' => '137', 'nombre' => "Nokia", ]);
        DB::table('distribuidores')->insert([ 'id' => '138', 'nombre' => "Nordic Games GmbH", ]);
        DB::table('distribuidores')->insert([ 'id' => '139', 'nombre' => "Nova Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '140', 'nombre' => "O3 Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '141', 'nombre' => "Ocean Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '142', 'nombre' => "Origin Systems", ]);
        DB::table('distribuidores')->insert([ 'id' => '143', 'nombre' => "Oxygen Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '144', 'nombre' => "Panesian Taiwan", ]);
        DB::table('distribuidores')->insert([ 'id' => '145', 'nombre' => "Paradox Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '146', 'nombre' => "Penguin Software", ]);
        DB::table('distribuidores')->insert([ 'id' => '147', 'nombre' => "Perfect World", ]);
        DB::table('distribuidores')->insert([ 'id' => '148', 'nombre' => "Petroglyph Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '149', 'nombre' => "PlayFirst", ]);
        DB::table('distribuidores')->insert([ 'id' => '150', 'nombre' => "Playlogic Entertainment, Inc.", ]);
        DB::table('distribuidores')->insert([ 'id' => '151', 'nombre' => "Playmates Toys", ]);
        DB::table('distribuidores')->insert([ 'id' => '152', 'nombre' => "PopCap Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '153', 'nombre' => "Programma International", ]);
        DB::table('distribuidores')->insert([ 'id' => '154', 'nombre' => "Psygnosis", ]);
        DB::table('distribuidores')->insert([ 'id' => '155', 'nombre' => "R2Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '156', 'nombre' => "Red Barrels", ]);
        DB::table('distribuidores')->insert([ 'id' => '157', 'nombre' => "Red Storm Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '158', 'nombre' => "Renovation Products", ]);
        DB::table('distribuidores')->insert([ 'id' => '159', 'nombre' => "Riot Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '160', 'nombre' => "Rising Star Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '161', 'nombre' => "Rockstar Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '162', 'nombre' => "Rovio Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '163', 'nombre' => "Sammy Studios", ]);
        DB::table('distribuidores')->insert([ 'id' => '164', 'nombre' => "SCi Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '165', 'nombre' => "Sega", ]);
        DB::table('distribuidores')->insert([ 'id' => '166', 'nombre' => "SETA Corporation", ]);
        DB::table('distribuidores')->insert([ 'id' => '167', 'nombre' => "Shanda", ]);
        DB::table('distribuidores')->insert([ 'id' => '168', 'nombre' => "Shrapnel Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '169', 'nombre' => "Sierra Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '170', 'nombre' => "Slitherine", ]);
        DB::table('distribuidores')->insert([ 'id' => '171', 'nombre' => "Mattel Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '172', 'nombre' => "SNK Playmore", ]);
        DB::table('distribuidores')->insert([ 'id' => '173', 'nombre' => "Sony Computer Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '174', 'nombre' => "Sony Pictures Digital", ]);
        DB::table('distribuidores')->insert([ 'id' => '175', 'nombre' => "SouthPeak Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '176', 'nombre' => "Spectrum HoloByte", ]);
        DB::table('distribuidores')->insert([ 'id' => '177', 'nombre' => "Spil Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '178', 'nombre' => "Square", ]);
        DB::table('distribuidores')->insert([ 'id' => '179', 'nombre' => "Square Electronic Arts", ]);
        DB::table('distribuidores')->insert([ 'id' => '180', 'nombre' => "Square Enix", ]);
        DB::table('distribuidores')->insert([ 'id' => '181', 'nombre' => "Stardock", ]);
        DB::table('distribuidores')->insert([ 'id' => '182', 'nombre' => "Strategic Simulations (SSI)", ]);
        DB::table('distribuidores')->insert([ 'id' => '183', 'nombre' => "Strategy First", ]);
        DB::table('distribuidores')->insert([ 'id' => '184', 'nombre' => "Success", ]);
        DB::table('distribuidores')->insert([ 'id' => '185', 'nombre' => "Sunsoft", ]);
        DB::table('distribuidores')->insert([ 'id' => '186', 'nombre' => "Taito", ]);
        DB::table('distribuidores')->insert([ 'id' => '187', 'nombre' => "Takara", ]);
        DB::table('distribuidores')->insert([ 'id' => '188', 'nombre' => "Takara Tomy", ]);
        DB::table('distribuidores')->insert([ 'id' => '189', 'nombre' => "Take-Two Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '190', 'nombre' => "TalonSoft", ]);
        DB::table('distribuidores')->insert([ 'id' => '191', 'nombre' => "Taxan", ]);
        DB::table('distribuidores')->insert([ 'id' => '192', 'nombre' => "Technos Japan", ]);
        DB::table('distribuidores')->insert([ 'id' => '193', 'nombre' => "TecMagik", ]);
        DB::table('distribuidores')->insert([ 'id' => '194', 'nombre' => "Tecmo", ]);
        DB::table('distribuidores')->insert([ 'id' => '195', 'nombre' => "Telltale Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '196', 'nombre' => "Tencent", ]);
        DB::table('distribuidores')->insert([ 'id' => '197', 'nombre' => "The9", ]);
        DB::table('distribuidores')->insert([ 'id' => '198', 'nombre' => "The Learning Company", ]);
        DB::table('distribuidores')->insert([ 'id' => '199', 'nombre' => "THQ", ]);
        DB::table('distribuidores')->insert([ 'id' => '200', 'nombre' => "Titus Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '201', 'nombre' => "Tomy", ]);
        DB::table('distribuidores')->insert([ 'id' => '202', 'nombre' => "TopWare Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '203', 'nombre' => "Tradewest", ]);
        DB::table('distribuidores')->insert([ 'id' => '204', 'nombre' => "Triffix Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '205', 'nombre' => "TT Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '206', 'nombre' => "Ubisoft", ]);
        DB::table('distribuidores')->insert([ 'id' => '207', 'nombre' => "Ultra Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '208', 'nombre' => "U.S. Gold", ]);
        DB::table('distribuidores')->insert([ 'id' => '209', 'nombre' => "Valve Corporation", ]);
        DB::table('distribuidores')->insert([ 'id' => '210', 'nombre' => "Vic Tokai", ]);
        DB::table('distribuidores')->insert([ 'id' => '211', 'nombre' => "Vivendi Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '212', 'nombre' => "VoxelStorm", ]);
        DB::table('distribuidores')->insert([ 'id' => '213', 'nombre' => "Wargaming.net", ]);
        DB::table('distribuidores')->insert([ 'id' => '214', 'nombre' => "Warner Bros. Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '215', 'nombre' => "Webzen", ]);
        DB::table('distribuidores')->insert([ 'id' => '216', 'nombre' => "Wisdom Tree", ]);
        DB::table('distribuidores')->insert([ 'id' => '217', 'nombre' => "Working Designs", ]);
        DB::table('distribuidores')->insert([ 'id' => '218', 'nombre' => "Xicat Interactive", ]);
        DB::table('distribuidores')->insert([ 'id' => '219', 'nombre' => "XSEED Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '220', 'nombre' => "XS Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '221', 'nombre' => "Yuisy", ]);
        DB::table('distribuidores')->insert([ 'id' => '222', 'nombre' => "ZeniMax Media", ]);
        DB::table('distribuidores')->insert([ 'id' => '223', 'nombre' => "Zuxxez Entertainment", ]);
        DB::table('distribuidores')->insert([ 'id' => '224', 'nombre' => "Zushi Games", ]);
        DB::table('distribuidores')->insert([ 'id' => '225', 'nombre' => "Zynga", ]);
    }
}
