<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Comienza el volcado de datos en la tabla paises
     */
    public function run()
    {
        DB::table('paises')->insert(['cod_pais' => 'AF', 'pais' => 'Afganistán',]);
        DB::table('paises')->insert(['cod_pais' => 'AL', 'pais' => 'Albania',]);
        DB::table('paises')->insert(['cod_pais' => 'DE', 'pais' => 'Alemania',]);
        DB::table('paises')->insert(['cod_pais' => 'AD', 'pais' => 'Andorra',]);
        DB::table('paises')->insert(['cod_pais' => 'AO', 'pais' => 'Angola',]);
        DB::table('paises')->insert(['cod_pais' => 'AI', 'pais' => 'Anguilla',]);
        DB::table('paises')->insert(['cod_pais' => 'AQ', 'pais' => 'Antártida',]);
        DB::table('paises')->insert(['cod_pais' => 'AG', 'pais' => 'Antigua y Barbuda',]);
        DB::table('paises')->insert(['cod_pais' => 'AN', 'pais' => 'Antillas Holandesas',]);
        DB::table('paises')->insert(['cod_pais' => 'SA', 'pais' => 'Arabia Saudí',]);
        DB::table('paises')->insert(['cod_pais' => 'DZ', 'pais' => 'Argelia',]);
        DB::table('paises')->insert(['cod_pais' => 'AR', 'pais' => 'Argentina',]);
        DB::table('paises')->insert(['cod_pais' => 'AM', 'pais' => 'Armenia',]);
        DB::table('paises')->insert(['cod_pais' => 'AW', 'pais' => 'Aruba',]);
        DB::table('paises')->insert(['cod_pais' => 'AU', 'pais' => 'Australia',]);
        DB::table('paises')->insert(['cod_pais' => 'AT', 'pais' => 'Austria',]);
        DB::table('paises')->insert(['cod_pais' => 'AZ', 'pais' => 'Azerbaiyán',]);
        DB::table('paises')->insert(['cod_pais' => 'BS', 'pais' => 'Bahamas',]);
        DB::table('paises')->insert(['cod_pais' => 'BH', 'pais' => 'Bahrein',]);
        DB::table('paises')->insert(['cod_pais' => 'BD', 'pais' => 'Bangladesh',]);
        DB::table('paises')->insert(['cod_pais' => 'BB', 'pais' => 'Barbados',]);
        DB::table('paises')->insert(['cod_pais' => 'BE', 'pais' => 'Bélgica',]);
        DB::table('paises')->insert(['cod_pais' => 'BZ', 'pais' => 'Belice',]);
        DB::table('paises')->insert(['cod_pais' => 'BJ', 'pais' => 'Benin',]);
        DB::table('paises')->insert(['cod_pais' => 'BM', 'pais' => 'Bermudas',]);
        DB::table('paises')->insert(['cod_pais' => 'BY', 'pais' => 'Bielorrusia',]);
        DB::table('paises')->insert(['cod_pais' => 'MM', 'pais' => 'Birmania',]);
        DB::table('paises')->insert(['cod_pais' => 'BO', 'pais' => 'Bolivia',]);
        DB::table('paises')->insert(['cod_pais' => 'BA', 'pais' => 'Bosnia y Herzegovina',]);
        DB::table('paises')->insert(['cod_pais' => 'BW', 'pais' => 'Botswana',]);
        DB::table('paises')->insert(['cod_pais' => 'BR', 'pais' => 'Brasil',]);
        DB::table('paises')->insert(['cod_pais' => 'BN', 'pais' => 'Brunei',]);
        DB::table('paises')->insert(['cod_pais' => 'BG', 'pais' => 'Bulgaria',]);
        DB::table('paises')->insert(['cod_pais' => 'BF', 'pais' => 'Burkina Faso',]);
        DB::table('paises')->insert(['cod_pais' => 'BI', 'pais' => 'Burundi',]);
        DB::table('paises')->insert(['cod_pais' => 'BT', 'pais' => 'Bután',]);
        DB::table('paises')->insert(['cod_pais' => 'CV', 'pais' => 'Cabo Verde',]);
        DB::table('paises')->insert(['cod_pais' => 'KH', 'pais' => 'Camboya',]);
        DB::table('paises')->insert(['cod_pais' => 'CM', 'pais' => 'Camerún',]);
        DB::table('paises')->insert(['cod_pais' => 'CA', 'pais' => 'Canadá',]);
        DB::table('paises')->insert(['cod_pais' => 'TD', 'pais' => 'Chad',]);
        DB::table('paises')->insert(['cod_pais' => 'CL', 'pais' => 'Chile',]);
        DB::table('paises')->insert(['cod_pais' => 'CN', 'pais' => 'China',]);
        DB::table('paises')->insert(['cod_pais' => 'CY', 'pais' => 'Chipre',]);
        DB::table('paises')->insert(['cod_pais' => 'VA', 'pais' => 'Ciudad del Vaticano (Santa Sede)',]);
        DB::table('paises')->insert(['cod_pais' => 'CO', 'pais' => 'Colombia',]);
        DB::table('paises')->insert(['cod_pais' => 'KM', 'pais' => 'Comores',]);
        DB::table('paises')->insert(['cod_pais' => 'CG', 'pais' => 'Congo',]);
        DB::table('paises')->insert(['cod_pais' => 'CD', 'pais' => 'Congo, República Democrática del',]);
        DB::table('paises')->insert(['cod_pais' => 'KR', 'pais' => 'Corea',]);
        DB::table('paises')->insert(['cod_pais' => 'KP', 'pais' => 'Corea del Norte',]);
        DB::table('paises')->insert(['cod_pais' => 'CI', 'pais' => 'Costa de Marfíl',]);
        DB::table('paises')->insert(['cod_pais' => 'CR', 'pais' => 'Costa Rica',]);
        DB::table('paises')->insert(['cod_pais' => 'HR', 'pais' => 'Croacia (Hrvatska)',]);
        DB::table('paises')->insert(['cod_pais' => 'CU', 'pais' => 'Cuba',]);
        DB::table('paises')->insert(['cod_pais' => 'DK', 'pais' => 'Dinamarca',]);
        DB::table('paises')->insert(['cod_pais' => 'DJ', 'pais' => 'Djibouti',]);
        DB::table('paises')->insert(['cod_pais' => 'DM', 'pais' => 'Dominica',]);
        DB::table('paises')->insert(['cod_pais' => 'EC', 'pais' => 'Ecuador',]);
        DB::table('paises')->insert(['cod_pais' => 'EG', 'pais' => 'Egipto',]);
        DB::table('paises')->insert(['cod_pais' => 'SV', 'pais' => 'El Salvador',]);
        DB::table('paises')->insert(['cod_pais' => 'AE', 'pais' => 'Emiratos Árabes Unidos',]);
        DB::table('paises')->insert(['cod_pais' => 'ER', 'pais' => 'Eritrea',]);
        DB::table('paises')->insert(['cod_pais' => 'SI', 'pais' => 'Eslovenia',]);
        DB::table('paises')->insert(['cod_pais' => 'ES', 'pais' => 'España',]);
        DB::table('paises')->insert(['cod_pais' => 'US', 'pais' => 'Estados Unidos',]);
        DB::table('paises')->insert(['cod_pais' => 'EE', 'pais' => 'Estonia',]);
        DB::table('paises')->insert(['cod_pais' => 'ET', 'pais' => 'Etiopía',]);
        DB::table('paises')->insert(['cod_pais' => 'FJ', 'pais' => 'Fiji',]);
        DB::table('paises')->insert(['cod_pais' => 'PH', 'pais' => 'Filipinas',]);
        DB::table('paises')->insert(['cod_pais' => 'FI', 'pais' => 'Finlandia',]);
        DB::table('paises')->insert(['cod_pais' => 'FR', 'pais' => 'Francia',]);
        DB::table('paises')->insert(['cod_pais' => 'GA', 'pais' => 'Gabón',]);
        DB::table('paises')->insert(['cod_pais' => 'GM', 'pais' => 'Gambia',]);
        DB::table('paises')->insert(['cod_pais' => 'GE', 'pais' => 'Georgia',]);
        DB::table('paises')->insert(['cod_pais' => 'GH', 'pais' => 'Ghana',]);
        DB::table('paises')->insert(['cod_pais' => 'GI', 'pais' => 'Gibraltar',]);
        DB::table('paises')->insert(['cod_pais' => 'GD', 'pais' => 'Granada',]);
        DB::table('paises')->insert(['cod_pais' => 'GR', 'pais' => 'Grecia',]);
        DB::table('paises')->insert(['cod_pais' => 'GL', 'pais' => 'Groenlandia',]);
        DB::table('paises')->insert(['cod_pais' => 'GP', 'pais' => 'Guadalupe',]);
        DB::table('paises')->insert(['cod_pais' => 'GU', 'pais' => 'Guam',]);
        DB::table('paises')->insert(['cod_pais' => 'GT', 'pais' => 'Guatemala',]);
        DB::table('paises')->insert(['cod_pais' => 'GY', 'pais' => 'Guayana',]);
        DB::table('paises')->insert(['cod_pais' => 'GF', 'pais' => 'Guayana Francesa',]);
        DB::table('paises')->insert(['cod_pais' => 'GN', 'pais' => 'Guinea',]);
        DB::table('paises')->insert(['cod_pais' => 'GQ', 'pais' => 'Guinea Ecuatorial',]);
        DB::table('paises')->insert(['cod_pais' => 'GW', 'pais' => 'Guinea-Bissau',]);
        DB::table('paises')->insert(['cod_pais' => 'HT', 'pais' => 'Haití',]);
        DB::table('paises')->insert(['cod_pais' => 'HN', 'pais' => 'Honduras',]);
        DB::table('paises')->insert(['cod_pais' => 'HU', 'pais' => 'Hungría',]);
        DB::table('paises')->insert(['cod_pais' => 'IN', 'pais' => 'India',]);
        DB::table('paises')->insert(['cod_pais' => 'ID', 'pais' => 'Indonesia',]);
        DB::table('paises')->insert(['cod_pais' => 'IQ', 'pais' => 'Irak',]);
        DB::table('paises')->insert(['cod_pais' => 'IR', 'pais' => 'Irán',]);
        DB::table('paises')->insert(['cod_pais' => 'IE', 'pais' => 'Irlanda',]);
        DB::table('paises')->insert(['cod_pais' => 'BV', 'pais' => 'Isla Bouvet',]);
        DB::table('paises')->insert(['cod_pais' => 'CX', 'pais' => 'Isla de Christmas',]);
        DB::table('paises')->insert(['cod_pais' => 'IS', 'pais' => 'Islandia',]);
        DB::table('paises')->insert(['cod_pais' => 'KY', 'pais' => 'Islas Caimán',]);
        DB::table('paises')->insert(['cod_pais' => 'CK', 'pais' => 'Islas Cook',]);
        DB::table('paises')->insert(['cod_pais' => 'CC', 'pais' => 'Islas de Cocos o Keeling',]);
        DB::table('paises')->insert(['cod_pais' => 'FO', 'pais' => 'Islas Faroe',]);
        DB::table('paises')->insert(['cod_pais' => 'HM', 'pais' => 'Islas Heard y McDonald',]);
        DB::table('paises')->insert(['cod_pais' => 'FK', 'pais' => 'Islas Malvinas',]);
        DB::table('paises')->insert(['cod_pais' => 'MP', 'pais' => 'Islas Marianas del Norte',]);
        DB::table('paises')->insert(['cod_pais' => 'MH', 'pais' => 'Islas Marshall',]);
        DB::table('paises')->insert(['cod_pais' => 'UM', 'pais' => 'Islas menores de Estados Unidos',]);
        DB::table('paises')->insert(['cod_pais' => 'PW', 'pais' => 'Islas Palau',]);
        DB::table('paises')->insert(['cod_pais' => 'SB', 'pais' => 'Islas Salomón',]);
        DB::table('paises')->insert(['cod_pais' => 'SJ', 'pais' => 'Islas Svalbard y Jan Mayen',]);
        DB::table('paises')->insert(['cod_pais' => 'TK', 'pais' => 'Islas Tokelau',]);
        DB::table('paises')->insert(['cod_pais' => 'TC', 'pais' => 'Islas Turks y Caicos',]);
        DB::table('paises')->insert(['cod_pais' => 'VI', 'pais' => 'Islas Vírgenes (EEUU)',]);
        DB::table('paises')->insert(['cod_pais' => 'VG', 'pais' => 'Islas Vírgenes (Reino Unido)',]);
        DB::table('paises')->insert(['cod_pais' => 'WF', 'pais' => 'Islas Wallis y Futuna',]);
        DB::table('paises')->insert(['cod_pais' => 'IL', 'pais' => 'Israel',]);
        DB::table('paises')->insert(['cod_pais' => 'IT', 'pais' => 'Italia',]);
        DB::table('paises')->insert(['cod_pais' => 'JM', 'pais' => 'Jamaica',]);
        DB::table('paises')->insert(['cod_pais' => 'JP', 'pais' => 'Japón',]);
        DB::table('paises')->insert(['cod_pais' => 'JO', 'pais' => 'Jordania',]);
        DB::table('paises')->insert(['cod_pais' => 'KZ', 'pais' => 'Kazajistán',]);
        DB::table('paises')->insert(['cod_pais' => 'KE', 'pais' => 'Kenia',]);
        DB::table('paises')->insert(['cod_pais' => 'KG', 'pais' => 'Kirguizistán',]);
        DB::table('paises')->insert(['cod_pais' => 'KI', 'pais' => 'Kiribati',]);
        DB::table('paises')->insert(['cod_pais' => 'KW', 'pais' => 'Kuwait',]);
        DB::table('paises')->insert(['cod_pais' => 'LA', 'pais' => 'Laos',]);
        DB::table('paises')->insert(['cod_pais' => 'LS', 'pais' => 'Lesotho',]);
        DB::table('paises')->insert(['cod_pais' => 'LV', 'pais' => 'Letonia',]);
        DB::table('paises')->insert(['cod_pais' => 'LB', 'pais' => 'Líbano',]);
        DB::table('paises')->insert(['cod_pais' => 'LR', 'pais' => 'Liberia',]);
        DB::table('paises')->insert(['cod_pais' => 'LY', 'pais' => 'Libia',]);
        DB::table('paises')->insert(['cod_pais' => 'LI', 'pais' => 'Liechtenstein',]);
        DB::table('paises')->insert(['cod_pais' => 'LT', 'pais' => 'Lituania',]);
        DB::table('paises')->insert(['cod_pais' => 'LU', 'pais' => 'Luxemburgo',]);
        DB::table('paises')->insert(['cod_pais' => 'MK', 'pais' => 'Macedonia, Ex-República Yugoslava de',]);
        DB::table('paises')->insert(['cod_pais' => 'MG', 'pais' => 'Madagascar',]);
        DB::table('paises')->insert(['cod_pais' => 'MY', 'pais' => 'Malasia',]);
        DB::table('paises')->insert(['cod_pais' => 'MW', 'pais' => 'Malawi',]);
        DB::table('paises')->insert(['cod_pais' => 'MV', 'pais' => 'Maldivas',]);
        DB::table('paises')->insert(['cod_pais' => 'ML', 'pais' => 'Malí',]);
        DB::table('paises')->insert(['cod_pais' => 'MT', 'pais' => 'Malta',]);
        DB::table('paises')->insert(['cod_pais' => 'MA', 'pais' => 'Marruecos',]);
        DB::table('paises')->insert(['cod_pais' => 'MQ', 'pais' => 'Martinica',]);
        DB::table('paises')->insert(['cod_pais' => 'MU', 'pais' => 'Mauricio',]);
        DB::table('paises')->insert(['cod_pais' => 'MR', 'pais' => 'Mauritania',]);
        DB::table('paises')->insert(['cod_pais' => 'YT', 'pais' => 'Mayotte',]);
        DB::table('paises')->insert(['cod_pais' => 'MX', 'pais' => 'México',]);
        DB::table('paises')->insert(['cod_pais' => 'FM', 'pais' => 'Micronesia',]);
        DB::table('paises')->insert(['cod_pais' => 'MD', 'pais' => 'Moldavia',]);
        DB::table('paises')->insert(['cod_pais' => 'MC', 'pais' => 'Mónaco',]);
        DB::table('paises')->insert(['cod_pais' => 'MN', 'pais' => 'Mongolia',]);
        DB::table('paises')->insert(['cod_pais' => 'MS', 'pais' => 'Montserrat',]);
        DB::table('paises')->insert(['cod_pais' => 'MZ', 'pais' => 'Mozambique',]);
        DB::table('paises')->insert(['cod_pais' => 'NA', 'pais' => 'Namibia',]);
        DB::table('paises')->insert(['cod_pais' => 'NR', 'pais' => 'Nauru',]);
        DB::table('paises')->insert(['cod_pais' => 'NP', 'pais' => 'Nepal',]);
        DB::table('paises')->insert(['cod_pais' => 'NI', 'pais' => 'Nicaragua',]);
        DB::table('paises')->insert(['cod_pais' => 'NE', 'pais' => 'Níger',]);
        DB::table('paises')->insert(['cod_pais' => 'NG', 'pais' => 'Nigeria',]);
        DB::table('paises')->insert(['cod_pais' => 'NU', 'pais' => 'Niue',]);
        DB::table('paises')->insert(['cod_pais' => 'NF', 'pais' => 'Norfolk',]);
        DB::table('paises')->insert(['cod_pais' => 'NO', 'pais' => 'Noruega',]);
        DB::table('paises')->insert(['cod_pais' => 'NC', 'pais' => 'Nueva Caledonia',]);
        DB::table('paises')->insert(['cod_pais' => 'NZ', 'pais' => 'Nueva Zelanda',]);
        DB::table('paises')->insert(['cod_pais' => 'OM', 'pais' => 'Omán',]);
        DB::table('paises')->insert(['cod_pais' => 'NL', 'pais' => 'Países Bajos',]);
        DB::table('paises')->insert(['cod_pais' => 'PA', 'pais' => 'Panamá',]);
        DB::table('paises')->insert(['cod_pais' => 'PG', 'pais' => 'Papúa Nueva Guinea',]);
        DB::table('paises')->insert(['cod_pais' => 'PK', 'pais' => 'Paquistán',]);
        DB::table('paises')->insert(['cod_pais' => 'PY', 'pais' => 'Paraguay',]);
        DB::table('paises')->insert(['cod_pais' => 'PE', 'pais' => 'Perú',]);
        DB::table('paises')->insert(['cod_pais' => 'PN', 'pais' => 'Pitcairn',]);
        DB::table('paises')->insert(['cod_pais' => 'PF', 'pais' => 'Polinesia Francesa',]);
        DB::table('paises')->insert(['cod_pais' => 'PL', 'pais' => 'Polonia',]);
        DB::table('paises')->insert(['cod_pais' => 'PT', 'pais' => 'Portugal',]);
        DB::table('paises')->insert(['cod_pais' => 'PR', 'pais' => 'Puerto Rico',]);
        DB::table('paises')->insert(['cod_pais' => 'QA', 'pais' => 'Qatar',]);
        DB::table('paises')->insert(['cod_pais' => 'UK', 'pais' => 'Reino Unido',]);
        DB::table('paises')->insert(['cod_pais' => 'CF', 'pais' => 'República Centroafricana',]);
        DB::table('paises')->insert(['cod_pais' => 'CZ', 'pais' => 'República Checa',]);
        DB::table('paises')->insert(['cod_pais' => 'ZA', 'pais' => 'República de Sudáfrica',]);
        DB::table('paises')->insert(['cod_pais' => 'DO', 'pais' => 'República Dominicana',]);
        DB::table('paises')->insert(['cod_pais' => 'SK', 'pais' => 'República Eslovaca',]);
        DB::table('paises')->insert(['cod_pais' => 'RE', 'pais' => 'Reunión',]);
        DB::table('paises')->insert(['cod_pais' => 'RW', 'pais' => 'Ruanda',]);
        DB::table('paises')->insert(['cod_pais' => 'RO', 'pais' => 'Rumania',]);
        DB::table('paises')->insert(['cod_pais' => 'RU', 'pais' => 'Rusia',]);
        DB::table('paises')->insert(['cod_pais' => 'EH', 'pais' => 'Sahara Occidental',]);
        DB::table('paises')->insert(['cod_pais' => 'KN', 'pais' => 'Saint Kitts y Nevis',]);
        DB::table('paises')->insert(['cod_pais' => 'WS', 'pais' => 'Samoa',]);
        DB::table('paises')->insert(['cod_pais' => 'AS', 'pais' => 'Samoa Americana',]);
        DB::table('paises')->insert(['cod_pais' => 'SM', 'pais' => 'San Marino',]);
        DB::table('paises')->insert(['cod_pais' => 'VC', 'pais' => 'San Vicente y Granadinas',]);
        DB::table('paises')->insert(['cod_pais' => 'SH', 'pais' => 'Santa Helena',]);
        DB::table('paises')->insert(['cod_pais' => 'LC', 'pais' => 'Santa Lucía',]);
        DB::table('paises')->insert(['cod_pais' => 'ST', 'pais' => 'Santo Tomé y Príncipe',]);
        DB::table('paises')->insert(['cod_pais' => 'SN', 'pais' => 'Senegal',]);
        DB::table('paises')->insert(['cod_pais' => 'SC', 'pais' => 'Seychelles',]);
        DB::table('paises')->insert(['cod_pais' => 'SL', 'pais' => 'Sierra Leona',]);
        DB::table('paises')->insert(['cod_pais' => 'SG', 'pais' => 'Singapur',]);
        DB::table('paises')->insert(['cod_pais' => 'SY', 'pais' => 'Siria',]);
        DB::table('paises')->insert(['cod_pais' => 'SO', 'pais' => 'Somalia',]);
        DB::table('paises')->insert(['cod_pais' => 'LK', 'pais' => 'Sri Lanka',]);
        DB::table('paises')->insert(['cod_pais' => 'PM', 'pais' => 'St Pierre y Miquelon',]);
        DB::table('paises')->insert(['cod_pais' => 'SZ', 'pais' => 'Suazilandia',]);
        DB::table('paises')->insert(['cod_pais' => 'SD', 'pais' => 'Sudán',]);
        DB::table('paises')->insert(['cod_pais' => 'SE', 'pais' => 'Suecia',]);
        DB::table('paises')->insert(['cod_pais' => 'CH', 'pais' => 'Suiza',]);
        DB::table('paises')->insert(['cod_pais' => 'SR', 'pais' => 'Surinam',]);
        DB::table('paises')->insert(['cod_pais' => 'TH', 'pais' => 'Tailandia',]);
        DB::table('paises')->insert(['cod_pais' => 'TW', 'pais' => 'Taiwán',]);
        DB::table('paises')->insert(['cod_pais' => 'TZ', 'pais' => 'Tanzania',]);
        DB::table('paises')->insert(['cod_pais' => 'TJ', 'pais' => 'Tayikistán',]);
        DB::table('paises')->insert(['cod_pais' => 'TF', 'pais' => 'Territorios franceses del Sur',]);
        DB::table('paises')->insert(['cod_pais' => 'TP', 'pais' => 'Timor Oriental',]);
        DB::table('paises')->insert(['cod_pais' => 'TG', 'pais' => 'Togo',]);
        DB::table('paises')->insert(['cod_pais' => 'TO', 'pais' => 'Tonga',]);
        DB::table('paises')->insert(['cod_pais' => 'TT', 'pais' => 'Trinidad y Tobago',]);
        DB::table('paises')->insert(['cod_pais' => 'TN', 'pais' => 'Túnez',]);
        DB::table('paises')->insert(['cod_pais' => 'TM', 'pais' => 'Turkmenistán',]);
        DB::table('paises')->insert(['cod_pais' => 'TR', 'pais' => 'Turquía',]);
        DB::table('paises')->insert(['cod_pais' => 'TV', 'pais' => 'Tuvalu',]);
        DB::table('paises')->insert(['cod_pais' => 'UA', 'pais' => 'Ucrania',]);
        DB::table('paises')->insert(['cod_pais' => 'UG', 'pais' => 'Uganda',]);
        DB::table('paises')->insert(['cod_pais' => 'UY', 'pais' => 'Uruguay',]);
        DB::table('paises')->insert(['cod_pais' => 'UZ', 'pais' => 'Uzbekistán',]);
        DB::table('paises')->insert(['cod_pais' => 'VU', 'pais' => 'Vanuatu',]);
        DB::table('paises')->insert(['cod_pais' => 'VE', 'pais' => 'Venezuela',]);
        DB::table('paises')->insert(['cod_pais' => 'VN', 'pais' => 'Vietnam',]);
        DB::table('paises')->insert(['cod_pais' => 'YE', 'pais' => 'Yemen',]);
        DB::table('paises')->insert(['cod_pais' => 'YU', 'pais' => 'Yugoslavia',]);
        DB::table('paises')->insert(['cod_pais' => 'ZM', 'pais' => 'Zambia',]);
        DB::table('paises')->insert(['cod_pais' => 'ZW', 'pais' => 'Zimbabue',]);
    }
}
