@extends('layouts.master')
@section('titulo', 'GamersHUB - Aviso Legal')

@section('contenido')

    <section class="hero">
        <div class="hero-bg-primary" style="background: #a3112e; opacity: 0.9;"></div>
        <div class="container">
            <div class="page-header">
                <div class="page-title">AVISO LEGAL</div>
                <ol class="breadcrumb">
                    <li><a href="/">Inicio</a></li>
                    <li><a href="/">GAMERSHUB</a></li>
                    <li class="active">Aviso Legal</li>
                </ol>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12" style="text-align : justify;">
                    <p><strong>1.DATOS IDENTIFICATIVOS</strong></p>
                    <p><strong>1.1.</strong>&nbsp;En cumplimiento con el deber de informaci&oacute;n recogido en el art&iacute;culo 10 de la Ley 34/2002 de 11 de julio, de Servicios de la Sociedad de la Informaci&oacute;n y el Comercio Electr&oacute;nico y el art&iacute;culo 4, apartado Cuatro de la Ley 56/2007, de 28 de diciembre, de Medidas de Impulso de la Sociedad de la Informaci&oacute;n, a continuaci&oacute;n se reflejan los siguientes datos: La empresa titular de este website es <b>LYNO STUDIOS</b> (en adelante, <b>LynoStudios</b>).</p>
                    <p><strong>1.2.</strong>&nbsp;<b>LynoStudios</b> es titular de www.<b><b><i>www.gamershub.es</i></b></b> y de la red de servicios publicadas en esta p&aacute;gina.</p>
                    <p>&nbsp;</p>
                    <p><strong>2. OBJETO Y &Aacute;MBITO DE APLICACI&Oacute;N</strong></p>
                    <p><strong>2.1.</strong>&nbsp;<b>LynoStudios</b> ofrece a trav&eacute;s de la web &ldquo;<b><b><i>www.gamershub.es</i></b></b>&rdquo; (en adelante, Sitio Web) diversos contenidos, servicios e iniciativas cuya prestaci&oacute;n queda condicionada a la aceptaci&oacute;n plena e incondicional por el destinatario de los mismos de todas y cada una de las presentes Condiciones Generales, lo que constituye condici&oacute;n imprescindible para poder participar en cualquiera de los Servicios existentes o que se creen o se pongan a disposici&oacute;n del p&uacute;blico en el futuro. La utilizaci&oacute;n del Sitio Web atribuye la condici&oacute;n de usuario e implica la aceptaci&oacute;n de todos los t&eacute;rminos y Condiciones Generales descritos. Las citadas Condiciones ser&aacute;n de aplicaci&oacute;n independientemente de las Condiciones Generales de Contrataci&oacute;n que en su caso resulten de obligado cumplimiento.</p>
                    <p>Se entender&aacute; por Usuario a la persona que acceda, navegue, utilice o participe en los servicios y actividades, gratuitas u onerosas, desarrolladas en el Sitio Web o su comunidad.</p>
                    <p><strong>2.2.</strong>&nbsp;Estas Condiciones Generales regulan el acceso, navegaci&oacute;n y uso del Sitio Web as&iacute; como las responsabilidades derivadas de la utilizaci&oacute;n de sus contenidos (entendiendo en adelante por &ldquo;contenidos&rdquo; los textos, gr&aacute;ficos, dibujos, dise&ntilde;os, c&oacute;digos, software, fotograf&iacute;as, m&uacute;sica, v&iacute;deos, sonidos, bases de datos, im&aacute;genes, expresiones e informaciones, as&iacute; como cualquier otra creaci&oacute;n protegida por las leyes nacionales y los tratados internacionales sobre propiedad intelectual e industrial). Independientemente de las mismas, <b>LynoStudios</b> podr&aacute; establecer unas condiciones particulares que regulen la utilizaci&oacute;n y/o contrataci&oacute;n de servicios espec&iacute;ficos ofrecidos a los Usuarios a trav&eacute;s del Sitio Web.</p>
                    <p><strong>2.3.</strong>&nbsp;Las presentes Condiciones Generales no constituyen toda la normativa aplicable a los Servicios. En concreto, <b>LynoStudios</b> podr&aacute; ofrecer o prestar Servicios a trav&eacute;s del Sitio Web que est&eacute;n sujetos a sus propias condiciones particulares, en cuyo caso las mismas ser&aacute;n comunicadas a los usuarios con anterioridad. La participaci&oacute;n en cada una de las actividades o la recepci&oacute;n de los servicios sujetos a Condiciones Particulares ser&aacute; en todo caso prueba de la &iacute;ntegra y total aceptaci&oacute;n de &eacute;stas. En estos supuestos, las Condiciones Generales se aplicar&aacute;n en todo aquello no est&eacute; regulado en las condiciones particulares y que no resulte contradictorio.</p>
                    <p>Asimismo, a trav&eacute;s del Sitio Web, <b>LynoStudios</b> podr&aacute; habilitar a terceras entidades para que publiciten o presten sus servicios. En estos casos, <b>LynoStudios</b> no ser&aacute; responsable de establecer las condiciones generales y particulares a tener en cuenta en la utilizaci&oacute;n, prestaci&oacute;n o contrataci&oacute;n de estos servicios por terceros y, por tanto, no podr&aacute; ser considerado responsable de los mismos.</p>
                    <p><strong>2.4.</strong>&nbsp;Antes de utilizar y/o contratar dichos servicios espec&iacute;ficos prestados por <b>LynoStudios</b>, el Usuario deber&aacute; leer atentamente las correspondientes condiciones particulares creadas a tal efecto. La utilizaci&oacute;n y/o la contrataci&oacute;n de dichos servicios espec&iacute;ficos implica la aceptaci&oacute;n de las condiciones particulares que los regulen en el momento en que se produzca dicha utilizaci&oacute;n y/o contrataci&oacute;n.</p>
                    <p>&nbsp;</p>
                    <p><strong>3. ACCESOS</strong></p>
                    <p><strong>3.1.</strong>&nbsp;Los sitios web pertenecientes a <b><b><i>www.gamershub.es</i></b></b> proporcionan el acceso a multitud de informaci&oacute;n, servicios, programas o datos (en adelante, &ldquo;los contenidos&rdquo;) en Internet pertenecientes a <b>LynoStudios</b> o a sus licenciantes a los que el usuario puede tener acceso. Dicho acceso tiene car&aacute;cter libre y gratuito. No obstante algunos de los servicios y/o contenidos ofrecidos por <b>LynoStudios</b> o terceros a trav&eacute;s del Sitio Web pueden encontrarse sujetos a la contrataci&oacute;n previa del servicio o producto y al pago de una cantidad de dinero en la forma que se determine en las correspondientes Condiciones Particulares, en cuyo caso se pondr&aacute;n a su disposici&oacute;n de forma clara.</p>
                    <p><strong>3.2.</strong>&nbsp;Queda prohibida la contrataci&oacute;n de productos y servicios a trav&eacute;s del Sitio Web por parte de menores de edad legal, debiendo obtener debidamente y con anterioridad, el consentimiento de sus padres, tutores o representantes legales, los cuales ser&aacute;n considerados como responsables de los actos que lleven a cabo los menores a su cargo, conforme a la normativa vigente.</p>
                    <p>&nbsp;</p>
                    <p><strong>4. UTILIZACI&Oacute;N DEL SITIO WEB</strong></p>
                    <p><strong>4.1.</strong>&nbsp;Los contenidos incluidos en el Sitio Web se facilitan &uacute;nicamente a usuarios finales. Cualquier uso comercial no autorizado de los mismos, o su reventa, quedan prohibidos, salvo que se cuente con la previa autorizaci&oacute;n escrita de <b>LynoStudios</b>.</p>
                    <p><strong>4.2.</strong>&nbsp;El usuario asume la responsabilidad del uso del Sitio Web. Dicha responsabilidad se extiende al registro que fuese necesario para acceder a determinados servicios o contenidos. En dicho registro el usuario ser&aacute; responsable de aportar informaci&oacute;n veraz y l&iacute;cita. Como consecuencia de este registro, al usuario se le puede proporcionar una contrase&ntilde;a de la que ser&aacute; responsable, comprometi&eacute;ndose a hacer un uso correcto y confidencial de la misma. Se compromete a no ceder su uso a terceros, ya sea temporal o permanente, ni a permitir su acceso a personas ajenas. Ser&aacute; responsabilidad del Usuario la utilizaci&oacute;n de los servicios por cualquier tercero ileg&iacute;timo que emplee a tal efecto una contrase&ntilde;a a causa de una utilizaci&oacute;n no diligente o de la p&eacute;rdida de la misma por el usuario.</p>
                    <p><strong>4.3.</strong>&nbsp;En virtud de lo anterior, es obligaci&oacute;n del usuario notificar de forma inmediata a <b><b><i>www.gamershub.es</i></b></b> cualquier hecho que permita el uso indebido de los identificadores y/o contrase&ntilde;as, tales como el robo, extrav&iacute;o, o el acceso no autorizado a los mismos, con el fin de proceder a su inmediata cancelaci&oacute;n. Mientras no se comuniquen tales hechos, <b>LynoStudios</b> quedar&aacute; eximida de cualquier responsabilidad que pudiera derivarse del uso indebido de los identificadores o contrase&ntilde;as por terceros no autorizados.</p>
                    <p>El usuario se compromete a utilizar el Sitio Web y sus servicios de conformidad con la ley, con las presentes Condiciones Generales, as&iacute; como las pr&aacute;cticas generalmente aceptadas en Internet. As&iacute; como a hacer un uso adecuado de los contenidos y servicios que <b>LynoStudios</b> ofrece a trav&eacute;s de su Sitio Web y con car&aacute;cter enunciativo pero no limitativo, a no emplearlos para (1) incurrir en actividades il&iacute;citas, ilegales o contrarias a la buena fe y al orden p&uacute;blico; (2) difundir contenidos o propaganda de car&aacute;cter racista, xen&oacute;fobo, pornogr&aacute;fico-ilegal, de apolog&iacute;a del terrorismo o atentatorio contra los derechos humanos; (3) provocar da&ntilde;os en los sistemas f&iacute;sicos y l&oacute;gicos de <b>LynoStudios</b>, de sus proveedores o de terceras personas; (4) introducir o difundir en la red virus inform&aacute;ticos o cualesquiera otros sistemas f&iacute;sicos o l&oacute;gicos que sean susceptibles de provocar los da&ntilde;os anteriormente<br />mencionados; (5) intentar acceder y, en su caso, utilizar las cuentas de correo electr&oacute;nico y/o la identificaci&oacute;n de otros usuarios y modificar o manipular sus mensajes.</p>
                    <p><strong>4.4</strong>&nbsp;El usuario se obliga a usar los contenidos de forma diligente, correcta y l&iacute;cita y, en particular, se compromete a abstenerse de reproducir o copiar, distribuir, permitir el acceso del p&uacute;blico a trav&eacute;s de cualquier modalidad de comunicaci&oacute;n p&uacute;blica, transformar o modificar los contenidos, a menos que se cuente con la autorizaci&oacute;n del titular de los correspondientes derechos o ello resulte legalmente permitido; emplear los contenidos y, en particular, la informaci&oacute;n de cualquier clase obtenida a trav&eacute;s del Sitio Web o de los servicios para remitir publicidad, comunicaciones con fines de venta directa o con cualquier otra clase de finalidad comercial, mensajes no solicitados dirigidos a una pluralidad de personas con independencia de su finalidad, as&iacute; como a abstenerse de comercializar o divulgar de cualquier modo dicha informaci&oacute;n.</p>
                    <p><strong>4.5.</strong>&nbsp;<b>LynoStudios</b> se reserva el derecho de moderar y/o retirar todos aquellos comentarios y aportaciones que vulneren el respeto a la dignidad de la persona, que sean discriminatorios, xen&oacute;fobos, racistas, pornogr&aacute;ficos, que atenten contra la juventud o la infancia, el orden o la seguridad p&uacute;blica o que, a su juicio, no resultaran adecuados para su publicaci&oacute;n.</p>
                    <p>Adem&aacute;s, <b>LynoStudios</b> se reserva el derecho de exclusi&oacute;n, pudiendo denegar o retirar el acceso al Sitio Web y/o a los servicios ofrecidos sin necesidad de pre-aviso, a instancia propia o de un tercero, a aquellos usuarios que incumplan las presentes Condiciones Generales de Uso, as&iacute; como a aquellos que generen comentarios inapropiados o que vayan en contra de los principios del Sitio Web y/o los servicios ofrecidos conforme a su s&oacute;lo criterio.</p>
                    <p>En caso de incumplimiento por parte del usuario de cualquiera de las obligaciones a las que est&aacute;s sometido por ley y por las presentes Condiciones Generales en relaci&oacute;n con el uso del Sitio Web, responder&aacute; y nos dejar&aacute; indemnes por los da&ntilde;os que, por su incumplimiento de estas obligaciones, hubiera causado a terceros.</p>
                    <p><strong>4.6.</strong>&nbsp;<b>LynoStudios</b> perseguir&aacute; el incumplimiento de las presentes condiciones as&iacute; como cualquier utilizaci&oacute;n indebida de sus p&aacute;ginas web ejerciendo todas las acciones civiles y penales que le puedan corresponder en derecho.</p>
                    <p>&nbsp;</p>
                    <p><strong>5. EXENCI&Oacute;N DE RESPONSABILIDAD</strong></p>
                    <p><strong>5.1.</strong>&nbsp;<b>LynoStudios</b> no se hace responsable, en ning&uacute;n caso, de los da&ntilde;os y perjuicios de cualquier naturaleza que pudieran ocasionar, a t&iacute;tulo enunciativo: errores u omisiones en los contenidos, falta de disponibilidad del portal, la invulnerabilidad del Sitio Web y/o la inexpugnabilidad de las medidas de seguridad que se adopten en el mismo; la falta de utilidad o rendimiento de los contenidos del Sitio Web; o la transmisi&oacute;n de virus o programas maliciosos en los contenidos, a pesar de haber adoptado todas las medidas tecnol&oacute;gicas necesarias para evitarlo.</p>
                    <p>No obstante, <b>LynoStudios</b> declara que ha adoptado todas las medidas necesarias, dentro de sus posibilidades y del estado de la tecnolog&iacute;a, para garantizar el funcionamiento del Sitio Web y evitar la existencia y transmisi&oacute;n a los Usuarios de virus y otros componentes da&ntilde;inos.</p>
                    <p>Asimismo <b>LynoStudios</b> no ser&aacute; responsable de las opiniones vertidas por los usuarios a trav&eacute;s de los foros, comunidades, comentarios u otras herramientas de participaci&oacute;n.</p>
                    <p><strong>5.2.</strong>&nbsp;<b>LynoStudios</b> no garantiza la calidad, exactitud, fiabilidad, correcci&oacute;n, integridad o moralidad de los datos, programas, informaciones u opiniones, cualquiera que sea su origen, que circulen por su red o por las redes a las que el usuario del Sitio Web pueda acceder a trav&eacute;s de &eacute;sta. El usuario declara y garantiza que mantendr&aacute; exenta de toda responsabilidad por estos conceptos a <b>LynoStudios</b>. En consecuencia, el usuario asume bajo su exclusiva responsabilidad las consecuencias, da&ntilde;os o acciones que pudieran derivarse del acceso a dichos contenidos as&iacute; como de su reproducci&oacute;n o difusi&oacute;n.</p>
                    <p><strong>5.3.</strong>&nbsp;<b>LynoStudios</b> no es responsable, ni garantiza, el cumplimiento por terceros de la normativa de Protecci&oacute;n de Datos ni de la Sociedad de la Informaci&oacute;n ni se responsabiliza de la integridad y veracidad del contenido de los enlaces del Sitio Web.</p>
                    <p>&nbsp;</p>
                    <p><strong>6. DERECHOS DE PROPIEDAD INTELECTUAL E INDUSTRIAL</strong></p>
                    <p><strong>6.1.</strong>&nbsp;<b>LynoStudios</b> como autor de obra colectiva, o cualquiera obra o prestaciones de cualquier naturaleza, es titular de los derechos de propiedad intelectual e industrial del Sitio Web, y es tambi&eacute;n titular o tiene la correspondiente licencia, autorizaci&oacute;n o cesi&oacute;n sobre los derechos de propiedad intelectual, industrial y de imagen sobre los contenidos, servicios y elementos (logos, marcas, s&iacute;mbolos, c&oacute;digo fuente, v&iacute;deo, sonido, software, etc) disponibles a trav&eacute;s del mismo. Todos los derechos reservados.</p>
                    <p><strong>6.2.</strong>&nbsp;En ning&uacute;n caso se entender&aacute; que el acceso y navegaci&oacute;n del usuario implica una renuncia, transmisi&oacute;n, licencia o cesi&oacute;n total ni parcial de dichos derechos por parte de <b>LynoStudios</b>.</p>
                    <p><strong>6.3.</strong>&nbsp;En consecuencia, no est&aacute; permitido suprimir, eludir o manipular el aviso de derechos de autor, propiedad intelectual (&ldquo;copyright&rdquo;) y cualesquiera otros datos de identificaci&oacute;n de los derechos de <b>LynoStudios</b> o de sus titulares incorporados a los contenidos, as&iacute; como los dispositivos t&eacute;cnicos de protecci&oacute;n, las huellas digitales o cualesquiera mecanismos de informaci&oacute;n y/o de identificaci&oacute;n que pudieren contenerse en los contenidos.</p>
                    <p><strong>6.4.</strong>&nbsp;Asimismo est&aacute; prohibido modificar, copiar, reutilizar, extraer, explotar, reproducir, comunicar p&uacute;blicamente, hacer segundas o posteriores publicaciones, cargar archivos, enviar por correo, transmitir, usar, tratar o distribuir de cualquier forma, en cualquier soporte y por cualquier medio t&eacute;cnico, la totalidad o parte de los contenidos incluidos en el Sitio Web si no se cuenta con la autorizaci&oacute;n expresa y por escrito de <b>LynoStudios</b> o, en su caso, del titular o titulares de los derechos a que corresponda.</p>
                    <p>En particular, <b>LynoStudios</b> se opone de manera expresa a que la reproducci&oacute;n de sus p&aacute;ginas pueda ser considerada una cita en los t&eacute;rminos previstos en el art&iacute;culo 32, 1&ordm; p&aacute;rrafo segundo, de la ley de propiedad intelectual.</p>
                    <p><strong>6.5.</strong>&nbsp;El Usuario se compromete a respetar los derechos de Propiedad Intelectual e Industrial titularidad de <b>LynoStudios</b>, y por ello reconoce que la reproducci&oacute;n, distribuci&oacute;n, comercializaci&oacute;n, transformaci&oacute;n, y en general, cualquier otra forma de explotaci&oacute;n, por cualquier procedimiento, de todo o parte de los contenidos de este Sitio Web y sus p&aacute;ginas webs constituye una infracci&oacute;n de los derechos de propiedad intelectual y/o industrial del titular del Sitio Web o de los titulares de los mismos.</p>
                    <p>Podr&aacute; visualizar los elementos de los diferentes sites e incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte f&iacute;sico siempre y cuando sea, &uacute;nica y exclusivamente, para su uso personal y privado.</p>
                    <p>En caso de que est&eacute; interesado en una autorizaci&oacute;n o licencia para utilizar en cualquier forma los contenidos del Sitio Web dir&iacute;jase a contacto @ <b><b><i>www.gamershub.es</i></b></b> o utilizando nuestro formulario de contacto http://www.<b><b><i>www.gamershub.es</i></b></b>/contacto</p>
                    <p><strong>6.6.</strong>&nbsp;El usuario deber&aacute; abstenerse de suprimir, alterar, eludir o manipular cualquier dispositivo de protecci&oacute;n o sistema de seguridad que estuviera instalado en el las p&aacute;ginas de <b>LynoStudios</b>.</p>
                    <p>&nbsp;</p>
                    <p><strong>7. ESPACIOS Y HERRAMIENTAS DE PARTICIPACI&Oacute;N</strong></p>
                    <p><strong>7.1.</strong>&nbsp;El Sitio Web pone a disposici&oacute;n del usuario distintos espacios y herramientas de participaci&oacute;n para fomentar la conversaci&oacute;n y el intercambio de ideas y opiniones entre los usuarios. Su objetivo es permanecer abierto y accesible para cualquiera siempre que se respeten unas normas de convivencia y respeto b&aacute;sicas.</p>
                    <p>Por medio de estas herramientas y espacios el usuario podr&aacute;:</p>
                    <p>Disponer de un espacio propio, llamado Perfil que le identificar&aacute; bajo su nombre real o su identificador de usuario (nick) asociado a la cuenta de usuario. La cuenta de usuario podr&aacute;, si el usuario as&iacute; lo elige, ser asociada a una imagen (avatar) de su elecci&oacute;n y que le representar&aacute; de manera visual en los diferentes espacios de participaci&oacute;n del Sitio Web.</p>
                    <p>En el Perfil se reflejar&aacute; la actividad de participaci&oacute;n en <b><b><i>www.gamershub.es</i></b></b>. Los comentarios del usuario son p&uacute;blicos y podr&aacute;n consultarse recopilados en un el Perfil junto a las respuestas y menciones que haya recibido de otros usuarios.</p>
                    <p>Otros usuarios podr&aacute;n seguir la actividad del Usuario que se genere en el Sitio Web, los comentarios o los concursos y promociones en los que el Usuario este participando.</p>
                    <p>El Usuario podr&aacute; seguir la actividad de otros usuarios del Sitio Web que le parezcan interesantes, qu&eacute; comentan y d&oacute;nde lo hacen. El Usuario podr&aacute; seguir la actividad generada por los colaboradores o redactores del Sitio Web o seguir las noticias generadas en torno al mundo de los videojuegos y todo lo relacionado con ello.</p>
                    <p>El Sitio Web podr&aacute; enviar notificaciones a los usuarios mediante correo electr&oacute;nico a la direcci&oacute;n facilitada en el proceso de registro.</p>
                    <p>Este Perfil ser&aacute; p&uacute;blico pero se mantendr&aacute;n ocultas, s&oacute;lo visibles por el usuario, ciertas actividades de car&aacute;cter privado (tales como inicio de seguimiento, contenidos moderados, notificaciones individuales de participaci&oacute;n en promociones y juegos y cualesquiera otras notificaciones privadas).</p>
                    <p><strong>7.2 Normas de Participaci&oacute;n</strong></p>
                    <blockquote>
                        <p><strong><em>7.2.1.</em></strong><em>&nbsp;En ning&uacute;n caso se permitir&aacute; la publicaci&oacute;n de contenidos que de forma manifiesta fomenten el odio, el desprecio o la discriminaci&oacute;n por motivos de nacimiento, raza, sexo, religi&oacute;n, nacionalidad, opini&oacute;n o cualquier otra circunstancia personal o social.</em></p>
                        <p><em>Tampoco se tolerar&aacute;n, en ning&uacute;n caso, sea cual sea su fin, los intentos de suplantar la identidad de terceras personas ni la publicaci&oacute;n de datos de contacto privados.</em></p>
                        <p><strong><em>7.2.2.</em></strong><em>&nbsp;Tampoco se aprobar&aacute;n mensajes que contengan &lsquo;spam&rsquo; ni aquellos con enlaces a otras p&aacute;ginas web similares y/o que no tengan relaci&oacute;n con la conversaci&oacute;n.</em></p>
                        <p><strong><em>7.2.3.</em></strong><em>&nbsp;Buscamos mensajes educados para un intercambio de opiniones de modo que no se permitir&aacute;n los ataques personales ni los mensajes no relacionados con la conversaci&oacute;n.</em></p>
                        <p><strong><em>7.2.4.</em></strong><em>&nbsp;Para evitar comentarios repetidos, recomendamos leer primero una conversaci&oacute;n antes de participar en ella.</em></p>
                        <p><strong><em>7.2.5.</em></strong><em>&nbsp;El Usuario es responsable de la totalidad de las manifestaciones en internet igual que en cualquier otro lugar. Adem&aacute;s deber&aacute; respetar al resto de usuarios, debe ser tolerante y respetuoso con los mensajes y opiniones de los dem&aacute;s.</em></p>
                        <p><strong><em>7.2.6.</em></strong><em>&nbsp;Los Mensajes de los usuarios no se corresponden necesariamente con nuestra l&iacute;nea editorial, de actuaci&oacute;n, de pensamiento o cualquier clase de ideolog&iacute;a.</em></p>
                        <p><strong><em>7.2.7.</em></strong><em>&nbsp;Est&aacute; totalmente prohibido publicar promociones y enlaces de ofertas comerciales, publicidad, material promocional, cartas cadena ni cualquier actividad promocional directa o indirecta o cualquier otro tipo de comentario que no se ajuste al normal desarrollo de los temas tratados.</em></p>
                        <p><strong><em>7.2.8.</em></strong><em>&nbsp;El Sitio Web se reserva el derecho de suprimir, por cualquier raz&oacute;n y sin previo aviso, cualquier informaci&oacute;n o contenido generado en los espacios de participaci&oacute;n.</em></p>
                        <p><strong><em>7.2.9.</em></strong><em>&nbsp;El Sitio Web pone a disposici&oacute;n una herramienta para denuncia de los mensajes o contenidos inadecuados accesible mediante un bot&oacute;n habilitado al efecto.</em></p>
                        <p><strong><em>7.2.10.</em></strong><em>&nbsp;El Sitio Web declina expresamente cualquier responsabilidad dimanante de los contenidos alojados por los usuarios, sin perjuicio de lo cual adoptar&aacute; las medidas oportunas para detectar y atender reclamaciones sobre posible actividades il&iacute;citas por parte de los mismos, reserv&aacute;ndose expresamente la posibilidad de interrumpir en cualquier momento y sin previo aviso, temporal o definitivamente, el servicio de participaci&oacute;n ofrecido a cualquier usuario cuyos contenidos puedan ser considerados ilegales, prohibidos o simplemente inadecuados.</em></p>
                        <p><strong><em>7.2.11.</em></strong><em>&nbsp;El uso de las herramientas de participaci&oacute;n de las redes sociales (Facebook/Twitter,etc) que el Sitio Web ponga a disposici&oacute;n del usuario son &uacute;nicamente responsabilidad de &eacute;ste.</em></p>
                    </blockquote>
                    <p><strong>8. LIMITACIONES DE USO</strong></p>
                    <p>El usuario se obliga a no utilizar los servicios ofrecidos por el Sitio Web para la realizaci&oacute;n de actividades contrarias a la ley, a la moral, al orden p&uacute;blico y, en general, a hacer un uso conforme a las presentes condiciones. Se obliga asimismo a no realizar actividades publicitarias o de explotaci&oacute;n comercial y a no remitir ning&uacute;n tipo de<br />mensaje utilizando una identidad falsa, as&iacute; como a no camuflar en manera alguna el origen del mensaje ni a remitir publicidad no solicitada.</p>
                    <p>En caso de que <b>LynoStudios</b> descubriera, bien de forma directa o a trav&eacute;s de solicitudes o requerimientos de terceros, la existencia de contenidos que pudieran infringir la legalidad vigente o derechos de terceros, las presentes condiciones, las normas de funcionamiento del Sitio Web o la utilizaci&oacute;n de las mismas con fines fraudulentos o il&iacute;citos y/o no autorizados por los presentes t&eacute;rminos legales, <b>LynoStudios</b> se reserva el derecho, sin necesidad de autorizaci&oacute;n previa, de eliminar dichos contenidos infractores o implementar cualquier otra medida que considere necesaria para evitar la continuidad en la comisi&oacute;n del il&iacute;cito o de la infracci&oacute;n detectada. Id&eacute;ntica medida ser&aacute; aplicable en caso de que se detecte una utilizaci&oacute;n que, por sus caracter&iacute;sticas tales como tama&ntilde;o, formato o similares, dificulten el funcionamiento del Sitio Web.</p>
                    <p><b>LynoStudios</b> se reserva el derecho a rechazar la admisi&oacute;n, publicaci&oacute;n, muestra o transmisi&oacute;n de cualquier contenido, a su discreci&oacute;n, por lo que la recepci&oacute;n de los contenidos en el Sitio Web no implica en ning&uacute;n caso obligaci&oacute;n alguna de <b>LynoStudios</b> de ponerlos a disposici&oacute;n de los usuarios.</p>
                    <p>&nbsp;</p>
                    <p><strong>9. CONTENIDOS GENERADOS POR EL USUARIO</strong></p>
                    <p><strong>9.1.</strong>&nbsp;En el caso de que el usuario env&iacute;e contenidos de cualquier tipo al Sitio Web, el mismo declara, garantiza y acepta que tiene derecho a hacerlo libremente, que dicha informaci&oacute;n no infringe ning&uacute;n derecho de propiedad intelectual, de marca, de patente, secreto comercial, o cualquier otro derecho de tercero, que dicha informaci&oacute;n no tiene car&aacute;cter confidencial y que dicha informaci&oacute;n no es perjudicial para terceros. Adem&aacute;s, en caso necesario, el usuario deber&aacute; proporcionar la informaci&oacute;n que le sea requerida, en relaci&oacute;n con el origen y titularidad de los contenidos y el procedimiento por el que el participante los haya obtenido. Esta informaci&oacute;n deber&aacute; ser veraz y comprobable en el caso de que <b>LynoStudios</b> as&iacute; lo requiera, asumiendo el usuario su veracidad.</p>
                    <p><strong>9.2.</strong>&nbsp;El usuario reconoce asumir la responsabilidad y dejar&aacute; indemne a <b>LynoStudios</b> por cualquier da&ntilde;o derivado de cualquier comunicaci&oacute;n que suministre personalmente o a su nombre, alcanzando dicha responsabilidad sin restricci&oacute;n alguna la exactitud, legalidad, originalidad y titularidad de la misma.</p>
                    <p><strong>9.3.</strong>&nbsp;<b>LynoStudios</b> se reserva la facultad de decidir la divulgaci&oacute;n o publicaci&oacute;n de los contenidos enviados por el Usuario o de destacar dicho contenido en aquellas p&aacute;ginas del Sitio Web que consideremos oportunas.</p>
                    <p><strong>9.4.</strong>&nbsp;En el caso de que los contenidos enviados por los usuarios contengan im&aacute;genes el usuario declara y garantiza y acepta:</p>
                    <p>1&ordm; Que es mayor de edad a los efectos legales.<br />2&ordm; Que es el autor o titular de los derechos de las im&aacute;genes y que tiene derecho a enviarlas y que las mismas no infringen ning&uacute;n derecho de propiedad intelectual, de marca o cualquier otro derecho de tercero.<br />3&ordm; Que las citadas im&aacute;genes han sido realizadas con el consentimiento de las personas que aparecen en las mismas y que en caso de aparecer menores el citado consentimiento se ha prestado por escrito por sus representantes legales y podr&aacute; acreditarlo en cualquier momento que sea requerido para ello.</p>
                    <p><strong>9.5.</strong>&nbsp;<b>LynoStudios</b>, se reserva la facultad de comunicar p&uacute;blicamente las im&aacute;genes o el resto del contenido publicado por el usuario que estime conveniente y queda facultada para reproducir y comunicar dicho contenido (informaci&oacute;n, im&aacute;genes, audio,video, etc) en todos los medios pertenecientes a <b><b><i>www.gamershub.es</i></b></b> y otros proyectos de la empresa <b>LynoStudios</b> S.L.U.</p>
                    <p><strong>9.6.</strong>&nbsp;El Usuario reconoce asumir la responsabilidad y dejar&aacute; indemne a <b>LynoStudios</b> por las anteriores manifestaciones.</p>
                    <p><strong>9.7.</strong>&nbsp;El Usuario cede a t&iacute;tulo gratuito a <b>LynoStudios</b>, sin car&aacute;cter de exclusiva, los derechos de reproducci&oacute;n, distribuci&oacute;n, transformaci&oacute;n y comunicaci&oacute;n p&uacute;blica, en todas las posibles modalidades, en relaci&oacute;n a los contenidos enviados ( fotograf&iacute;as, im&aacute;genes con o sin movimiento, textos, informaciones, bases de datos grabaciones sonoras o cualesquiera otras obras o prestaciones) para su explotaci&oacute;n a trav&eacute;s tanto de Internet como de cualquier otro medio de explotaci&oacute;n, utilizando cualquier tecnolog&iacute;a conocida o por conocer. La citada cesi&oacute;n se realiza para todo el mundo, por la duraci&oacute;n m&aacute;xima actualmente prevista en la ley de propiedad intelectual y con expresa facultad de cesi&oacute;n a terceros. A t&iacute;tulo enunciativo, <b>LynoStudios</b> podr&aacute; explotar los contenidos audiovisuales, o textos, puestos a su disposici&oacute;n a trav&eacute;s del Sitio Web por los usuarios (y ceder a terceros su explotaci&oacute;n) en Internet, televisi&oacute;n en abierto, televisi&oacute;n de pago, pago por visi&oacute;n, v&iacute;deo bajo demanda, soportes de video (DVD, CD ROM, Blue Ray, HD DVD, entre otros), explotaci&oacute;n en dispositivos m&oacute;viles, cines, aeronaves, establecimientos p&uacute;blicos o privados, abiertos o no al p&uacute;blico, tales como hospitales, hoteles, etc&eacute;tera. Los derechos se entender&aacute;n cedidos por el m&aacute;ximo tiempo permitido por la ley y sin limitaci&oacute;n territorial alguna.</p>
                    <p>&nbsp;</p>
                    <p><strong>10. INFRACCIONES</strong></p>
                    <p><b>LynoStudios</b> no ser&aacute; responsable de las infracciones realizadas por cualquier usuario del Sitio Web que afecten a cualquier otro usuario de la misma, o a terceros, incluyendo las que se refieran a derechos de propiedad intelectual, copyrights, marcas, patentes, informaci&oacute;n confidencial y/o cualquier otro derecho de propiedad intelectual o industrial. Asimismo, tampoco responder&aacute; de las infracciones de un usuario a la intimidad personal, honor y/o propia imagen de otro usuario o de un tercero, que ser&aacute;n responsabilidad exclusiva del infractor, ya se trate de afirmaciones vertidas en foros, opiniones del usuario o materiales audiovisuales aportados por &eacute;ste. El usuario acepta su responsabilidad y las consecuencias derivadas de la infracci&oacute;n de estas normas, oblig&aacute;ndose a mantener indemne a <b>LynoStudios</b> de cualquier reclamaci&oacute;n por este motivo.</p>
                    <p>En especial, <b>LynoStudios</b> no ser&aacute; responsable ni de la disponibilidad t&eacute;cnica, ni de los contenidos, ni de los da&ntilde;os que el usuario pudiera sufrir como consecuencia de la consulta o el uso de los contenidos ofrecidos a trav&eacute;s de p&aacute;ginas a la que el usuario acceda a trav&eacute;s de links, botones, banners etc., incluidos en el Sitio Web. En particular, el usuario podr&iacute;a encontrar en estas p&aacute;ginas asociadas encuestas o formularios en los que se le solicite proporcionar informaci&oacute;n personal o de otro tipo, por distintos motivos o finalidades. El usuario es libre de aceptar o no estas ofertas, pero si lo hace establecer&aacute; una relaci&oacute;n directa con la web en cuesti&oacute;n, siendo posible que <b>LynoStudios</b> no tenga relaci&oacute;n con ella distinta del establecimiento de un link en el Sitio Web. En este caso, esa web se rige por sus propias normas de confidencialidad y condiciones generales, que el usuario deber&aacute; consultar y, en su caso, aceptar. <b>LynoStudios</b> no garantiza el cumplimiento de la normativa de protecci&oacute;n de datos de car&aacute;cter personal ni de la sociedad de la informaci&oacute;n en esas webs mencionadas, que prestan servicios de terceros y no se responsabiliza de da&ntilde;os y perjuicios de cualquier naturaleza causados por terceros a trav&eacute;s de esa web y en particular y a t&iacute;tulo meramente enunciativo, los causados por:</p>
                    <ul>
                        <li>El incumplimiento de la ley, la moral o el orden p&uacute;blico.</li>
                        <li>La incorporaci&oacute;n de virus o cualquier otro c&oacute;digo inform&aacute;tico, archivo o programa que pueda da&ntilde;ar, interrumpir o impedir el normal funcionamiento de cualquier software, hardware o equipo de telecomunicaciones.</li>
                        <li>La infracci&oacute;n de los derechos de propiedad intelectual e industrial, de los secretos empresariales, de compromisos contractuales de cualquier clase.</li>
                        <li>La realizaci&oacute;n de actos que constituyan publicidad il&iacute;cita, enga&ntilde;osa o desleal y, en general, que constituyan competencia desleal.</li>
                        <li>La falta de veracidad, exactitud, calidad, pertinencia y/o actualidad de los contenidos transmitidos, difundidos, almacenados, recibidos, obtenidos, puestos a disposici&oacute;n o accesibles; la infracci&oacute;n de los derechos al honor, a la intimidad personal y familiar y a la imagen de las personas o, en general, cualquier tipo de derechos de terceros.</li>
                        <li>La inadecuaci&oacute;n para cualquier clase de prop&oacute;sito y la defraudaci&oacute;n de las expectativas generadas, o los vicios y defectos que pudieran generarse en la relaci&oacute;n terceros.</li>
                        <li>El incumplimiento, retraso en el cumplimiento, cumplimiento defectuoso o terminaci&oacute;n por cualquier causa de las obligaciones contra&iacute;das por terceros y contratos realizados con terceros.</li>
                    </ul>
                    <p>Por favor, si cualquier usuario observase que se est&aacute;n incumpliendo alguna de las normas aqu&iacute; se&ntilde;aladas o la legalidad vigente, por otro usuario o un prestador de servicio ajeno, rogamos se ponga en contacto, lo antes posible, con <b>LynoStudios</b> a contacto @ <b><b><i>www.gamershub.es</i></b></b> o utilizando nuestro formulario de contacto&nbsp;<a href="http://www.<b><b><i>www.gamershub.es</i></b></b>/contacto">http://www.<b><b><i>www.gamershub.es</i></b></b>/contacto</a></p>
                    <p>&nbsp;</p>
                    <p><strong>11. MODIFICACIONES</strong></p>
                    <p><b>LynoStudios</b> se reserva el derecho de efectuar sin previo aviso las modificaciones que considere oportunas en la web <b><b><i>www.gamershub.es</i></b></b> y en el resto de comunidades, pudiendo cambiar, suprimir o a&ntilde;adir tanto los contenidos y servicios que se presten a trav&eacute;s de la misma como la forma en la que &eacute;stos aparezcan presentados o localizados en el Sitio Web.</p>
                    <p>Asimismo, <b>LynoStudios</b> se reserva la rescisi&oacute;n de los servicios que realiza, en aquellos usuarios que no cumplan con los t&eacute;rminos y condiciones legales de uso, as&iacute; como con la legislaci&oacute;n vigente.</p>
                    <p>Tambi&eacute;n <b>LynoStudios</b> se reserva el derecho de cancelar en cualquier momento y sin responsabilidad alguna cualquiera de los Servicios ofrecidos a trav&eacute;s del Sitio Web, incluyendo la posibilidad de eliminar contenidos previamente seleccionados para figurar en el Sitio Web.</p>
                    <p>&nbsp;</p>
                    <p><strong>12. RSS</strong></p>
                    <p><strong>12.1. Lectores de RSS</strong></p>
                    <p>A trav&eacute;s de este servicio, la web te ofrece la posibilidad de conocer al momento todos los contenidos nuevos que se publiquen; estar informado y no perderte nada de lo que ocurra en ellos, o bien recibir las principales novedades de la web.</p>
                    <p>Para utilizar las fuentes RSS existen diferentes opciones. Una de ellas consiste en instalar un programa llamado &lsquo;agregador&rsquo; o lector de noticias. Son programas -en su mayor&iacute;a gratuitos, como Feedreader, RSS Reader, Sharp Reader o Feed Demon- que se instalan en el ordenador y que permiten agrupar la informaci&oacute;n de diferentes webs y consultarla desde una &uacute;nica p&aacute;gina.</p>
                    <p>Adem&aacute;s, existe otra opci&oacute;n que son los servicios on-line, como por ejemplo Bloglines, MyFeedster, MyYahoo.</p>
                    <p><strong>12.2.</strong>&nbsp;Objeto</p>
                    <p>12.2.1. El RSS es un formato de texto, est&aacute;ndar y p&uacute;blico basado en XML que sirve para facilitar el acceso a la informaci&oacute;n Web que se actualiza con regularidad, logrando que el usuario tenga acceso al momento de las novedades producidas en la informaci&oacute;n que es de su inter&eacute;s. A esta manera de distribuir contenidos se le llama &lsquo;sindicaci&oacute;n&rsquo;.</p>
                    <p>Su funci&oacute;n es la de mostrar un sumario o &iacute;ndice con los contenidos y noticias que ha publicado un sitio web. Gracias a los agregadores o lectores de feeds (programas o sitios que permiten leer fuentes RSS) se pueden obtener diversos contenidos de distintas fuentes de una manera sencilla.</p>
                    <p><strong>12.2.2.</strong>&nbsp;Todos los derechos de la informaci&oacute;n incluida en nuestra sindicaci&oacute;n RSS son propiedad del gestor de la web.</p>
                    <p><strong>12.2.3.</strong>&nbsp;Esta licencia no permite el uso de marcas, signos, logotipos ni cualquier otro s&iacute;mbolo titularidad del gestor de la web, salvo autorizaci&oacute;n expresa y por escrito de &eacute;ste.</p>
                    <p><strong>12.2.4.</strong>&nbsp;<b>LynoStudios</b> no se compromete con el usuario a mantener este servicio, ni a ning&uacute;n tipo de Acuerdo de Nivel de Servicio (SLA). Por tanto, el usuario no podr&aacute; ejercer ning&uacute;n tipo de reclamaci&oacute;n ni exigir contraprestaci&oacute;n alguna por su cancelaci&oacute;n y/o mal funcionamiento.</p>
                    <p><strong>12.3.</strong>&nbsp;Utilizaci&oacute;n del contenido de <b>LynoStudios</b></p>
                    <p><strong>12.3.1.</strong>&nbsp;El contenido informativo titularidad de <b>LynoStudios</b> no puede reproducirse en portales que no est&eacute;n debidamente autorizados por <b>LynoStudios</b> ni en ning&uacute;n caso por aquellos portales que contravengan la ley, la moral, las costumbres generalmente aceptadas y el orden p&uacute;blico, en general. A t&iacute;tulo meramente enunciativo y no exclusivo, no podr&aacute;n reproducirse los contenidos de <b>LynoStudios</b> en sitios que promuevan, faciliten o inciten al odio, la discriminaci&oacute;n, la violencia, el enga&ntilde;o, la difamaci&oacute;n, el abuso infantil, la pornograf&iacute;a, que vulneren la privacidad de los individuos o que vayan en contra de la pol&iacute;tica de privacidad de <b>LynoStudios</b>.</p>
                    <p><strong>12.3.2.</strong>&nbsp;Todo el contenido de la web que aparezca en sitios de el usuario debe estar debidamente identificado con el mensaje &ldquo;Informaci&oacute;n de www.<b><b><i>www.gamershub.es</i></b></b>&rdquo;, incluyendo un enlace a la Web, sin utilizar o reproducir en ning&uacute;n caso marcas, signos, logotipos ni cualquier otro s&iacute;mbolo propio de <b>LynoStudios</b>, salvo autorizaci&oacute;n expresa y por escrito de <b>LynoStudios</b> y salvo que el contenido lo lleve embebido.</p>
                    <p><strong>12.3.3.</strong>&nbsp;El usuario no puede cobrar ni directamente a sus propios usuarios ni indirectamente mediante la inserci&oacute;n de publicidad de cualquier tipo por acceder al contenido de <b>LynoStudios</b> ni explotarlo econ&oacute;micamente en modo alguno.</p>
                    <p><strong>12.3.4.</strong>&nbsp;El usuario debe utilizar la sindicaci&oacute;n en el modo en que se ofrece: t&iacute;tulo y sumario, y un v&iacute;nculo a la web que contiene la noticia original. El usuario no puede en ning&uacute;n caso cambiar, editar, a&ntilde;adir o desvirtuar la informaci&oacute;n original contenida en la sindicaci&oacute;n. Esta licencia no permite el uso de las noticias completas de la web en el portal del usuario.</p>
                    <p><strong>12.3.5.</strong>&nbsp;No se permite sugerir ning&uacute;n tipo de relaci&oacute;n entre el contenido de la web con productos comerciales, ideolog&iacute;as o puntos de vista incluidos en el portal o servicio del usuario.</p>
                    <p><strong>12.3.6.</strong>&nbsp;El usuario debe aceptar el control editorial de la web sobre la informaci&oacute;n que proveemos en nuestro RSS, as&iacute; como que la independencia y la integridad del contenido de la web es &uacute;nicamente responsabilidad de <b>LynoStudios</b>.</p>
                    <p><strong>12.4. Garant&iacute;as y responsabilidades legales</strong></p>
                    <p><strong>12.4.1.</strong>&nbsp;El usuario se compromete a:</p>
                    <p>a) cumplir con la ley<br />b) cumplir las presentes condiciones legales del servicio RSS.<br />c) que su portal no contenga informaci&oacute;n difamatoria, ilegal, pornogr&aacute;fica, ni a cualquier otra que pueda da&ntilde;ar la reputaci&oacute;n de <b>LynoStudios</b> o vulnerar los derechos de propiedad intelectual de terceros, asumiendo el usuario cuantas reclamaciones se presenten por dicha infracci&oacute;n de esta garant&iacute;a.<br />d) que los usuarios de su sitio conozcan y respeten las condiciones de esta licencia para el uso de material de <b>LynoStudios</b>.</p>
                    <p><strong>12.4.2.</strong>&nbsp;<b>LynoStudios</b> no garantiza, por el mero uso de su RSS, ning&uacute;n tipo de relaci&oacute;n directa del portal del usuario con el contenido de la web o con el proceso editorial de <b>LynoStudios</b>.</p>
                    <p><strong>12.4.3.</strong>&nbsp;Siempre en el marco de la legalidad vigente, <b>LynoStudios</b> rechaza cualquier responsabilidad por da&ntilde;o o p&eacute;rdida derivada del uso de este servicio de sindicaci&oacute;n en el portal del usuario.</p>
                    <p><strong>12.5. Gastos</strong></p>
                    <p>El usuario debe responsabilizarse de indemnizar a <b>LynoStudios</b> en el caso en que se produzcan gastos, costes legales o de litigaci&oacute;n derivados del mal uso de los contenidos de la web y del incumplimiento de las cl&aacute;usulas de esta licencia.</p>
                    <p><strong>12.6. Finalizaci&oacute;n</strong></p>
                    <p><strong>12.6.1.</strong>&nbsp;El usuario puede desistir de este acuerdo en cualquier momento, eliminando la sindicaci&oacute;n a su sitio y retirando todas las copias existentes de contenido de <b>LynoStudios</b> tanto en su portal como en los archivos que queden en su poder, asegurando su no utilizaci&oacute;n en el futuro.</p>
                    <p><strong>12.6.2.</strong>&nbsp;<b>LynoStudios</b> se reserva el derecho de restringir, eliminar o suspender esta sindicaci&oacute;n en cualquier momento sin ning&uacute;n tipo de responsabilidad legal. En ese caso, y una vez se lo hayamos notificado oficialmente, el usuario se compromete a destruir todas las copias existentes de contenido de la web tanto en su portal como en los archivos que queden en su poder, asegurando su no utilizaci&oacute;n en el futuro.</p>
                    <p><strong>12.7.</strong>&nbsp;General</p>
                    <p><strong>12.7.1.</strong>&nbsp;El usuario no puede cobrar, vender o poner a disposici&oacute;n los servicios cubiertos por este acuerdo a terceras partes.</p>
                    <p><strong>12.7.2.</strong>&nbsp;Este acuerdo se regula de acuerdo a la legislaci&oacute;n espa&ntilde;ola siendo la jurisdicci&oacute;n espa&ntilde;ola la &uacute;nica que puede conocer de cualquier caso derivado de problemas o disputas legales.</p>
                    <p><strong>12.7.3.</strong>&nbsp;Las partes, con expresa renuncia de cualquier fuero que pudiera corresponderles, someten cualquier interpretaci&oacute;n o controversia resultantes del presente acuerdo a la ley espa&ntilde;ola y a los Juzgados y Tribunales de&nbsp;Burgos&nbsp;capital.</p>
                    <p>&nbsp;</p>
                    <p><strong>13. POL&Iacute;TICA DE PRIVACIDAD Y PROTECCI&Oacute;N DE DATOS</strong></p>
                    <p>13.1. A los efectos de la Ley Org&aacute;nica 15/1999, de 13 de diciembre, de Protecci&oacute;n de Datos de Car&aacute;cter Personal, (LOPD) y en virtud de su art&iacute;culo 5, se informa a los usuarios del Sitio Web www.<b><b><i>www.gamershub.es</i></b></b> de que los datos de car&aacute;cter personal recabados a trav&eacute;s de formularios puestos a su disposici&oacute;n en la Web, ser&aacute;n incluidos en un fichero automatizado de datos de car&aacute;cter personal, titularidad de <b>LynoStudios</b> y bajo su responsabilidad.</p>
                    <p><strong>13.2.</strong>&nbsp;Los datos personales registrados tienen la finalidad de (I) posibilitar la gesti&oacute;n de solicitudes de participaci&oacute;n en los diferentes productos y servicios ofrecidos en cada momento, (II) la gesti&oacute;n, administraci&oacute;n, prestaci&oacute;n y mejora de los servicios ofrecidos o dise&ntilde;o de nuevos servicios, (III) el estudio de la utilizaci&oacute;n de los servicios por parte de los usuarios, (IV) poder mantener relaci&oacute;n con los usarios, como por ejemplo realizar avisos, para lo que se podr&aacute;n utilizar, entre otros, medios como el correo electr&oacute;nico y el tel&eacute;fono m&oacute;vil, adem&aacute;s de los tradicionales y (V) llevar a cabo acciones informativas sobre productos y servicios de <b>LynoStudios</b> as&iacute; como en nombre de terceros.</p>
                    <p><strong>13.3.</strong>&nbsp;<b>LynoStudios</b> no cede ni ceder&aacute; a terceros los datos personales del usuario sin su consentimiento por escrito y/o en caso de menores de edad sin el consentimiento expreso de los tutores legales.</p>
                    <p><strong>13.4.</strong>&nbsp;<b>LynoStudios</b> tambi&eacute;n certifica que los datos recogidos no contienen informaci&oacute;n de car&aacute;cter personal como religi&oacute;n o raza.</p>
                    <p><strong>13.5.</strong>&nbsp;El usuario garantiza que los datos personales facilitados a <b>LynoStudios</b> son propios y veraces, al mismo tiempo que se hace responsable de comunicar cualquier modificaci&oacute;n de los mismos.</p>
                    <p>Los campos marcados con un asterisco (*) en los formularios de registro a cumplimentar son estrictamente necesarios para atender cualquier petici&oacute;n o servicio solicitado, siendo voluntaria la inclusi&oacute;n de datos en los campos restantes.</p>
                    <p><strong>13.6.&nbsp;</strong>El env&iacute;o de datos personales a <b>LynoStudios</b>, bien a trav&eacute;s de formularios, mensajes de correo electr&oacute;nico o a trav&eacute;s de cualquier otro sistema activado en ese momento, supone el consentimiento expreso del remitente al tratamiento automatizado de los datos incluidos, as&iacute; como al env&iacute;o de comunicaciones con informaci&oacute;n sobre <b>LynoStudios</b>, boletines electr&oacute;nicos, ofertas o comunicaciones publicitarias y promocionales por cualquier v&iacute;a electr&oacute;nica o tradicional, a aquellos usuarios que hayan otorgado expresamente su consentimiento.</p>
                    <p><strong>13.7. Derechos de acceso, rectificaci&oacute;n, oposici&oacute;n y cancelaci&oacute;n de los usuarios.</strong></p>
                    <p><b>LynoStudios</b> garantiza que el usuario puede ejercer sus derechos de acceso, rectificaci&oacute;n, cancelaci&oacute;n y oposici&oacute;n de los datos facilitados en cualquier momento y se compromete, a la utilizaci&oacute;n de los datos facilitados, a respetar su confidencialidad y a utilizarlos de acuerdo con su finalidad.</p>
                    <p>Si el usuario decide darse de baja, sus datos ser&aacute;n totalmente cancelados.</p>
                    <p>Para el ejercicio de estos derechos el usuario puede enviar un correo electr&oacute;nico&nbsp;a contacto @ <b><b><i>www.gamershub.es</i></b></b>, acreditando la titularidad de los datos.</p>
                    <p><strong>13.8.</strong>&nbsp;El almacenamiento de los datos proporcionados por los usuarios se realiza de conformidad con todas las garant&iacute;as de seguridad exigidas por la legislaci&oacute;n vigente y, en especial, por el Real Decreto 1720/2007, de 21 de diciembre, por el que se aprueba el Reglamento de desarrollo de la Ley Org&aacute;nica 15/1999, de 13 de diciembre, de protecci&oacute;n de datos de car&aacute;cter personal, y ha establecido todos los medios t&eacute;cnicos a su alcance para evitar la p&eacute;rdida, mal uso, alteraci&oacute;n, acceso no autorizado y robo de los datos que el usuario facilite a trav&eacute;s del sitio web, sin perjuicio de informarle de que las medidas de seguridad en Internet no son inexpugnables.</p>
                    <p><b>LynoStudios</b> se compromete a cumplir con el deber de secreto y confidencialidad respecto de los datos personales contenidos en el fichero automatizado de acuerdo con la legislaci&oacute;n aplicable, as&iacute; como a conferirles un tratamiento seguro en las cesiones, que en su caso, puedan producirse.</p>
                    <p><strong>13.9.</strong>&nbsp;El tratamiento de los datos de car&aacute;cter personal, as&iacute; como el env&iacute;o de comunicaciones comerciales realizadas por medios electr&oacute;nicos, son conformes a la Ley Org&aacute;nica 15/1999, de 13 de diciembre, de Protecci&oacute;n de Datos de Car&aacute;cter Personal (B.O.E. de 14 de diciembre de 1999) y a la Ley 34/2002, de 11 de julio, de servicios de la Sociedad de Informaci&oacute;n y de Comercio Electr&oacute;nico (B.O.E. de 12 de julio de 2002).</p>
                    <p>&nbsp;</p>
                    <p><strong>14. COOKIES</strong></p>
                    <p><strong>14.1.</strong>&nbsp;Una cookie es una peque&ntilde;a cantidad de informaci&oacute;n que se almacena en un ordenador con el fin de identificar al navegador mientras interacciona con nuestros sitios Web. Las cookies pueden usarse para almacenar elementos como identificadores y preferencias del usuario. Un sitio Web puede establecer una cookie en el navegador si las preferencias de este lo permiten. Un navegador solo permite que un sitio Web acceda a las cookies que este establece, no a las que establecen otros sitios Web.</p>
                    <p><strong>14.2.</strong>&nbsp;El usuario acepta el uso de cookies y seguimientos de IPs. Nuestro analizador de tr&aacute;fico del sitio web utiliza cookies y seguimientos de IPs que nos permiten recoger datos a efectos estad&iacute;sticos como: fecha de la primera visita, n&uacute;mero de veces que se ha visitado, fecha de la &uacute;ltima visita, URL y dominio de la que proviene, explorador utilizado y resoluci&oacute;n de la pantalla. La utilizaci&oacute;n de cookies tambi&eacute;n facilita</p>
                    <p>a) el equilibrado y limitaci&oacute;n del tr&aacute;fico como m&eacute;todo de aseguramiento del servicio. b) Facilidad de uso: Hacer m&aacute;s f&aacute;cil y amigable el uso de la web y recordar aspectos del usuario: lenguaje, pa&iacute;s, navegador, etc&hellip; y c) Comerciales: Capacidad de orientar la informaci&oacute;n a cada usuario para permitir a los anunciantes o socios mostrar los anuncios o la informaci&oacute;n m&aacute;s apropiados y realizar un seguimiento de su efectividad.</p>
                    <p><strong>14.3.</strong>&nbsp;El usuario si lo desea puede desactivar y/o eliminar las cookies siguiendo las instrucciones de su navegador de Internet o configurarlo para que el navegador le avise cuando un servidor quiera guardar una cookie. Decir que Algunas de las cookies pueden ser fundamentales para utilizar ciertos servicios del sitio web.</p>
                    <p>Si Usted contin&uacute;a sin cambiar la configuraci&oacute;n, entenderemos que acepta la utilizaci&oacute;n de las cookies por parte del Sitio Web.</p>
                    <p><strong>14.4.</strong>&nbsp;<b>LynoStudios</b> en ning&uacute;n caso realiza registro de las actividades que el usuario lleva a cabo en la red ni elabora perfiles de &eacute;ste.</p>
                    <p><strong>14.5.</strong>&nbsp;Adobe Flash Player es una aplicaci&oacute;n y herramienta Web que permite un r&aacute;pido desarrollo del contenido din&aacute;mico. Flash (y otras aplicaciones similares) usan tecnolog&iacute;as para recordar par&aacute;metros de configuraci&oacute;n, preferencias y uso de forma similar a las cookies de los navegadores, pero se gestionan a trav&eacute;s de una interfaz distinta a la proporcionada por el navegador.</p>
                    <p><b>LynoStudios</b> emplea o puede emplear cookies de Adobe Flash en determinadas situaciones, en las que usamos Flash para proporcionar contenidos como clips de v&iacute;deo o animaciones. Puede acceder a las herramientas de gesti&oacute;n de Flash desde el sitio&nbsp;Web de Adobe directamente. <b>LynoStudios</b> no usa cookies de Flash para mostrar publicidad basada en intereses.</p>
                    <p><strong>14.6.</strong>&nbsp;Adem&aacute;s del uso de cookies de <b>LynoStudios</b> en nuestra red de Sitios Web, permitimos a terceros establecer cookies y acceder a ellas en su ordenador. El uso de las cookies de estas empresas est&aacute; sujeto a sus propias pol&iacute;ticas de privacidad, no a la Pol&iacute;tica de privacidad de <b>LynoStudios</b>.</p>
                    <p><strong>14.7.</strong>&nbsp;<b>LynoStudios</b> le agradece que active la aceptaci&oacute;n de cookies, esto nos ayuda a obtener datos m&aacute;s precisos que nos permiten mejorar el contenido y el dise&ntilde;o de nuestro Sitio Web para adaptarlo a sus preferencias.</p>
                    <p><strong>14.8.</strong>&nbsp;En caso de que <b>LynoStudios</b> prestara alg&uacute;n tipo de servicio especial en el que determine unas previsiones espec&iacute;ficas diferentes a &eacute;stas en lo relativo a la protecci&oacute;n de datos personales y la utilizaci&oacute;n de cookies, tendr&aacute; primac&iacute;a la aplicaci&oacute;n de las normas particulares indicadas para ese servicio en particular por encima de las presentes, en caso de incongruencia o contradicci&oacute;n.</p>
                    <p>&nbsp;</p>
                    <p><strong>15. ENLACES</strong></p>
                    <p>Enlaces a otros Sitios Web</p>
                    <p><strong>15.1.</strong>&nbsp;En el Sitio Web, el Usuario podr&aacute; encontrar enlaces a otras p&aacute;ginas web mediante&nbsp;diferentes botones, links, banners, etc., los cuales son gestionados por terceros. <b>LynoStudios</b> no ejercer&aacute; ning&uacute;n tipo de control sobre dichos sitios y contenidos y no asume ning&uacute;n tipo de responsabilidad por cualquier aspecto relativo a la p&aacute;gina web a la que se establece un enlace desde el Sitio Web.</p>
                    <p><strong>15.2.</strong>&nbsp;El establecimiento de cualquier tipo de enlace por parte del Sitio Web a otro sitio web ajeno no implica que exista alg&uacute;n tipo de relaci&oacute;n, colaboraci&oacute;n o dependencia entre <b>LynoStudios</b> y el responsable del sitio web ajeno.</p>
                    <p>Enlaces en otros sitios web con destino al Sitio Web</p>
                    <p><strong>15.3.</strong>&nbsp;Si cualquier Usuario, entidad o sitio web deseara establecer alg&uacute;n tipo de enlace con destino al Sitio Web deber&aacute; atenerse a las siguientes condiciones y requisitos:</p>
                    <p>El enlace se podr&aacute; dirigir a la P&aacute;gina Principal del Sitio Web.</p>
                    <p>El enlace debe ser absoluto y completo, es decir, debe llevar al Usuario, mediante un clic, a la propia direcci&oacute;n URL de <b>LynoStudios</b> www.<b><b><i>www.gamershub.es</i></b></b> y debe abarcar completamente toda la extensi&oacute;n de la pantalla del Sitio Web. En ning&uacute;n caso, salvo que <b>LynoStudios</b> lo autorice de manera expresa y por escrito, el sitio web que realiza el enlace podr&aacute; reproducir, de cualquier manera el Sitio Web, incluirlo como parte de su web o dentro de uno de sus &ldquo;frames&rdquo; o crear un &ldquo;browser&rdquo; sobre cualquiera de las p&aacute;ginas del Sitio Web. No pueden permitir la visualizaci&oacute;n de los contenidos a trav&eacute;s de direcciones de Internet distintas a las del propio Sitio Web (www.<b><b><i>www.gamershub.es</i></b></b>) o su red de comunidades de videojuegos y, en cualquier caso, esta prohibici&oacute;n incluye tambi&eacute;n que se visualicen conjuntamente con contenidos ajenos a la web, de forma que: (I) produzca error, confusi&oacute;n o enga&ntilde;o en los usuarios sobre la verdadera procedencia de los contenidos; (II) suponga un acto de comparaci&oacute;n o imitaci&oacute;n desleal; (III) sirva para aprovecharse de la reputaci&oacute;n de la marca o (IV) de cualquier otra forma resulte prohibido por la legislaci&oacute;n vigente o atente contra los usos y costumbres de buen hacer profesional que sean de general aceptaci&oacute;n en internet.</p>
                    <p>En la p&aacute;gina que establece el enlace no se podr&aacute; declarar de ninguna manera que <b>LynoStudios</b> ha autorizado tal enlace, salvo que <b>LynoStudios</b> lo haya hecho expresamente y por escrito. Si la entidad que realiza el enlace desde su p&aacute;gina al Sitio Web deseara incluir en su p&aacute;gina web la marca, denominaci&oacute;n, nombre comercial, r&oacute;tulo, logotipo, slogan o cualquier otro tipo de elemento identificativo de <b>LynoStudios</b> y/o del Sitio Web, deber&aacute; contar previamente con su autorizaci&oacute;n expresa y por escrito.</p>
                    <p><b>LynoStudios</b> no autoriza el establecimiento de un enlace al Sitio Web desde aquellas p&aacute;ginas web que de forma manifiesta fomenten el odio, el desprecio o la discriminaci&oacute;n por motivos de nacimiento, raza, sexo, religi&oacute;n, nacionalidad, opini&oacute;n o cualquier otra circunstancia personal o social y en general, que contravengan la moral, el orden p&uacute;blico o las normas sociales generalmente aceptadas.</p>
                    <p>No se realizar&aacute; desde la p&aacute;gina que introduce el enlace ning&uacute;n tipo de manifestaci&oacute;n falsa, inexacta o incorrecta sobre <b>LynoStudios</b>.</p>
                    <p><strong>15.4.</strong>&nbsp;<b>LynoStudios</b> no asume ning&uacute;n tipo de responsabilidad por cualquier aspecto relativo la p&aacute;gina web que establece ese enlace con destino al Sitio Web, en concreto, a t&iacute;tulo enunciativo y no taxativo, sobre su funcionamiento, acceso, datos, informaci&oacute;n, archivos, calidad y fiabilidad de sus productos y servicios, sus propios enlaces y/o cualquiera de sus contenidos, en general.</p>
                    <p>Servicios prestados por terceros a trav&eacute;s del Sitio Web</p>
                    <p><strong>15.5.</strong>&nbsp;<b>LynoStudios</b> no garantiza la licitud, fiabilidad y utilidad de los servicios prestados por terceros a trav&eacute;s del Sitio Web o sobre los que <b>LynoStudios</b> &uacute;nicamente act&uacute;e como medio cauce publicitario o prestador de servicio de intermediaci&oacute;n.</p>
                    <p><strong>15.6.</strong>&nbsp;<b>LynoStudios</b> no ser&aacute; responsable de los da&ntilde;os y perjuicios de toda naturaleza causados por los servicios prestados por terceros a trav&eacute;s del Sitio Web, y en particular, a t&iacute;tulo meramente enunciativo, los causados por: el incumplimiento de la ley, la moral o el orden p&uacute;blico; la incorporaci&oacute;n de virus o cualquier otro c&oacute;digo inform&aacute;tico, archivo o programa que pueda da&ntilde;ar, interrumpir o impedir el normal funcionamiento de cualquier software, hardware o equipo de telecomunicaciones; la infracci&oacute;n de los derechos de propiedad intelectual e industrial, de los secretos empresariales, de compromisos contractuales de cualquier clase. la realizaci&oacute;n de actos que constituyan publicidad il&iacute;cita, enga&ntilde;osa o desleal y, en general, que constituyan competencia desleal; la falta de veracidad, exactitud, calidad, pertinencia y/o actualidad de los contenidos transmitidos, difundidos, almacenados, recibidos, obtenidos, puestos a disposici&oacute;n o accesibles; la infracci&oacute;n de los derechos al honor, a la intimidad personal y familiar y a la imagen de las personas o, en general, cualquier tipo de derechos de terceros; la inadecuaci&oacute;n para cualquier clase de prop&oacute;sito y la defraudaci&oacute;n de las expectativas generadas, o los vicios y defectos que pudieran generarse en la relaci&oacute;n terceros; el incumplimiento, retraso en el cumplimiento, cumplimiento defectuoso o terminaci&oacute;n por cualquier causa de las obligaciones contra&iacute;das por terceros y contratos realizados con terceros.</p>
                    <p>&nbsp;</p>
                    <p><strong>16. DURACI&Oacute;N Y MODIFICACI&Oacute;N.</strong></p>
                    <p><strong>16.1.</strong>&nbsp;<b>LynoStudios</b> podr&aacute; modificar los t&eacute;rminos y condiciones aqu&iacute; estipuladas, total o parcialmente, publicando cualquier cambio en la misma forma en que aparecen estas condiciones generales o a trav&eacute;s de cualquier tipo de comunicaci&oacute;n dirigida a los Usuarios.</p>
                    <p><strong>16.2.</strong>&nbsp;La vigencia de estas condiciones generales coincide, por lo tanto, con el tiempo de su exposici&oacute;n, hasta que sean modificadas total o parcialmente, momento en el cual pasar&aacute;n a tener vigencia las condiciones generales modificadas.</p>
                    <p><strong>16.3.</strong>&nbsp;Con independencia de lo dispuesto en las condiciones particulares, <b>LynoStudios</b> podr&aacute; dar por terminado, suspender o interrumpir, en cualquier momento sin necesidad de preaviso, el acceso a los contenidos de la p&aacute;gina, sin posibilidad por parte del Usuario de exigir indemnizaci&oacute;n alguna. Tras dicha extinci&oacute;n, seguir&aacute;n vigentes las prohibiciones de uso de los contenidos expuestas anteriormente en las presentes condiciones generales.</p>
                    <p>&nbsp;</p>
                    <p><strong>17. GENERALIDADES</strong></p>
                    <p><strong>17.1.</strong>&nbsp;Los encabezamientos de las distintas cl&aacute;usulas son s&oacute;lo informativos, y no afectar&aacute;n, calificar&aacute;n o ampliar&aacute;n la interpretaci&oacute;n de las condiciones generales.</p>
                    <p><strong>17.2.</strong>&nbsp;En caso de existir discrepancia entre lo establecido en estas condiciones generales y las condiciones particulares de cada servicio espec&iacute;fico, prevalecer&aacute; lo dispuesto en &eacute;stas &uacute;ltimas.</p>
                    <p><strong>17.3.</strong>&nbsp;En el caso de que cualquier disposici&oacute;n o disposiciones de estas condiciones generales fuera(n) considerada(s) nula(s) o inaplicable(s), en su totalidad o en parte, por cualquier Juzgado, Tribunal u &oacute;rgano administrativo competente, dicha nulidad o inaplicaci&oacute;n no afectar&aacute; a las otras disposiciones de las condiciones generales ni a las condiciones particulares de los diferentes servicios de <b>LynoStudios</b>.</p>
                    <p><strong>17.4.</strong>&nbsp;El no ejercicio o ejecuci&oacute;n por parte de <b>LynoStudios</b> de cualquier derecho o disposici&oacute;n contenida en estas condiciones generales no constituir&aacute; una renuncia al mismo, salvo reconocimiento y acuerdo por escrito por su parte.</p>
                    <p>&nbsp;</p>
                    <p><strong>18. RESPONSABILIDAD DEL USUARIO</strong></p>
                    <p><strong>18.1.</strong>&nbsp;El usuario asumir&aacute; todos los gastos, costes e indemnizaciones que pudieran derivarse de procesos iniciados contra &eacute;l por el incumplimiento de garant&iacute;as y obligaciones que le fuera imputable conforme a lo establecido en el presente aviso legal.</p>
                    <p><strong>18.2.</strong>&nbsp;El usuario ser&aacute; responsable frente a cualquier posible reclamaci&oacute;n, derivada del incumplimiento por su parte de cualesquiera de las manifestaciones del presente documento, y se compromete a indemnizar a <b>LynoStudios</b> por cualquier incumplimiento de las garant&iacute;as otorgadas.</p>
                    <p>&nbsp;</p>
                    <p><strong>19. JURISDICCI&Oacute;N</strong></p>
                    <p>Las relaciones establecidas entre <b>LynoStudios</b> y el Usuario se regir&aacute;n por lo dispuesto en la normativa espa&ntilde;ola vigente acerca de la legislaci&oacute;n aplicable y la jurisdicci&oacute;n competente. No obstante, cualquier controversia se someter&aacute; a los Juzgados y Tribunales de la ciudad de Burgos.</p>
                    <p>La suscripci&oacute;n/registro a cualquier servicio ofrecido por el Sitio Web implica la aceptaci&oacute;n &iacute;ntegra de estas Condiciones Generales.</p>
                    <p>El usuario declara haber le&iacute;do estas Condiciones Generales y las acepta &iacute;ntegramente.</p>
                    <a target="_blank" class="pull-right" href="http://www.gamershub.es/documentos/GH%20AVISO%20LEGAL.pdf">Ver en formato .PDF</a>
                </div>
            </div>
        </div>
    </section>

@endsection